// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module HW_accel_fc_layer117 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [6:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;
output  [31:0] ap_return_6;
output  [31:0] ap_return_7;
output  [31:0] ap_return_8;
output  [31:0] ap_return_9;
output  [31:0] ap_return_10;
output  [31:0] ap_return_11;
output  [31:0] ap_return_12;
output  [31:0] ap_return_13;
output  [31:0] ap_return_14;
output  [31:0] ap_return_15;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_FC_layer_100_16_true_s_fu_8_ap_start;
wire    grp_FC_layer_100_16_true_s_fu_8_ap_done;
wire    grp_FC_layer_100_16_true_s_fu_8_ap_idle;
wire    grp_FC_layer_100_16_true_s_fu_8_ap_ready;
wire   [6:0] grp_FC_layer_100_16_true_s_fu_8_input_r_address0;
wire    grp_FC_layer_100_16_true_s_fu_8_input_r_ce0;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_0;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_1;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_2;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_3;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_4;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_5;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_6;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_7;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_8;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_9;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_10;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_11;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_12;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_13;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_14;
wire   [31:0] grp_FC_layer_100_16_true_s_fu_8_ap_return_15;
reg    grp_FC_layer_100_16_true_s_fu_8_ap_start_reg;
reg    ap_block_state1_ignore_call0;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;
reg    ap_block_state1;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 grp_FC_layer_100_16_true_s_fu_8_ap_start_reg = 1'b0;
end

HW_accel_FC_layer_100_16_true_s grp_FC_layer_100_16_true_s_fu_8(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_FC_layer_100_16_true_s_fu_8_ap_start),
    .ap_done(grp_FC_layer_100_16_true_s_fu_8_ap_done),
    .ap_idle(grp_FC_layer_100_16_true_s_fu_8_ap_idle),
    .ap_ready(grp_FC_layer_100_16_true_s_fu_8_ap_ready),
    .input_r_address0(grp_FC_layer_100_16_true_s_fu_8_input_r_address0),
    .input_r_ce0(grp_FC_layer_100_16_true_s_fu_8_input_r_ce0),
    .input_r_q0(input_r_q0),
    .ap_return_0(grp_FC_layer_100_16_true_s_fu_8_ap_return_0),
    .ap_return_1(grp_FC_layer_100_16_true_s_fu_8_ap_return_1),
    .ap_return_2(grp_FC_layer_100_16_true_s_fu_8_ap_return_2),
    .ap_return_3(grp_FC_layer_100_16_true_s_fu_8_ap_return_3),
    .ap_return_4(grp_FC_layer_100_16_true_s_fu_8_ap_return_4),
    .ap_return_5(grp_FC_layer_100_16_true_s_fu_8_ap_return_5),
    .ap_return_6(grp_FC_layer_100_16_true_s_fu_8_ap_return_6),
    .ap_return_7(grp_FC_layer_100_16_true_s_fu_8_ap_return_7),
    .ap_return_8(grp_FC_layer_100_16_true_s_fu_8_ap_return_8),
    .ap_return_9(grp_FC_layer_100_16_true_s_fu_8_ap_return_9),
    .ap_return_10(grp_FC_layer_100_16_true_s_fu_8_ap_return_10),
    .ap_return_11(grp_FC_layer_100_16_true_s_fu_8_ap_return_11),
    .ap_return_12(grp_FC_layer_100_16_true_s_fu_8_ap_return_12),
    .ap_return_13(grp_FC_layer_100_16_true_s_fu_8_ap_return_13),
    .ap_return_14(grp_FC_layer_100_16_true_s_fu_8_ap_return_14),
    .ap_return_15(grp_FC_layer_100_16_true_s_fu_8_ap_return_15)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_FC_layer_100_16_true_s_fu_8_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_FC_layer_100_16_true_s_fu_8_ap_start_reg <= 1'b0;
    end else begin
        if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_FC_layer_100_16_true_s_fu_8_ap_start_reg <= 1'b1;
        end else if ((grp_FC_layer_100_16_true_s_fu_8_ap_ready == 1'b1)) begin
            grp_FC_layer_100_16_true_s_fu_8_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_FC_layer_100_16_true_s_fu_8_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_FC_layer_100_16_true_s_fu_8_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_FC_layer_100_16_true_s_fu_8_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_FC_layer_100_16_true_s_fu_8_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state1_ignore_call0 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_return_0 = grp_FC_layer_100_16_true_s_fu_8_ap_return_0;

assign ap_return_1 = grp_FC_layer_100_16_true_s_fu_8_ap_return_1;

assign ap_return_10 = grp_FC_layer_100_16_true_s_fu_8_ap_return_10;

assign ap_return_11 = grp_FC_layer_100_16_true_s_fu_8_ap_return_11;

assign ap_return_12 = grp_FC_layer_100_16_true_s_fu_8_ap_return_12;

assign ap_return_13 = grp_FC_layer_100_16_true_s_fu_8_ap_return_13;

assign ap_return_14 = grp_FC_layer_100_16_true_s_fu_8_ap_return_14;

assign ap_return_15 = grp_FC_layer_100_16_true_s_fu_8_ap_return_15;

assign ap_return_2 = grp_FC_layer_100_16_true_s_fu_8_ap_return_2;

assign ap_return_3 = grp_FC_layer_100_16_true_s_fu_8_ap_return_3;

assign ap_return_4 = grp_FC_layer_100_16_true_s_fu_8_ap_return_4;

assign ap_return_5 = grp_FC_layer_100_16_true_s_fu_8_ap_return_5;

assign ap_return_6 = grp_FC_layer_100_16_true_s_fu_8_ap_return_6;

assign ap_return_7 = grp_FC_layer_100_16_true_s_fu_8_ap_return_7;

assign ap_return_8 = grp_FC_layer_100_16_true_s_fu_8_ap_return_8;

assign ap_return_9 = grp_FC_layer_100_16_true_s_fu_8_ap_return_9;

assign grp_FC_layer_100_16_true_s_fu_8_ap_start = grp_FC_layer_100_16_true_s_fu_8_ap_start_reg;

assign input_r_address0 = grp_FC_layer_100_16_true_s_fu_8_input_r_address0;

assign input_r_ce0 = grp_FC_layer_100_16_true_s_fu_8_input_r_ce0;

endmodule //HW_accel_fc_layer117
