-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HW_accel_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    window_2_2_promoted253 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_2_0_promoted251 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_2_1_promoted249 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_0_2_promoted247 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_0_0_promoted245 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_0_1_promoted243 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_1_2_promoted241 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_1_0_promoted239 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_1_1_promoted237 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_28664 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_18553 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_08442 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_227 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_116 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_05 : IN STD_LOGIC_VECTOR (31 downto 0);
    select_ln139_3 : IN STD_LOGIC_VECTOR (4 downto 0);
    mul_ln52 : IN STD_LOGIC_VECTOR (7 downto 0);
    ifmap_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    ifmap_ce0 : OUT STD_LOGIC;
    ifmap_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out_ap_vld : OUT STD_LOGIC;
    p_out1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out1_ap_vld : OUT STD_LOGIC;
    p_out2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out2_ap_vld : OUT STD_LOGIC;
    p_out3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out3_ap_vld : OUT STD_LOGIC;
    p_out4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out4_ap_vld : OUT STD_LOGIC;
    p_out5 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out5_ap_vld : OUT STD_LOGIC;
    p_out6 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out6_ap_vld : OUT STD_LOGIC;
    p_out7 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out7_ap_vld : OUT STD_LOGIC;
    p_out8 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out8_ap_vld : OUT STD_LOGIC;
    mux_case_28662_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_28662_out_ap_vld : OUT STD_LOGIC;
    mux_case_18551_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_18551_out_ap_vld : OUT STD_LOGIC;
    mux_case_08440_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_08440_out_ap_vld : OUT STD_LOGIC;
    mux_case_230_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_230_out_ap_vld : OUT STD_LOGIC;
    mux_case_119_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_119_out_ap_vld : OUT STD_LOGIC;
    mux_case_08_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_08_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of HW_accel_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv12_1A : STD_LOGIC_VECTOR (11 downto 0) := "000000011010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln49_fu_495_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln49_reg_855 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_reg_855_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln49_reg_855_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_fu_525_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_reg_859 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_reg_859_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_reg_859_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_reg_859_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_2_fu_533_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_2_reg_864 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_2_reg_864_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_2_reg_864_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_2_reg_864_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln52_6_fu_579_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal wj_fu_110 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln50_fu_555_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_wj_load : STD_LOGIC_VECTOR (1 downto 0);
    signal wi_fu_114 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_wi_load : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten150_fu_118 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln49_2_fu_501_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten150_load : STD_LOGIC_VECTOR (3 downto 0);
    signal mux_case_08_fu_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_119_fu_126 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_230_fu_130 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_08440_fu_134 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_18551_fu_138 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_28662_fu_142 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_fu_146 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_141_fu_150 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_142_fu_154 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_143_fu_158 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_144_fu_162 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_145_fu_166 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_146_fu_170 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_147_fu_174 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_148_fu_178 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln50_fu_519_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln49_fu_513_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln52_fu_541_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln52_fu_545_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_718_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_718_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_718_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_718_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal grp_fu_718_p10 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_718_p30 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_condition_467 : BOOLEAN;
    signal ap_condition_472 : BOOLEAN;
    signal ap_condition_476 : BOOLEAN;
    signal ap_condition_479 : BOOLEAN;
    signal ap_condition_482 : BOOLEAN;
    signal ap_condition_486 : BOOLEAN;
    signal ap_condition_489 : BOOLEAN;
    signal ap_condition_494 : BOOLEAN;
    signal ap_condition_497 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component HW_accel_ama_addmuladd_8ns_5ns_5ns_2ns_12_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        din2 : IN STD_LOGIC_VECTOR (4 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component HW_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    ama_addmuladd_8ns_5ns_5ns_2ns_12_4_1_U292 : component HW_accel_ama_addmuladd_8ns_5ns_5ns_2ns_12_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        din2_WIDTH => 5,
        din3_WIDTH => 2,
        dout_WIDTH => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => mul_ln52,
        din1 => grp_fu_718_p1,
        din2 => grp_fu_718_p2,
        din3 => grp_fu_718_p3,
        ce => ap_const_logic_1,
        dout => grp_fu_718_p4);

    flow_control_loop_pipe_sequential_init_U : component HW_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    empty_141_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_141_fu_150 <= window_1_0_promoted239;
                elsif ((ap_const_boolean_1 = ap_condition_467)) then 
                    empty_141_fu_150 <= ifmap_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_142_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_142_fu_154 <= window_1_2_promoted241;
                elsif ((ap_const_boolean_1 = ap_condition_472)) then 
                    empty_142_fu_154 <= ifmap_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_143_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_143_fu_158 <= window_0_1_promoted243;
                elsif ((ap_const_boolean_1 = ap_condition_476)) then 
                    empty_143_fu_158 <= ifmap_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_144_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_144_fu_162 <= window_0_0_promoted245;
                elsif ((ap_const_boolean_1 = ap_condition_479)) then 
                    empty_144_fu_162 <= ifmap_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_145_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_145_fu_166 <= window_0_2_promoted247;
                elsif ((ap_const_boolean_1 = ap_condition_482)) then 
                    empty_145_fu_166 <= ifmap_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_146_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_146_fu_170 <= window_2_1_promoted249;
                elsif ((ap_const_boolean_1 = ap_condition_486)) then 
                    empty_146_fu_170 <= ifmap_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_147_fu_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_147_fu_174 <= window_2_0_promoted251;
                elsif ((ap_const_boolean_1 = ap_condition_489)) then 
                    empty_147_fu_174 <= ifmap_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_148_fu_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_148_fu_178 <= window_2_2_promoted253;
                elsif ((ap_const_boolean_1 = ap_condition_494)) then 
                    empty_148_fu_178 <= ifmap_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    empty_fu_146 <= window_1_1_promoted237;
                elsif ((ap_const_boolean_1 = ap_condition_497)) then 
                    empty_fu_146 <= ifmap_q0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten150_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln49_fu_495_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten150_fu_118 <= add_ln49_2_fu_501_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten150_fu_118 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    mux_case_08440_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    mux_case_08440_fu_134 <= mux_case_08442;
                elsif ((ap_const_boolean_1 = ap_condition_482)) then 
                    mux_case_08440_fu_134 <= ifmap_q0;
                end if;
            end if; 
        end if;
    end process;

    mux_case_08_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    mux_case_08_fu_122 <= mux_case_05;
                elsif ((ap_const_boolean_1 = ap_condition_476)) then 
                    mux_case_08_fu_122 <= ifmap_q0;
                end if;
            end if; 
        end if;
    end process;

    mux_case_119_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    mux_case_119_fu_126 <= mux_case_116;
                elsif ((ap_const_boolean_1 = ap_condition_497)) then 
                    mux_case_119_fu_126 <= ifmap_q0;
                end if;
            end if; 
        end if;
    end process;

    mux_case_18551_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    mux_case_18551_fu_138 <= mux_case_18553;
                elsif ((ap_const_boolean_1 = ap_condition_472)) then 
                    mux_case_18551_fu_138 <= ifmap_q0;
                end if;
            end if; 
        end if;
    end process;

    mux_case_230_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    mux_case_230_fu_130 <= mux_case_227;
                elsif ((ap_const_boolean_1 = ap_condition_486)) then 
                    mux_case_230_fu_130 <= ifmap_q0;
                end if;
            end if; 
        end if;
    end process;

    mux_case_28662_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    mux_case_28662_fu_142 <= mux_case_28664;
                elsif ((ap_const_boolean_1 = ap_condition_494)) then 
                    mux_case_28662_fu_142 <= ifmap_q0;
                end if;
            end if; 
        end if;
    end process;

    wi_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln49_fu_495_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    wi_fu_114 <= select_ln52_2_fu_533_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    wi_fu_114 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    wj_fu_110_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln49_fu_495_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    wj_fu_110 <= add_ln50_fu_555_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    wj_fu_110 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln49_reg_855 <= icmp_ln49_fu_495_p2;
                icmp_ln49_reg_855_pp0_iter1_reg <= icmp_ln49_reg_855;
                select_ln52_2_reg_864_pp0_iter1_reg <= select_ln52_2_reg_864;
                select_ln52_reg_859_pp0_iter1_reg <= select_ln52_reg_859;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                icmp_ln49_reg_855_pp0_iter2_reg <= icmp_ln49_reg_855_pp0_iter1_reg;
                select_ln52_2_reg_864_pp0_iter2_reg <= select_ln52_2_reg_864_pp0_iter1_reg;
                select_ln52_2_reg_864_pp0_iter3_reg <= select_ln52_2_reg_864_pp0_iter2_reg;
                select_ln52_reg_859_pp0_iter2_reg <= select_ln52_reg_859_pp0_iter1_reg;
                select_ln52_reg_859_pp0_iter3_reg <= select_ln52_reg_859_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln49_fu_495_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln52_2_reg_864 <= select_ln52_2_fu_533_p3;
                select_ln52_reg_859 <= select_ln52_fu_525_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln49_2_fu_501_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten150_load) + unsigned(ap_const_lv4_1));
    add_ln49_fu_513_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_wi_load) + unsigned(ap_const_lv2_1));
    add_ln50_fu_555_p2 <= std_logic_vector(unsigned(select_ln52_fu_525_p3) + unsigned(ap_const_lv2_1));
    add_ln52_fu_545_p2 <= std_logic_vector(unsigned(select_ln139_3) + unsigned(zext_ln52_fu_541_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_467_assign_proc : process(ap_enable_reg_pp0_iter4, select_ln52_reg_859_pp0_iter3_reg, select_ln52_2_reg_864_pp0_iter3_reg)
    begin
                ap_condition_467 <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (select_ln52_2_reg_864_pp0_iter3_reg = ap_const_lv2_1) and (select_ln52_reg_859_pp0_iter3_reg = ap_const_lv2_0));
    end process;


    ap_condition_472_assign_proc : process(ap_enable_reg_pp0_iter4, select_ln52_reg_859_pp0_iter3_reg, select_ln52_2_reg_864_pp0_iter3_reg)
    begin
                ap_condition_472 <= (not((select_ln52_reg_859_pp0_iter3_reg = ap_const_lv2_0)) and not((select_ln52_reg_859_pp0_iter3_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (select_ln52_2_reg_864_pp0_iter3_reg = ap_const_lv2_1));
    end process;


    ap_condition_476_assign_proc : process(ap_enable_reg_pp0_iter4, select_ln52_reg_859_pp0_iter3_reg, select_ln52_2_reg_864_pp0_iter3_reg)
    begin
                ap_condition_476 <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (select_ln52_2_reg_864_pp0_iter3_reg = ap_const_lv2_0) and (select_ln52_reg_859_pp0_iter3_reg = ap_const_lv2_1));
    end process;


    ap_condition_479_assign_proc : process(ap_enable_reg_pp0_iter4, select_ln52_reg_859_pp0_iter3_reg, select_ln52_2_reg_864_pp0_iter3_reg)
    begin
                ap_condition_479 <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (select_ln52_2_reg_864_pp0_iter3_reg = ap_const_lv2_0) and (select_ln52_reg_859_pp0_iter3_reg = ap_const_lv2_0));
    end process;


    ap_condition_482_assign_proc : process(ap_enable_reg_pp0_iter4, select_ln52_reg_859_pp0_iter3_reg, select_ln52_2_reg_864_pp0_iter3_reg)
    begin
                ap_condition_482 <= (not((select_ln52_reg_859_pp0_iter3_reg = ap_const_lv2_0)) and not((select_ln52_reg_859_pp0_iter3_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (select_ln52_2_reg_864_pp0_iter3_reg = ap_const_lv2_0));
    end process;


    ap_condition_486_assign_proc : process(ap_enable_reg_pp0_iter4, select_ln52_reg_859_pp0_iter3_reg, select_ln52_2_reg_864_pp0_iter3_reg)
    begin
                ap_condition_486 <= (not((select_ln52_2_reg_864_pp0_iter3_reg = ap_const_lv2_1)) and not((select_ln52_2_reg_864_pp0_iter3_reg = ap_const_lv2_0)) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (select_ln52_reg_859_pp0_iter3_reg = ap_const_lv2_1));
    end process;


    ap_condition_489_assign_proc : process(ap_enable_reg_pp0_iter4, select_ln52_reg_859_pp0_iter3_reg, select_ln52_2_reg_864_pp0_iter3_reg)
    begin
                ap_condition_489 <= (not((select_ln52_2_reg_864_pp0_iter3_reg = ap_const_lv2_1)) and not((select_ln52_2_reg_864_pp0_iter3_reg = ap_const_lv2_0)) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (select_ln52_reg_859_pp0_iter3_reg = ap_const_lv2_0));
    end process;


    ap_condition_494_assign_proc : process(ap_enable_reg_pp0_iter4, select_ln52_reg_859_pp0_iter3_reg, select_ln52_2_reg_864_pp0_iter3_reg)
    begin
                ap_condition_494 <= (not((select_ln52_reg_859_pp0_iter3_reg = ap_const_lv2_0)) and not((select_ln52_2_reg_864_pp0_iter3_reg = ap_const_lv2_1)) and not((select_ln52_reg_859_pp0_iter3_reg = ap_const_lv2_1)) and not((select_ln52_2_reg_864_pp0_iter3_reg = ap_const_lv2_0)) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1));
    end process;


    ap_condition_497_assign_proc : process(ap_enable_reg_pp0_iter4, select_ln52_reg_859_pp0_iter3_reg, select_ln52_2_reg_864_pp0_iter3_reg)
    begin
                ap_condition_497 <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (select_ln52_2_reg_864_pp0_iter3_reg = ap_const_lv2_1) and (select_ln52_reg_859_pp0_iter3_reg = ap_const_lv2_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln49_fu_495_p2)
    begin
        if (((icmp_ln49_fu_495_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter3_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter3_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten150_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten150_fu_118)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten150_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten150_load <= indvar_flatten150_fu_118;
        end if; 
    end process;


    ap_sig_allocacmp_wi_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, wi_fu_114)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_wi_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_wi_load <= wi_fu_114;
        end if; 
    end process;


    ap_sig_allocacmp_wj_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, wj_fu_110, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_wj_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_wj_load <= wj_fu_110;
        end if; 
    end process;

    grp_fu_718_p1 <= grp_fu_718_p10(5 - 1 downto 0);
    grp_fu_718_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln52_fu_545_p2),8));
    grp_fu_718_p2 <= ap_const_lv12_1A(5 - 1 downto 0);
    grp_fu_718_p3 <= grp_fu_718_p30(2 - 1 downto 0);
    grp_fu_718_p30 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln52_reg_859_pp0_iter1_reg),12));
    icmp_ln49_fu_495_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten150_load = ap_const_lv4_9) else "0";
    icmp_ln50_fu_519_p2 <= "1" when (ap_sig_allocacmp_wj_load = ap_const_lv2_3) else "0";
    ifmap_address0 <= zext_ln52_6_fu_579_p1(12 - 1 downto 0);

    ifmap_ce0_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            ifmap_ce0 <= ap_const_logic_1;
        else 
            ifmap_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    mux_case_08440_out <= mux_case_08440_fu_134;

    mux_case_08440_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln49_reg_855_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln49_reg_855_pp0_iter2_reg = ap_const_lv1_1))) then 
            mux_case_08440_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_08440_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mux_case_08_out <= mux_case_08_fu_122;

    mux_case_08_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln49_reg_855_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln49_reg_855_pp0_iter2_reg = ap_const_lv1_1))) then 
            mux_case_08_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_08_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mux_case_119_out <= mux_case_119_fu_126;

    mux_case_119_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln49_reg_855_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln49_reg_855_pp0_iter2_reg = ap_const_lv1_1))) then 
            mux_case_119_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_119_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mux_case_18551_out <= mux_case_18551_fu_138;

    mux_case_18551_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln49_reg_855_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln49_reg_855_pp0_iter2_reg = ap_const_lv1_1))) then 
            mux_case_18551_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_18551_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mux_case_230_out <= mux_case_230_fu_130;

    mux_case_230_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln49_reg_855_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln49_reg_855_pp0_iter2_reg = ap_const_lv1_1))) then 
            mux_case_230_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_230_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mux_case_28662_out <= mux_case_28662_fu_142;

    mux_case_28662_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln49_reg_855_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln49_reg_855_pp0_iter2_reg = ap_const_lv1_1))) then 
            mux_case_28662_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_28662_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out <= empty_148_fu_178;
    p_out1 <= empty_147_fu_174;

    p_out1_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln49_reg_855_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln49_reg_855_pp0_iter2_reg = ap_const_lv1_1))) then 
            p_out1_ap_vld <= ap_const_logic_1;
        else 
            p_out1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out2 <= empty_146_fu_170;

    p_out2_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln49_reg_855_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln49_reg_855_pp0_iter2_reg = ap_const_lv1_1))) then 
            p_out2_ap_vld <= ap_const_logic_1;
        else 
            p_out2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out3 <= empty_145_fu_166;

    p_out3_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln49_reg_855_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln49_reg_855_pp0_iter2_reg = ap_const_lv1_1))) then 
            p_out3_ap_vld <= ap_const_logic_1;
        else 
            p_out3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out4 <= empty_144_fu_162;

    p_out4_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln49_reg_855_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln49_reg_855_pp0_iter2_reg = ap_const_lv1_1))) then 
            p_out4_ap_vld <= ap_const_logic_1;
        else 
            p_out4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out5 <= empty_143_fu_158;

    p_out5_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln49_reg_855_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln49_reg_855_pp0_iter2_reg = ap_const_lv1_1))) then 
            p_out5_ap_vld <= ap_const_logic_1;
        else 
            p_out5_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out6 <= empty_142_fu_154;

    p_out6_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln49_reg_855_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln49_reg_855_pp0_iter2_reg = ap_const_lv1_1))) then 
            p_out6_ap_vld <= ap_const_logic_1;
        else 
            p_out6_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out7 <= empty_141_fu_150;

    p_out7_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln49_reg_855_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln49_reg_855_pp0_iter2_reg = ap_const_lv1_1))) then 
            p_out7_ap_vld <= ap_const_logic_1;
        else 
            p_out7_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out8 <= empty_fu_146;

    p_out8_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln49_reg_855_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln49_reg_855_pp0_iter2_reg = ap_const_lv1_1))) then 
            p_out8_ap_vld <= ap_const_logic_1;
        else 
            p_out8_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_out_ap_vld_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln49_reg_855_pp0_iter2_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln49_reg_855_pp0_iter2_reg = ap_const_lv1_1))) then 
            p_out_ap_vld <= ap_const_logic_1;
        else 
            p_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln52_2_fu_533_p3 <= 
        add_ln49_fu_513_p2 when (icmp_ln50_fu_519_p2(0) = '1') else 
        ap_sig_allocacmp_wi_load;
    select_ln52_fu_525_p3 <= 
        ap_const_lv2_0 when (icmp_ln50_fu_519_p2(0) = '1') else 
        ap_sig_allocacmp_wj_load;
    zext_ln52_6_fu_579_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_718_p4),64));
    zext_ln52_fu_541_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln52_2_fu_533_p3),5));
end behav;
