// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module HW_accel_Conv_func_4_12_4_10_Pipeline_loadWinFull_VITIS_LOOP_50_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        window_2_2_promoted253,
        window_2_0_promoted251,
        window_2_1_promoted249,
        window_0_2_promoted247,
        window_0_0_promoted245,
        window_0_1_promoted243,
        window_1_2_promoted241,
        window_1_0_promoted239,
        window_1_1_promoted237,
        mux_case_28664,
        mux_case_18553,
        mux_case_08442,
        mux_case_227,
        mux_case_116,
        mux_case_05,
        select_ln139_6,
        sub_ln52,
        ifmap_address0,
        ifmap_ce0,
        ifmap_q0,
        p_out,
        p_out_ap_vld,
        p_out1,
        p_out1_ap_vld,
        p_out2,
        p_out2_ap_vld,
        p_out3,
        p_out3_ap_vld,
        p_out4,
        p_out4_ap_vld,
        p_out5,
        p_out5_ap_vld,
        p_out6,
        p_out6_ap_vld,
        p_out7,
        p_out7_ap_vld,
        p_out8,
        p_out8_ap_vld,
        mux_case_28662_out,
        mux_case_28662_out_ap_vld,
        mux_case_18551_out,
        mux_case_18551_out_ap_vld,
        mux_case_08440_out,
        mux_case_08440_out_ap_vld,
        mux_case_230_out,
        mux_case_230_out_ap_vld,
        mux_case_119_out,
        mux_case_119_out_ap_vld,
        mux_case_08_out,
        mux_case_08_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] window_2_2_promoted253;
input  [31:0] window_2_0_promoted251;
input  [31:0] window_2_1_promoted249;
input  [31:0] window_0_2_promoted247;
input  [31:0] window_0_0_promoted245;
input  [31:0] window_0_1_promoted243;
input  [31:0] window_1_2_promoted241;
input  [31:0] window_1_0_promoted239;
input  [31:0] window_1_1_promoted237;
input  [31:0] mux_case_28664;
input  [31:0] mux_case_18553;
input  [31:0] mux_case_08442;
input  [31:0] mux_case_227;
input  [31:0] mux_case_116;
input  [31:0] mux_case_05;
input  [3:0] select_ln139_6;
input  [7:0] sub_ln52;
output  [9:0] ifmap_address0;
output   ifmap_ce0;
input  [31:0] ifmap_q0;
output  [31:0] p_out;
output   p_out_ap_vld;
output  [31:0] p_out1;
output   p_out1_ap_vld;
output  [31:0] p_out2;
output   p_out2_ap_vld;
output  [31:0] p_out3;
output   p_out3_ap_vld;
output  [31:0] p_out4;
output   p_out4_ap_vld;
output  [31:0] p_out5;
output   p_out5_ap_vld;
output  [31:0] p_out6;
output   p_out6_ap_vld;
output  [31:0] p_out7;
output   p_out7_ap_vld;
output  [31:0] p_out8;
output   p_out8_ap_vld;
output  [31:0] mux_case_28662_out;
output   mux_case_28662_out_ap_vld;
output  [31:0] mux_case_18551_out;
output   mux_case_18551_out_ap_vld;
output  [31:0] mux_case_08440_out;
output   mux_case_08440_out_ap_vld;
output  [31:0] mux_case_230_out;
output   mux_case_230_out_ap_vld;
output  [31:0] mux_case_119_out;
output   mux_case_119_out_ap_vld;
output  [31:0] mux_case_08_out;
output   mux_case_08_out_ap_vld;

reg ap_idle;
reg ifmap_ce0;
reg p_out_ap_vld;
reg p_out1_ap_vld;
reg p_out2_ap_vld;
reg p_out3_ap_vld;
reg p_out4_ap_vld;
reg p_out5_ap_vld;
reg p_out6_ap_vld;
reg p_out7_ap_vld;
reg p_out8_ap_vld;
reg mux_case_28662_out_ap_vld;
reg mux_case_18551_out_ap_vld;
reg mux_case_08440_out_ap_vld;
reg mux_case_230_out_ap_vld;
reg mux_case_119_out_ap_vld;
reg mux_case_08_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln49_fu_509_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire  signed [8:0] sub_ln52_cast_fu_412_p1;
reg  signed [8:0] sub_ln52_cast_reg_907;
reg   [0:0] icmp_ln49_reg_912;
wire   [1:0] select_ln52_fu_539_p3;
reg   [1:0] select_ln52_reg_916;
reg   [1:0] select_ln52_reg_916_pp0_iter1_reg;
wire   [1:0] select_ln52_3_fu_547_p3;
reg   [1:0] select_ln52_3_reg_921;
reg   [1:0] select_ln52_3_reg_921_pp0_iter1_reg;
wire   [3:0] add_ln52_fu_559_p2;
reg   [3:0] add_ln52_reg_925;
wire   [63:0] zext_ln52_7_fu_641_p1;
wire    ap_block_pp0_stage0;
reg   [1:0] wj_fu_120;
wire   [1:0] add_ln50_fu_565_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_wj_load;
reg   [1:0] wi_fu_124;
reg   [1:0] ap_sig_allocacmp_wi_load;
reg   [3:0] indvar_flatten150_fu_128;
wire   [3:0] add_ln49_3_fu_515_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten150_load;
reg   [31:0] mux_case_08_fu_132;
reg   [31:0] mux_case_119_fu_136;
reg   [31:0] mux_case_230_fu_140;
reg   [31:0] mux_case_08440_fu_144;
reg   [31:0] mux_case_18551_fu_148;
reg   [31:0] mux_case_28662_fu_152;
reg   [31:0] empty_fu_156;
reg   [31:0] empty_191_fu_160;
reg   [31:0] empty_192_fu_164;
reg   [31:0] empty_193_fu_168;
reg   [31:0] empty_194_fu_172;
reg   [31:0] empty_195_fu_176;
reg   [31:0] empty_196_fu_180;
reg   [31:0] empty_197_fu_184;
reg   [31:0] empty_198_fu_188;
wire    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln50_fu_533_p2;
wire   [1:0] add_ln49_fu_527_p2;
wire   [3:0] zext_ln52_5_fu_555_p1;
wire   [8:0] zext_ln52_fu_586_p1;
wire   [8:0] add_ln52_3_fu_589_p2;
wire   [12:0] tmp_fu_594_p3;
wire   [10:0] tmp_1_fu_606_p3;
wire  signed [63:0] sext_ln52_fu_602_p1;
wire  signed [63:0] sext_ln52_1_fu_614_p1;
wire   [63:0] sub_ln52_1_fu_618_p2;
wire   [7:0] tmp_57_cast_fu_624_p4;
wire   [9:0] tmp_s_fu_634_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_440;
reg    ap_condition_445;
reg    ap_condition_449;
reg    ap_condition_452;
reg    ap_condition_455;
reg    ap_condition_459;
reg    ap_condition_462;
reg    ap_condition_467;
reg    ap_condition_470;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

HW_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_191_fu_160 <= window_1_0_promoted239;
        end else if ((1'b1 == ap_condition_440)) begin
            empty_191_fu_160 <= ifmap_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_192_fu_164 <= window_1_2_promoted241;
        end else if ((1'b1 == ap_condition_445)) begin
            empty_192_fu_164 <= ifmap_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_193_fu_168 <= window_0_1_promoted243;
        end else if ((1'b1 == ap_condition_449)) begin
            empty_193_fu_168 <= ifmap_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_194_fu_172 <= window_0_0_promoted245;
        end else if ((1'b1 == ap_condition_452)) begin
            empty_194_fu_172 <= ifmap_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_195_fu_176 <= window_0_2_promoted247;
        end else if ((1'b1 == ap_condition_455)) begin
            empty_195_fu_176 <= ifmap_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_196_fu_180 <= window_2_1_promoted249;
        end else if ((1'b1 == ap_condition_459)) begin
            empty_196_fu_180 <= ifmap_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_197_fu_184 <= window_2_0_promoted251;
        end else if ((1'b1 == ap_condition_462)) begin
            empty_197_fu_184 <= ifmap_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_198_fu_188 <= window_2_2_promoted253;
        end else if ((1'b1 == ap_condition_467)) begin
            empty_198_fu_188 <= ifmap_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            empty_fu_156 <= window_1_1_promoted237;
        end else if ((1'b1 == ap_condition_470)) begin
            empty_fu_156 <= ifmap_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln49_fu_509_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten150_fu_128 <= add_ln49_3_fu_515_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten150_fu_128 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            mux_case_08440_fu_144 <= mux_case_08442;
        end else if ((1'b1 == ap_condition_455)) begin
            mux_case_08440_fu_144 <= ifmap_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            mux_case_08_fu_132 <= mux_case_05;
        end else if ((1'b1 == ap_condition_449)) begin
            mux_case_08_fu_132 <= ifmap_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            mux_case_119_fu_136 <= mux_case_116;
        end else if ((1'b1 == ap_condition_470)) begin
            mux_case_119_fu_136 <= ifmap_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            mux_case_18551_fu_148 <= mux_case_18553;
        end else if ((1'b1 == ap_condition_445)) begin
            mux_case_18551_fu_148 <= ifmap_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            mux_case_230_fu_140 <= mux_case_227;
        end else if ((1'b1 == ap_condition_459)) begin
            mux_case_230_fu_140 <= ifmap_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
            mux_case_28662_fu_152 <= mux_case_28664;
        end else if ((1'b1 == ap_condition_467)) begin
            mux_case_28662_fu_152 <= ifmap_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln49_fu_509_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            wi_fu_124 <= select_ln52_3_fu_547_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            wi_fu_124 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln49_fu_509_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            wj_fu_120 <= add_ln50_fu_565_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            wj_fu_120 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln49_fu_509_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln52_reg_925 <= add_ln52_fu_559_p2;
        select_ln52_3_reg_921 <= select_ln52_3_fu_547_p3;
        select_ln52_reg_916 <= select_ln52_fu_539_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln49_reg_912 <= icmp_ln49_fu_509_p2;
        select_ln52_3_reg_921_pp0_iter1_reg <= select_ln52_3_reg_921;
        select_ln52_reg_916_pp0_iter1_reg <= select_ln52_reg_916;
        sub_ln52_cast_reg_907 <= sub_ln52_cast_fu_412_p1;
    end
end

always @ (*) begin
    if (((icmp_ln49_fu_509_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten150_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten150_load = indvar_flatten150_fu_128;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_wi_load = 2'd0;
    end else begin
        ap_sig_allocacmp_wi_load = wi_fu_124;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_wj_load = 2'd0;
    end else begin
        ap_sig_allocacmp_wj_load = wj_fu_120;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ifmap_ce0 = 1'b1;
    end else begin
        ifmap_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_reg_912 == 1'd1))) begin
        mux_case_08440_out_ap_vld = 1'b1;
    end else begin
        mux_case_08440_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_reg_912 == 1'd1))) begin
        mux_case_08_out_ap_vld = 1'b1;
    end else begin
        mux_case_08_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_reg_912 == 1'd1))) begin
        mux_case_119_out_ap_vld = 1'b1;
    end else begin
        mux_case_119_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_reg_912 == 1'd1))) begin
        mux_case_18551_out_ap_vld = 1'b1;
    end else begin
        mux_case_18551_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_reg_912 == 1'd1))) begin
        mux_case_230_out_ap_vld = 1'b1;
    end else begin
        mux_case_230_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_reg_912 == 1'd1))) begin
        mux_case_28662_out_ap_vld = 1'b1;
    end else begin
        mux_case_28662_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_reg_912 == 1'd1))) begin
        p_out1_ap_vld = 1'b1;
    end else begin
        p_out1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_reg_912 == 1'd1))) begin
        p_out2_ap_vld = 1'b1;
    end else begin
        p_out2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_reg_912 == 1'd1))) begin
        p_out3_ap_vld = 1'b1;
    end else begin
        p_out3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_reg_912 == 1'd1))) begin
        p_out4_ap_vld = 1'b1;
    end else begin
        p_out4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_reg_912 == 1'd1))) begin
        p_out5_ap_vld = 1'b1;
    end else begin
        p_out5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_reg_912 == 1'd1))) begin
        p_out6_ap_vld = 1'b1;
    end else begin
        p_out6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_reg_912 == 1'd1))) begin
        p_out7_ap_vld = 1'b1;
    end else begin
        p_out7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_reg_912 == 1'd1))) begin
        p_out8_ap_vld = 1'b1;
    end else begin
        p_out8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln49_reg_912 == 1'd1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln49_3_fu_515_p2 = (ap_sig_allocacmp_indvar_flatten150_load + 4'd1);

assign add_ln49_fu_527_p2 = (ap_sig_allocacmp_wi_load + 2'd1);

assign add_ln50_fu_565_p2 = (select_ln52_fu_539_p3 + 2'd1);

assign add_ln52_3_fu_589_p2 = ($signed(sub_ln52_cast_reg_907) + $signed(zext_ln52_fu_586_p1));

assign add_ln52_fu_559_p2 = (select_ln139_6 + zext_ln52_5_fu_555_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_440 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln52_3_reg_921_pp0_iter1_reg == 2'd1) & (select_ln52_reg_916_pp0_iter1_reg == 2'd0));
end

always @ (*) begin
    ap_condition_445 = (~(select_ln52_reg_916_pp0_iter1_reg == 2'd0) & ~(select_ln52_reg_916_pp0_iter1_reg == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln52_3_reg_921_pp0_iter1_reg == 2'd1));
end

always @ (*) begin
    ap_condition_449 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln52_3_reg_921_pp0_iter1_reg == 2'd0) & (select_ln52_reg_916_pp0_iter1_reg == 2'd1));
end

always @ (*) begin
    ap_condition_452 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln52_3_reg_921_pp0_iter1_reg == 2'd0) & (select_ln52_reg_916_pp0_iter1_reg == 2'd0));
end

always @ (*) begin
    ap_condition_455 = (~(select_ln52_reg_916_pp0_iter1_reg == 2'd0) & ~(select_ln52_reg_916_pp0_iter1_reg == 2'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln52_3_reg_921_pp0_iter1_reg == 2'd0));
end

always @ (*) begin
    ap_condition_459 = (~(select_ln52_3_reg_921_pp0_iter1_reg == 2'd1) & ~(select_ln52_3_reg_921_pp0_iter1_reg == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln52_reg_916_pp0_iter1_reg == 2'd1));
end

always @ (*) begin
    ap_condition_462 = (~(select_ln52_3_reg_921_pp0_iter1_reg == 2'd1) & ~(select_ln52_3_reg_921_pp0_iter1_reg == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln52_reg_916_pp0_iter1_reg == 2'd0));
end

always @ (*) begin
    ap_condition_467 = (~(select_ln52_reg_916_pp0_iter1_reg == 2'd0) & ~(select_ln52_3_reg_921_pp0_iter1_reg == 2'd1) & ~(select_ln52_reg_916_pp0_iter1_reg == 2'd1) & ~(select_ln52_3_reg_921_pp0_iter1_reg == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_condition_470 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (select_ln52_3_reg_921_pp0_iter1_reg == 2'd1) & (select_ln52_reg_916_pp0_iter1_reg == 2'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln49_fu_509_p2 = ((ap_sig_allocacmp_indvar_flatten150_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln50_fu_533_p2 = ((ap_sig_allocacmp_wj_load == 2'd3) ? 1'b1 : 1'b0);

assign ifmap_address0 = zext_ln52_7_fu_641_p1;

assign mux_case_08440_out = mux_case_08440_fu_144;

assign mux_case_08_out = mux_case_08_fu_132;

assign mux_case_119_out = mux_case_119_fu_136;

assign mux_case_18551_out = mux_case_18551_fu_148;

assign mux_case_230_out = mux_case_230_fu_140;

assign mux_case_28662_out = mux_case_28662_fu_152;

assign p_out = empty_198_fu_188;

assign p_out1 = empty_197_fu_184;

assign p_out2 = empty_196_fu_180;

assign p_out3 = empty_195_fu_176;

assign p_out4 = empty_194_fu_172;

assign p_out5 = empty_193_fu_168;

assign p_out6 = empty_192_fu_164;

assign p_out7 = empty_191_fu_160;

assign p_out8 = empty_fu_156;

assign select_ln52_3_fu_547_p3 = ((icmp_ln50_fu_533_p2[0:0] == 1'b1) ? add_ln49_fu_527_p2 : ap_sig_allocacmp_wi_load);

assign select_ln52_fu_539_p3 = ((icmp_ln50_fu_533_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_wj_load);

assign sext_ln52_1_fu_614_p1 = $signed(tmp_1_fu_606_p3);

assign sext_ln52_fu_602_p1 = $signed(tmp_fu_594_p3);

assign sub_ln52_1_fu_618_p2 = ($signed(sext_ln52_fu_602_p1) - $signed(sext_ln52_1_fu_614_p1));

assign sub_ln52_cast_fu_412_p1 = $signed(sub_ln52);

assign tmp_1_fu_606_p3 = {{add_ln52_3_fu_589_p2}, {2'd0}};

assign tmp_57_cast_fu_624_p4 = {{sub_ln52_1_fu_618_p2[9:2]}};

assign tmp_fu_594_p3 = {{add_ln52_3_fu_589_p2}, {4'd0}};

assign tmp_s_fu_634_p3 = {{tmp_57_cast_fu_624_p4}, {select_ln52_reg_916}};

assign zext_ln52_5_fu_555_p1 = select_ln52_3_fu_547_p3;

assign zext_ln52_7_fu_641_p1 = tmp_s_fu_634_p3;

assign zext_ln52_fu_586_p1 = add_ln52_reg_925;

endmodule //HW_accel_Conv_func_4_12_4_10_Pipeline_loadWinFull_VITIS_LOOP_50_1
