// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module HW_accel_Conv_func_4_26_4_24_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ifmap_address0,
        ifmap_ce0,
        ifmap_q0,
        ofmap_0_address0,
        ofmap_0_ce0,
        ofmap_0_we0,
        ofmap_0_d0,
        ofmap_0_q0,
        ofmap_1_address0,
        ofmap_1_ce0,
        ofmap_1_we0,
        ofmap_1_d0,
        ofmap_1_q0
);

parameter    ap_ST_fsm_state1 = 42'd1;
parameter    ap_ST_fsm_state2 = 42'd2;
parameter    ap_ST_fsm_state3 = 42'd4;
parameter    ap_ST_fsm_state4 = 42'd8;
parameter    ap_ST_fsm_state5 = 42'd16;
parameter    ap_ST_fsm_state6 = 42'd32;
parameter    ap_ST_fsm_state7 = 42'd64;
parameter    ap_ST_fsm_state8 = 42'd128;
parameter    ap_ST_fsm_state9 = 42'd256;
parameter    ap_ST_fsm_state10 = 42'd512;
parameter    ap_ST_fsm_state11 = 42'd1024;
parameter    ap_ST_fsm_state12 = 42'd2048;
parameter    ap_ST_fsm_state13 = 42'd4096;
parameter    ap_ST_fsm_state14 = 42'd8192;
parameter    ap_ST_fsm_state15 = 42'd16384;
parameter    ap_ST_fsm_state16 = 42'd32768;
parameter    ap_ST_fsm_state17 = 42'd65536;
parameter    ap_ST_fsm_state18 = 42'd131072;
parameter    ap_ST_fsm_state19 = 42'd262144;
parameter    ap_ST_fsm_state20 = 42'd524288;
parameter    ap_ST_fsm_state21 = 42'd1048576;
parameter    ap_ST_fsm_state22 = 42'd2097152;
parameter    ap_ST_fsm_state23 = 42'd4194304;
parameter    ap_ST_fsm_state24 = 42'd8388608;
parameter    ap_ST_fsm_state25 = 42'd16777216;
parameter    ap_ST_fsm_state26 = 42'd33554432;
parameter    ap_ST_fsm_state27 = 42'd67108864;
parameter    ap_ST_fsm_state28 = 42'd134217728;
parameter    ap_ST_fsm_state29 = 42'd268435456;
parameter    ap_ST_fsm_state30 = 42'd536870912;
parameter    ap_ST_fsm_state31 = 42'd1073741824;
parameter    ap_ST_fsm_state32 = 42'd2147483648;
parameter    ap_ST_fsm_state33 = 42'd4294967296;
parameter    ap_ST_fsm_state34 = 42'd8589934592;
parameter    ap_ST_fsm_state35 = 42'd17179869184;
parameter    ap_ST_fsm_state36 = 42'd34359738368;
parameter    ap_ST_fsm_state37 = 42'd68719476736;
parameter    ap_ST_fsm_state38 = 42'd137438953472;
parameter    ap_ST_fsm_state39 = 42'd274877906944;
parameter    ap_ST_fsm_state40 = 42'd549755813888;
parameter    ap_ST_fsm_state41 = 42'd1099511627776;
parameter    ap_ST_fsm_state42 = 42'd2199023255552;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] ifmap_address0;
output   ifmap_ce0;
input  [31:0] ifmap_q0;
output  [10:0] ofmap_0_address0;
output   ofmap_0_ce0;
output   ofmap_0_we0;
output  [31:0] ofmap_0_d0;
input  [31:0] ofmap_0_q0;
output  [10:0] ofmap_1_address0;
output   ofmap_1_ce0;
output   ofmap_1_we0;
output  [31:0] ofmap_1_d0;
input  [31:0] ofmap_1_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[11:0] ifmap_address0;
reg ifmap_ce0;
reg[10:0] ofmap_0_address0;
reg ofmap_0_ce0;
reg ofmap_0_we0;
reg[31:0] ofmap_0_d0;
reg[10:0] ofmap_1_address0;
reg ofmap_1_ce0;
reg ofmap_1_we0;
reg[31:0] ofmap_1_d0;

(* fsm_encoding = "none" *) reg   [41:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] conv2_bias_address0;
reg    conv2_bias_ce0;
wire   [31:0] conv2_bias_q0;
wire   [2:0] add_ln133_fu_1238_p2;
reg   [2:0] add_ln133_reg_3125;
wire    ap_CS_fsm_state2;
wire   [7:0] or_ln_fu_1388_p4;
reg   [7:0] or_ln_reg_3238;
wire   [0:0] icmp_ln133_fu_1232_p2;
wire    ap_CS_fsm_state3;
wire  signed [9:0] sext_ln133_fu_1431_p1;
reg  signed [9:0] sext_ln133_reg_3248;
wire    ap_CS_fsm_state4;
reg   [31:0] conv2_bias_load_reg_3361;
wire   [11:0] add_ln137_1_fu_1549_p2;
reg   [11:0] add_ln137_1_reg_3369;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln139_fu_1555_p2;
reg   [0:0] icmp_ln139_reg_3374;
wire   [0:0] icmp_ln137_fu_1543_p2;
wire   [4:0] select_ln137_fu_1561_p3;
reg   [4:0] select_ln137_reg_3384;
wire   [2:0] select_ln137_1_fu_1723_p3;
reg   [2:0] select_ln137_1_reg_3390;
wire    ap_CS_fsm_state6;
wire   [7:0] mul_ln52_fu_1734_p2;
reg   [7:0] mul_ln52_reg_3395;
wire   [0:0] select_ln137_2_fu_1752_p3;
reg   [0:0] select_ln137_2_reg_3401;
wire   [0:0] select_ln137_3_fu_1771_p3;
reg   [0:0] select_ln137_3_reg_3406;
wire   [1:0] trunc_ln137_fu_1778_p1;
reg   [1:0] trunc_ln137_reg_3410;
wire   [4:0] select_ln139_fu_1809_p3;
reg   [4:0] select_ln139_reg_3415;
wire   [4:0] select_ln139_2_fu_1817_p3;
reg   [4:0] select_ln139_2_reg_3422;
wire   [10:0] sub_ln146_1_fu_1857_p2;
reg   [10:0] sub_ln146_1_reg_3429;
wire   [0:0] trunc_ln141_fu_1863_p1;
reg   [0:0] trunc_ln141_reg_3434;
wire   [0:0] icmp_ln46_fu_1867_p2;
reg   [0:0] icmp_ln46_reg_3439;
wire   [4:0] empty_189_fu_1954_p2;
reg   [4:0] empty_189_reg_3515;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state9;
reg   [10:0] ofmap_0_addr_reg_3676;
reg   [10:0] ofmap_1_addr_reg_3681;
wire   [31:0] prev_sum_fu_2110_p3;
reg   [31:0] prev_sum_reg_3686;
wire    ap_CS_fsm_state12;
wire   [31:0] grp_conv2D_4_s_fu_1159_ap_return;
reg   [31:0] sum_reg_3691;
wire    ap_CS_fsm_state38;
wire   [31:0] select_ln73_fu_2157_p3;
reg   [31:0] select_ln73_reg_3700;
wire    ap_CS_fsm_state41;
wire   [4:0] add_ln141_fu_2164_p2;
wire    ap_CS_fsm_state42;
wire   [9:0] select_ln139_3_fu_2175_p3;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_start;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_done;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_idle;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_ready;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out1;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out1_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out2;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out2_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out3;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out3_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out4;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out4_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out5;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out5_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out6;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out6_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out7;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out7_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out8;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out8_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out9;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out9_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out10;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out10_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out11;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out11_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out12;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out12_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out13;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out13_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out14;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out14_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out15;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out15_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out16;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out16_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out17;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out17_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out18;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out18_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out19;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out19_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out20;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out20_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out21;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out21_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out22;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out22_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out23;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out23_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out24;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out24_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out25;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out25_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out26;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out26_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out27;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out27_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out28;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out28_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out29;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out29_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out30;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out30_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out31;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out31_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out32;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out32_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out33;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out33_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out34;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out34_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out35;
wire    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out35_ap_vld;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_start;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_done;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_idle;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_ready;
wire   [11:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ifmap_address0;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ifmap_ce0;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2849107_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2849107_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2748100_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2748100_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_264793_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_264793_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_254686_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_254686_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_244579_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_244579_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_234472_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_234472_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_224365_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_224365_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_214258_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_214258_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window4151_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window4151_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2_2_promoted253351_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2_2_promoted253351_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2_0_promoted251344_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2_0_promoted251344_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2_1_promoted249337_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2_1_promoted249337_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_0_2_promoted247330_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_0_2_promoted247330_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_0_0_promoted245323_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_0_0_promoted245323_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_0_1_promoted243316_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_0_1_promoted243316_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_1_2_promoted241309_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_1_2_promoted241309_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_1_0_promoted239302_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_1_0_promoted239302_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_1_1_promoted237295_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_1_1_promoted237295_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_286_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_286_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_185_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_185_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_084_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_084_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_2_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_2_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_1_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_1_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_0_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_0_out_ap_vld;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_start;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_done;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_idle;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_ready;
wire   [11:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ifmap_address0;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ifmap_ce0;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out1;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out1_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out2;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out2_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out3;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out3_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out4;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out4_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out5;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out5_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out6;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out6_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out7;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out7_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out8;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out8_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_28662_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_28662_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_18551_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_18551_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_08440_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_08440_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_230_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_230_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_119_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_119_out_ap_vld;
wire   [31:0] grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_08_out;
wire    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_08_out_ap_vld;
reg   [11:0] indvar_flatten219_reg_687;
reg   [2:0] kch_reg_698;
reg   [9:0] indvar_flatten157_reg_710;
reg   [4:0] oh_reg_722;
reg   [4:0] ow_reg_733;
reg   [31:0] window_2849_reg_745;
reg   [31:0] window_2748_reg_755;
reg   [31:0] window_2647_reg_765;
reg   [31:0] window_2546_reg_775;
reg   [31:0] window_2445_reg_785;
reg   [31:0] window_2344_reg_795;
reg   [31:0] window_2243_reg_805;
reg   [31:0] window_2142_reg_815;
reg   [31:0] window41_reg_825;
reg   [31:0] window_2_2_promoted253353_reg_835;
reg   [31:0] window_2_0_promoted251346_reg_845;
reg   [31:0] window_2_1_promoted249339_reg_855;
reg   [31:0] window_0_2_promoted247332_reg_865;
reg   [31:0] window_0_0_promoted245325_reg_875;
reg   [31:0] window_0_1_promoted243318_reg_885;
reg   [31:0] window_1_2_promoted241311_reg_895;
reg   [31:0] window_1_0_promoted239304_reg_905;
reg   [31:0] window_1_1_promoted237297_reg_915;
reg   [31:0] mux_case_28665_reg_925;
reg   [31:0] mux_case_18554_reg_935;
reg   [31:0] mux_case_08443_reg_945;
reg   [31:0] mux_case_228_reg_955;
reg   [31:0] mux_case_117_reg_965;
reg   [31:0] mux_case_06_reg_975;
reg    grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_start_reg;
reg    grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_start_reg;
wire    ap_CS_fsm_state8;
reg    grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state13;
wire   [63:0] zext_ln133_fu_1399_p1;
wire   [63:0] zext_ln146_3_fu_2095_p1;
reg   [2:0] n_f_fu_104;
reg   [31:0] kernel_2_1_1_promoted_fu_108;
reg   [31:0] kernel_2_1_0_promoted_fu_112;
reg   [31:0] kernel_2_1_2_promoted_fu_116;
reg   [31:0] kernel_2_0_1_promoted_fu_120;
reg   [31:0] kernel_2_0_0_promoted_fu_124;
reg   [31:0] kernel_2_0_2_promoted_fu_128;
reg   [31:0] kernel_2_2_1_promoted_fu_132;
reg   [31:0] kernel_2_2_0_promoted_fu_136;
reg   [31:0] kernel_2_2_2_promoted_fu_140;
reg   [31:0] kernel_1_1_1_promoted_fu_144;
reg   [31:0] kernel_1_1_0_promoted_fu_148;
reg   [31:0] kernel_1_1_2_promoted_fu_152;
reg   [31:0] kernel_1_0_1_promoted_fu_156;
reg   [31:0] kernel_1_0_0_promoted_fu_160;
reg   [31:0] kernel_1_0_2_promoted_fu_164;
reg   [31:0] kernel_1_2_1_promoted_fu_168;
reg   [31:0] kernel_1_2_0_promoted_fu_172;
reg   [31:0] kernel_1_2_2_promoted_fu_176;
reg   [31:0] kernel_0_1_1_promoted_fu_180;
reg   [31:0] kernel_0_1_0_promoted_fu_184;
reg   [31:0] kernel_0_1_2_promoted_fu_188;
reg   [31:0] kernel_0_0_1_promoted_fu_192;
reg   [31:0] kernel_0_0_0_promoted_fu_196;
reg   [31:0] kernel_0_0_2_promoted_fu_200;
reg   [31:0] kernel_0_2_1_promoted_fu_204;
reg   [31:0] kernel_0_2_0_promoted_fu_208;
reg   [31:0] kernel_0_2_2_promoted_fu_212;
reg   [31:0] kernel_3_1_1_promoted_fu_216;
reg   [31:0] kernel_3_1_0_promoted_fu_220;
reg   [31:0] kernel_3_1_2_promoted_fu_224;
reg   [31:0] kernel_3_0_1_promoted_fu_228;
reg   [31:0] kernel_3_0_0_promoted_fu_232;
reg   [31:0] kernel_3_0_2_promoted_fu_236;
reg   [31:0] kernel_3_2_1_promoted_fu_240;
reg   [31:0] kernel_3_2_0_promoted_fu_244;
reg   [31:0] kernel_3_2_2_promoted_fu_248;
reg   [31:0] mux_case_01_fu_252;
reg   [31:0] mux_case_113_fu_256;
reg   [31:0] mux_case_224_fu_260;
reg   [31:0] mux_case_08435_fu_264;
reg   [31:0] mux_case_18546_fu_268;
reg   [31:0] mux_case_28657_fu_272;
reg   [31:0] window_1_1_promoted237291_fu_276;
reg   [31:0] window_1_0_promoted239298_fu_280;
reg   [31:0] window_1_2_promoted241305_fu_284;
reg   [31:0] window_0_1_promoted243312_fu_288;
reg   [31:0] window_0_0_promoted245319_fu_292;
reg   [31:0] window_0_2_promoted247326_fu_296;
reg   [31:0] window_2_1_promoted249333_fu_300;
reg   [31:0] window_2_0_promoted251340_fu_304;
reg   [31:0] window_2_2_promoted253347_fu_308;
reg   [31:0] window4153_fu_312;
reg   [31:0] window_214260_fu_316;
reg   [31:0] window_224367_fu_320;
reg   [31:0] window_234474_fu_324;
reg   [31:0] window_244581_fu_328;
reg   [31:0] window_254688_fu_332;
reg   [31:0] window_264795_fu_336;
reg   [31:0] window_2748102_fu_340;
reg   [31:0] window_2849109_fu_344;
wire    ap_CS_fsm_state39;
wire    ap_CS_fsm_state40;
wire   [7:0] tmp_s_fu_1403_p3;
wire   [5:0] tmp_25_fu_1414_p3;
wire   [8:0] zext_ln26_fu_1410_p1;
wire   [8:0] zext_ln146_fu_1421_p1;
wire   [8:0] sub_ln146_fu_1425_p2;
wire   [2:0] add_ln137_fu_1717_p2;
wire   [2:0] mul_ln52_fu_1734_p0;
wire   [5:0] mul_ln52_fu_1734_p1;
wire   [0:0] cmp15_mid1_fu_1740_p2;
wire   [0:0] cmp1597_fu_1746_p2;
wire   [0:0] cmp28_mid1_fu_1759_p2;
wire   [0:0] cmp2896_fu_1765_p2;
wire   [0:0] icmp_ln141_fu_1787_p2;
wire   [0:0] xor_ln137_fu_1782_p2;
wire   [0:0] and_ln137_fu_1793_p2;
wire   [0:0] or_ln139_fu_1804_p2;
wire   [4:0] add_ln139_fu_1799_p2;
wire   [9:0] zext_ln146_1_fu_1824_p1;
wire   [9:0] add_ln146_fu_1828_p2;
wire   [6:0] trunc_ln146_fu_1833_p1;
wire   [8:0] trunc_ln146_1_fu_1845_p1;
wire   [10:0] p_shl5_fu_1837_p3;
wire   [10:0] p_shl6_fu_1849_p3;
wire   [3:0] lshr_ln_fu_2077_p4;
wire   [10:0] zext_ln146_2_fu_2086_p1;
wire   [10:0] add_ln146_1_fu_2090_p2;
wire   [31:0] tmp_fu_2101_p4;
wire   [31:0] bitcast_ln73_fu_2116_p1;
wire   [7:0] tmp_22_fu_2119_p4;
wire   [22:0] trunc_ln73_fu_2129_p1;
wire   [0:0] icmp_ln73_17_fu_2139_p2;
wire   [0:0] icmp_ln73_fu_2133_p2;
wire   [0:0] or_ln73_fu_2145_p2;
wire   [0:0] grp_fu_1219_p2;
wire   [0:0] and_ln73_fu_2151_p2;
wire   [9:0] add_ln139_2_fu_2169_p2;
reg   [41:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire   [7:0] mul_ln52_fu_1734_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 42'd1;
#0 grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_start_reg = 1'b0;
#0 grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_start_reg = 1'b0;
#0 grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_start_reg = 1'b0;
end

HW_accel_Conv_func_4_26_4_24_s_conv2_bias_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 4 ),
    .AddressWidth( 2 ))
conv2_bias_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv2_bias_address0),
    .ce0(conv2_bias_ce0),
    .q0(conv2_bias_q0)
);

HW_accel_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_start),
    .ap_done(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_done),
    .ap_idle(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_idle),
    .ap_ready(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_ready),
    .kernel_3_2_2_promoted(kernel_3_2_2_promoted_fu_248),
    .kernel_3_2_0_promoted(kernel_3_2_0_promoted_fu_244),
    .kernel_3_2_1_promoted(kernel_3_2_1_promoted_fu_240),
    .kernel_3_0_2_promoted(kernel_3_0_2_promoted_fu_236),
    .kernel_3_0_0_promoted(kernel_3_0_0_promoted_fu_232),
    .kernel_3_0_1_promoted(kernel_3_0_1_promoted_fu_228),
    .kernel_3_1_2_promoted(kernel_3_1_2_promoted_fu_224),
    .kernel_3_1_0_promoted(kernel_3_1_0_promoted_fu_220),
    .kernel_3_1_1_promoted(kernel_3_1_1_promoted_fu_216),
    .kernel_0_2_2_promoted(kernel_0_2_2_promoted_fu_212),
    .kernel_0_2_0_promoted(kernel_0_2_0_promoted_fu_208),
    .kernel_0_2_1_promoted(kernel_0_2_1_promoted_fu_204),
    .kernel_0_0_2_promoted(kernel_0_0_2_promoted_fu_200),
    .kernel_0_0_0_promoted(kernel_0_0_0_promoted_fu_196),
    .kernel_0_0_1_promoted(kernel_0_0_1_promoted_fu_192),
    .kernel_0_1_2_promoted(kernel_0_1_2_promoted_fu_188),
    .kernel_0_1_0_promoted(kernel_0_1_0_promoted_fu_184),
    .kernel_0_1_1_promoted(kernel_0_1_1_promoted_fu_180),
    .kernel_1_2_2_promoted(kernel_1_2_2_promoted_fu_176),
    .kernel_1_2_0_promoted(kernel_1_2_0_promoted_fu_172),
    .kernel_1_2_1_promoted(kernel_1_2_1_promoted_fu_168),
    .kernel_1_0_2_promoted(kernel_1_0_2_promoted_fu_164),
    .kernel_1_0_0_promoted(kernel_1_0_0_promoted_fu_160),
    .kernel_1_0_1_promoted(kernel_1_0_1_promoted_fu_156),
    .kernel_1_1_2_promoted(kernel_1_1_2_promoted_fu_152),
    .kernel_1_1_0_promoted(kernel_1_1_0_promoted_fu_148),
    .kernel_1_1_1_promoted(kernel_1_1_1_promoted_fu_144),
    .kernel_2_2_2_promoted(kernel_2_2_2_promoted_fu_140),
    .kernel_2_2_0_promoted(kernel_2_2_0_promoted_fu_136),
    .kernel_2_2_1_promoted(kernel_2_2_1_promoted_fu_132),
    .kernel_2_0_2_promoted(kernel_2_0_2_promoted_fu_128),
    .kernel_2_0_0_promoted(kernel_2_0_0_promoted_fu_124),
    .kernel_2_0_1_promoted(kernel_2_0_1_promoted_fu_120),
    .kernel_2_1_2_promoted(kernel_2_1_2_promoted_fu_116),
    .kernel_2_1_0_promoted(kernel_2_1_0_promoted_fu_112),
    .kernel_2_1_1_promoted(kernel_2_1_1_promoted_fu_108),
    .or_ln26(or_ln_reg_3238),
    .p_out(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out),
    .p_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out_ap_vld),
    .p_out1(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out1),
    .p_out1_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out1_ap_vld),
    .p_out2(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out2),
    .p_out2_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out2_ap_vld),
    .p_out3(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out3),
    .p_out3_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out3_ap_vld),
    .p_out4(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out4),
    .p_out4_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out4_ap_vld),
    .p_out5(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out5),
    .p_out5_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out5_ap_vld),
    .p_out6(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out6),
    .p_out6_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out6_ap_vld),
    .p_out7(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out7),
    .p_out7_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out7_ap_vld),
    .p_out8(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out8),
    .p_out8_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out8_ap_vld),
    .p_out9(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out9),
    .p_out9_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out9_ap_vld),
    .p_out10(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out10),
    .p_out10_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out10_ap_vld),
    .p_out11(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out11),
    .p_out11_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out11_ap_vld),
    .p_out12(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out12),
    .p_out12_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out12_ap_vld),
    .p_out13(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out13),
    .p_out13_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out13_ap_vld),
    .p_out14(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out14),
    .p_out14_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out14_ap_vld),
    .p_out15(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out15),
    .p_out15_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out15_ap_vld),
    .p_out16(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out16),
    .p_out16_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out16_ap_vld),
    .p_out17(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out17),
    .p_out17_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out17_ap_vld),
    .p_out18(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out18),
    .p_out18_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out18_ap_vld),
    .p_out19(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out19),
    .p_out19_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out19_ap_vld),
    .p_out20(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out20),
    .p_out20_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out20_ap_vld),
    .p_out21(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out21),
    .p_out21_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out21_ap_vld),
    .p_out22(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out22),
    .p_out22_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out22_ap_vld),
    .p_out23(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out23),
    .p_out23_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out23_ap_vld),
    .p_out24(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out24),
    .p_out24_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out24_ap_vld),
    .p_out25(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out25),
    .p_out25_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out25_ap_vld),
    .p_out26(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out26),
    .p_out26_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out26_ap_vld),
    .p_out27(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out27),
    .p_out27_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out27_ap_vld),
    .p_out28(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out28),
    .p_out28_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out28_ap_vld),
    .p_out29(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out29),
    .p_out29_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out29_ap_vld),
    .p_out30(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out30),
    .p_out30_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out30_ap_vld),
    .p_out31(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out31),
    .p_out31_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out31_ap_vld),
    .p_out32(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out32),
    .p_out32_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out32_ap_vld),
    .p_out33(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out33),
    .p_out33_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out33_ap_vld),
    .p_out34(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out34),
    .p_out34_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out34_ap_vld),
    .p_out35(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out35),
    .p_out35_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out35_ap_vld)
);

HW_accel_Conv_func_4_26_4_24_Pipeline_loadWinShift grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_start),
    .ap_done(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_done),
    .ap_idle(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_idle),
    .ap_ready(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_ready),
    .window_2849112(window_2849109_fu_344),
    .window_2748105(window_2748102_fu_340),
    .window_264798(window_264795_fu_336),
    .window_254691(window_254688_fu_332),
    .window_244584(window_244581_fu_328),
    .window_234477(window_234474_fu_324),
    .window_224370(window_224367_fu_320),
    .window_214263(window_214260_fu_316),
    .window4156(window4153_fu_312),
    .window_2_2_promoted253(window_2_2_promoted253347_fu_308),
    .window_2_0_promoted251(window_2_0_promoted251340_fu_304),
    .window_2_1_promoted249(window_2_1_promoted249333_fu_300),
    .window_0_2_promoted247(window_0_2_promoted247326_fu_296),
    .window_0_0_promoted245(window_0_0_promoted245319_fu_292),
    .window_0_1_promoted243(window_0_1_promoted243312_fu_288),
    .window_1_2_promoted241(window_1_2_promoted241305_fu_284),
    .window_1_0_promoted239(window_1_0_promoted239298_fu_280),
    .window_1_1_promoted237(window_1_1_promoted237291_fu_276),
    .mux_case_28664(mux_case_28657_fu_272),
    .mux_case_18553(mux_case_18546_fu_268),
    .mux_case_08442(mux_case_08435_fu_264),
    .mux_case_227(mux_case_224_fu_260),
    .mux_case_116(mux_case_113_fu_256),
    .mux_case_05(mux_case_01_fu_252),
    .select_ln139_3(select_ln139_2_reg_3422),
    .mul_ln52(mul_ln52_reg_3395),
    .zext_ln58(empty_189_reg_3515),
    .ifmap_address0(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ifmap_address0),
    .ifmap_ce0(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ifmap_ce0),
    .ifmap_q0(ifmap_q0),
    .window_2849107_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2849107_out),
    .window_2849107_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2849107_out_ap_vld),
    .window_2748100_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2748100_out),
    .window_2748100_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2748100_out_ap_vld),
    .window_264793_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_264793_out),
    .window_264793_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_264793_out_ap_vld),
    .window_254686_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_254686_out),
    .window_254686_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_254686_out_ap_vld),
    .window_244579_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_244579_out),
    .window_244579_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_244579_out_ap_vld),
    .window_234472_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_234472_out),
    .window_234472_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_234472_out_ap_vld),
    .window_224365_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_224365_out),
    .window_224365_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_224365_out_ap_vld),
    .window_214258_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_214258_out),
    .window_214258_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_214258_out_ap_vld),
    .window4151_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window4151_out),
    .window4151_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window4151_out_ap_vld),
    .window_2_2_promoted253351_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2_2_promoted253351_out),
    .window_2_2_promoted253351_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2_2_promoted253351_out_ap_vld),
    .window_2_0_promoted251344_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2_0_promoted251344_out),
    .window_2_0_promoted251344_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2_0_promoted251344_out_ap_vld),
    .window_2_1_promoted249337_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2_1_promoted249337_out),
    .window_2_1_promoted249337_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2_1_promoted249337_out_ap_vld),
    .window_0_2_promoted247330_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_0_2_promoted247330_out),
    .window_0_2_promoted247330_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_0_2_promoted247330_out_ap_vld),
    .window_0_0_promoted245323_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_0_0_promoted245323_out),
    .window_0_0_promoted245323_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_0_0_promoted245323_out_ap_vld),
    .window_0_1_promoted243316_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_0_1_promoted243316_out),
    .window_0_1_promoted243316_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_0_1_promoted243316_out_ap_vld),
    .window_1_2_promoted241309_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_1_2_promoted241309_out),
    .window_1_2_promoted241309_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_1_2_promoted241309_out_ap_vld),
    .window_1_0_promoted239302_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_1_0_promoted239302_out),
    .window_1_0_promoted239302_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_1_0_promoted239302_out_ap_vld),
    .window_1_1_promoted237295_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_1_1_promoted237295_out),
    .window_1_1_promoted237295_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_1_1_promoted237295_out_ap_vld),
    .mux_case_286_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_286_out),
    .mux_case_286_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_286_out_ap_vld),
    .mux_case_185_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_185_out),
    .mux_case_185_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_185_out_ap_vld),
    .mux_case_084_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_084_out),
    .mux_case_084_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_084_out_ap_vld),
    .mux_case_2_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_2_out),
    .mux_case_2_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_2_out_ap_vld),
    .mux_case_1_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_1_out),
    .mux_case_1_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_1_out_ap_vld),
    .mux_case_0_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_0_out),
    .mux_case_0_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_0_out_ap_vld)
);

HW_accel_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1 grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_start),
    .ap_done(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_done),
    .ap_idle(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_idle),
    .ap_ready(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_ready),
    .window_2_2_promoted253(window_2_2_promoted253347_fu_308),
    .window_2_0_promoted251(window_2_0_promoted251340_fu_304),
    .window_2_1_promoted249(window_2_1_promoted249333_fu_300),
    .window_0_2_promoted247(window_0_2_promoted247326_fu_296),
    .window_0_0_promoted245(window_0_0_promoted245319_fu_292),
    .window_0_1_promoted243(window_0_1_promoted243312_fu_288),
    .window_1_2_promoted241(window_1_2_promoted241305_fu_284),
    .window_1_0_promoted239(window_1_0_promoted239298_fu_280),
    .window_1_1_promoted237(window_1_1_promoted237291_fu_276),
    .mux_case_28664(mux_case_28657_fu_272),
    .mux_case_18553(mux_case_18546_fu_268),
    .mux_case_08442(mux_case_08435_fu_264),
    .mux_case_227(mux_case_224_fu_260),
    .mux_case_116(mux_case_113_fu_256),
    .mux_case_05(mux_case_01_fu_252),
    .select_ln139_3(select_ln139_2_reg_3422),
    .mul_ln52(mul_ln52_reg_3395),
    .ifmap_address0(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ifmap_address0),
    .ifmap_ce0(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ifmap_ce0),
    .ifmap_q0(ifmap_q0),
    .p_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out),
    .p_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out_ap_vld),
    .p_out1(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out1),
    .p_out1_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out1_ap_vld),
    .p_out2(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out2),
    .p_out2_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out2_ap_vld),
    .p_out3(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out3),
    .p_out3_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out3_ap_vld),
    .p_out4(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out4),
    .p_out4_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out4_ap_vld),
    .p_out5(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out5),
    .p_out5_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out5_ap_vld),
    .p_out6(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out6),
    .p_out6_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out6_ap_vld),
    .p_out7(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out7),
    .p_out7_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out7_ap_vld),
    .p_out8(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out8),
    .p_out8_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out8_ap_vld),
    .mux_case_28662_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_28662_out),
    .mux_case_28662_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_28662_out_ap_vld),
    .mux_case_18551_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_18551_out),
    .mux_case_18551_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_18551_out_ap_vld),
    .mux_case_08440_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_08440_out),
    .mux_case_08440_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_08440_out_ap_vld),
    .mux_case_230_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_230_out),
    .mux_case_230_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_230_out_ap_vld),
    .mux_case_119_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_119_out),
    .mux_case_119_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_119_out_ap_vld),
    .mux_case_08_out(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_08_out),
    .mux_case_08_out_ap_vld(grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_08_out_ap_vld)
);

HW_accel_conv2D_4_s grp_conv2D_4_s_fu_1159(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .kch(trunc_ln137_reg_3410),
    .p_read(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out13),
    .p_read1(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out14),
    .p_read2(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out12),
    .p_read3(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out16),
    .p_read4(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out17),
    .p_read5(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out15),
    .p_read6(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out10),
    .p_read7(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out11),
    .p_read8(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out9),
    .p_read9(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out22),
    .p_read10(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out23),
    .p_read11(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out21),
    .p_read12(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out25),
    .p_read13(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out26),
    .p_read14(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out24),
    .p_read15(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out19),
    .p_read16(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out20),
    .p_read17(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out18),
    .p_read18(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out31),
    .p_read19(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out32),
    .p_read20(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out30),
    .p_read21(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out34),
    .p_read22(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out35),
    .p_read23(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out33),
    .p_read24(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out28),
    .p_read25(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out29),
    .p_read26(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out27),
    .p_read27(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out4),
    .p_read28(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out5),
    .p_read29(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out3),
    .p_read30(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out7),
    .p_read31(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out8),
    .p_read32(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out6),
    .p_read33(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out1),
    .p_read34(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out2),
    .p_read35(grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out),
    .p_read36(window41_reg_825),
    .p_read37(window_2142_reg_815),
    .p_read38(window_2243_reg_805),
    .p_read39(window_2344_reg_795),
    .p_read40(window_2445_reg_785),
    .p_read41(window_2546_reg_775),
    .p_read42(window_2647_reg_765),
    .p_read43(window_2748_reg_755),
    .p_read44(window_2849_reg_745),
    .prev_sum(prev_sum_reg_3686),
    .ap_return(grp_conv2D_4_s_fu_1159_ap_return)
);

HW_accel_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U402(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sum_reg_3691),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_1219_p2)
);

HW_accel_mul_3ns_6ns_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 8 ))
mul_3ns_6ns_8_1_1_U403(
    .din0(mul_ln52_fu_1734_p0),
    .din1(mul_ln52_fu_1734_p1),
    .dout(mul_ln52_fu_1734_p2)
);

HW_accel_mux_21_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 32 ))
mux_21_32_1_1_U404(
    .din0(ofmap_0_q0),
    .din1(ofmap_1_q0),
    .din2(trunc_ln141_reg_3434),
    .dout(tmp_fu_2101_p4)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln133_fu_1232_p2 == 1'd0))) begin
            grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_start_reg <= 1'b1;
        end else if ((grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_ready == 1'b1)) begin
            grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_start_reg <= 1'b1;
        end else if ((grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_ready == 1'b1)) begin
            grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_start_reg <= 1'b1;
        end else if ((grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_ready == 1'b1)) begin
            grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        indvar_flatten157_reg_710 <= select_ln139_3_fu_2175_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        indvar_flatten157_reg_710 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        indvar_flatten219_reg_687 <= add_ln137_1_reg_3369;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        indvar_flatten219_reg_687 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        kch_reg_698 <= select_ln137_1_reg_3390;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        kch_reg_698 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            mux_case_06_reg_975 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_08_out;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            mux_case_06_reg_975 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_0_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            mux_case_08443_reg_945 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_08440_out;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            mux_case_08443_reg_945 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_084_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            mux_case_117_reg_965 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_119_out;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            mux_case_117_reg_965 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_1_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            mux_case_18554_reg_935 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_18551_out;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            mux_case_18554_reg_935 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_185_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            mux_case_228_reg_955 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_230_out;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            mux_case_228_reg_955 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_2_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            mux_case_28665_reg_925 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_mux_case_28662_out;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            mux_case_28665_reg_925 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_mux_case_286_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        n_f_fu_104 <= 3'd0;
    end else if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln137_fu_1543_p2 == 1'd1))) begin
        n_f_fu_104 <= add_ln133_reg_3125;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        oh_reg_722 <= select_ln139_2_reg_3422;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        oh_reg_722 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        ow_reg_733 <= add_ln141_fu_2164_p2;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        ow_reg_733 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window41_reg_825 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out4;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window41_reg_825 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window4151_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_0_0_promoted245325_reg_875 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out4;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_0_0_promoted245325_reg_875 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_0_0_promoted245323_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_0_1_promoted243318_reg_885 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out5;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_0_1_promoted243318_reg_885 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_0_1_promoted243316_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_0_2_promoted247332_reg_865 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out3;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_0_2_promoted247332_reg_865 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_0_2_promoted247330_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_1_0_promoted239304_reg_905 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out7;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_1_0_promoted239304_reg_905 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_1_0_promoted239302_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_1_1_promoted237297_reg_915 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out8;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_1_1_promoted237297_reg_915 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_1_1_promoted237295_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_1_2_promoted241311_reg_895 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out6;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_1_2_promoted241311_reg_895 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_1_2_promoted241309_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_2142_reg_815 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out5;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_2142_reg_815 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_214258_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_2243_reg_805 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out3;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_2243_reg_805 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_224365_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_2344_reg_795 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out7;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_2344_reg_795 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_234472_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_2445_reg_785 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out8;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_2445_reg_785 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_244579_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_2546_reg_775 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out6;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_2546_reg_775 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_254686_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_2647_reg_765 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out1;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_2647_reg_765 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_264793_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_2748_reg_755 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out2;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_2748_reg_755 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2748100_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_2849_reg_745 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_2849_reg_745 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2849107_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_2_0_promoted251346_reg_845 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out1;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_2_0_promoted251346_reg_845 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2_0_promoted251344_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_2_1_promoted249339_reg_855 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out2;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_2_1_promoted249339_reg_855 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2_1_promoted249337_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        if ((icmp_ln46_reg_3439 == 1'd1)) begin
            window_2_2_promoted253353_reg_835 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_p_out;
        end else if ((icmp_ln46_reg_3439 == 1'd0)) begin
            window_2_2_promoted253353_reg_835 <= grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_window_2_2_promoted253351_out;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln133_reg_3125 <= add_ln133_fu_1238_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln137_1_reg_3369 <= add_ln137_1_fu_1549_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        conv2_bias_load_reg_3361 <= conv2_bias_q0;
        sext_ln133_reg_3248[9 : 3] <= sext_ln133_fu_1431_p1[9 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        empty_189_reg_3515 <= empty_189_fu_1954_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln137_fu_1543_p2 == 1'd0))) begin
        icmp_ln139_reg_3374 <= icmp_ln139_fu_1555_p2;
        select_ln137_reg_3384 <= select_ln137_fu_1561_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        icmp_ln46_reg_3439 <= icmp_ln46_fu_1867_p2;
        mul_ln52_reg_3395 <= mul_ln52_fu_1734_p2;
        select_ln137_1_reg_3390 <= select_ln137_1_fu_1723_p3;
        select_ln137_2_reg_3401 <= select_ln137_2_fu_1752_p3;
        select_ln137_3_reg_3406 <= select_ln137_3_fu_1771_p3;
        select_ln139_2_reg_3422 <= select_ln139_2_fu_1817_p3;
        select_ln139_reg_3415 <= select_ln139_fu_1809_p3;
        sub_ln146_1_reg_3429[10 : 2] <= sub_ln146_1_fu_1857_p2[10 : 2];
        trunc_ln137_reg_3410 <= trunc_ln137_fu_1778_p1;
        trunc_ln141_reg_3434 <= trunc_ln141_fu_1863_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln137_fu_1543_p2 == 1'd1))) begin
        kernel_0_0_0_promoted_fu_196 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out13;
        kernel_0_0_1_promoted_fu_192 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out14;
        kernel_0_0_2_promoted_fu_200 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out12;
        kernel_0_1_0_promoted_fu_184 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out16;
        kernel_0_1_1_promoted_fu_180 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out17;
        kernel_0_1_2_promoted_fu_188 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out15;
        kernel_0_2_0_promoted_fu_208 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out10;
        kernel_0_2_1_promoted_fu_204 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out11;
        kernel_0_2_2_promoted_fu_212 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out9;
        kernel_1_0_0_promoted_fu_160 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out22;
        kernel_1_0_1_promoted_fu_156 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out23;
        kernel_1_0_2_promoted_fu_164 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out21;
        kernel_1_1_0_promoted_fu_148 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out25;
        kernel_1_1_1_promoted_fu_144 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out26;
        kernel_1_1_2_promoted_fu_152 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out24;
        kernel_1_2_0_promoted_fu_172 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out19;
        kernel_1_2_1_promoted_fu_168 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out20;
        kernel_1_2_2_promoted_fu_176 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out18;
        kernel_2_0_0_promoted_fu_124 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out31;
        kernel_2_0_1_promoted_fu_120 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out32;
        kernel_2_0_2_promoted_fu_128 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out30;
        kernel_2_1_0_promoted_fu_112 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out34;
        kernel_2_1_1_promoted_fu_108 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out35;
        kernel_2_1_2_promoted_fu_116 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out33;
        kernel_2_2_0_promoted_fu_136 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out28;
        kernel_2_2_1_promoted_fu_132 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out29;
        kernel_2_2_2_promoted_fu_140 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out27;
        kernel_3_0_0_promoted_fu_232 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out4;
        kernel_3_0_1_promoted_fu_228 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out5;
        kernel_3_0_2_promoted_fu_236 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out3;
        kernel_3_1_0_promoted_fu_220 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out7;
        kernel_3_1_1_promoted_fu_216 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out8;
        kernel_3_1_2_promoted_fu_224 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out6;
        kernel_3_2_0_promoted_fu_244 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out1;
        kernel_3_2_1_promoted_fu_240 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out2;
        kernel_3_2_2_promoted_fu_248 <= grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_p_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        mux_case_01_fu_252 <= mux_case_06_reg_975;
        mux_case_08435_fu_264 <= mux_case_08443_reg_945;
        mux_case_113_fu_256 <= mux_case_117_reg_965;
        mux_case_18546_fu_268 <= mux_case_18554_reg_935;
        mux_case_224_fu_260 <= mux_case_228_reg_955;
        mux_case_28657_fu_272 <= mux_case_28665_reg_925;
        window4153_fu_312 <= window41_reg_825;
        window_0_0_promoted245319_fu_292 <= window_0_0_promoted245325_reg_875;
        window_0_1_promoted243312_fu_288 <= window_0_1_promoted243318_reg_885;
        window_0_2_promoted247326_fu_296 <= window_0_2_promoted247332_reg_865;
        window_1_0_promoted239298_fu_280 <= window_1_0_promoted239304_reg_905;
        window_1_1_promoted237291_fu_276 <= window_1_1_promoted237297_reg_915;
        window_1_2_promoted241305_fu_284 <= window_1_2_promoted241311_reg_895;
        window_214260_fu_316 <= window_2142_reg_815;
        window_224367_fu_320 <= window_2243_reg_805;
        window_234474_fu_324 <= window_2344_reg_795;
        window_244581_fu_328 <= window_2445_reg_785;
        window_254688_fu_332 <= window_2546_reg_775;
        window_264795_fu_336 <= window_2647_reg_765;
        window_2748102_fu_340 <= window_2748_reg_755;
        window_2849109_fu_344 <= window_2849_reg_745;
        window_2_0_promoted251340_fu_304 <= window_2_0_promoted251346_reg_845;
        window_2_1_promoted249333_fu_300 <= window_2_1_promoted249339_reg_855;
        window_2_2_promoted253347_fu_308 <= window_2_2_promoted253353_reg_835;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ofmap_0_addr_reg_3676 <= zext_ln146_3_fu_2095_p1;
        ofmap_1_addr_reg_3681 <= zext_ln146_3_fu_2095_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln133_fu_1232_p2 == 1'd0))) begin
        or_ln_reg_3238[7 : 2] <= or_ln_fu_1388_p4[7 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        prev_sum_reg_3686 <= prev_sum_fu_2110_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state41)) begin
        select_ln73_reg_3700 <= select_ln73_fu_2157_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        sum_reg_3691 <= grp_conv2D_4_s_fu_1159_ap_return;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if ((grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (icmp_ln133_fu_1232_p2 == 1'd1)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln133_fu_1232_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        conv2_bias_ce0 = 1'b1;
    end else begin
        conv2_bias_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ifmap_address0 = grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ifmap_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        ifmap_address0 = grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ifmap_address0;
    end else begin
        ifmap_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ifmap_ce0 = grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ifmap_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        ifmap_ce0 = grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ifmap_ce0;
    end else begin
        ifmap_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state39))) begin
        ofmap_0_address0 = ofmap_0_addr_reg_3676;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        ofmap_0_address0 = zext_ln146_3_fu_2095_p1;
    end else begin
        ofmap_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state39))) begin
        ofmap_0_ce0 = 1'b1;
    end else begin
        ofmap_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        ofmap_0_d0 = select_ln73_reg_3700;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        ofmap_0_d0 = sum_reg_3691;
    end else begin
        ofmap_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state42) & (trunc_ln141_reg_3434 == 1'd0) & (select_ln137_3_reg_3406 == 1'd1)) | ((1'b1 == ap_CS_fsm_state39) & (trunc_ln141_reg_3434 == 1'd0)))) begin
        ofmap_0_we0 = 1'b1;
    end else begin
        ofmap_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state39))) begin
        ofmap_1_address0 = ofmap_1_addr_reg_3681;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        ofmap_1_address0 = zext_ln146_3_fu_2095_p1;
    end else begin
        ofmap_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state39))) begin
        ofmap_1_ce0 = 1'b1;
    end else begin
        ofmap_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        ofmap_1_d0 = select_ln73_reg_3700;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        ofmap_1_d0 = sum_reg_3691;
    end else begin
        ofmap_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state42) & (trunc_ln141_reg_3434 == 1'd1) & (select_ln137_3_reg_3406 == 1'd1)) | ((1'b1 == ap_CS_fsm_state39) & (trunc_ln141_reg_3434 == 1'd1)))) begin
        ofmap_1_we0 = 1'b1;
    end else begin
        ofmap_1_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln133_fu_1232_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (icmp_ln137_fu_1543_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln46_fu_1867_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            if (((1'b1 == ap_CS_fsm_state38) & (select_ln137_3_reg_3406 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln133_fu_1238_p2 = (n_f_fu_104 + 3'd1);

assign add_ln137_1_fu_1549_p2 = (indvar_flatten219_reg_687 + 12'd1);

assign add_ln137_fu_1717_p2 = (kch_reg_698 + 3'd1);

assign add_ln139_2_fu_2169_p2 = (indvar_flatten157_reg_710 + 10'd1);

assign add_ln139_fu_1799_p2 = (select_ln137_reg_3384 + 5'd1);

assign add_ln141_fu_2164_p2 = (select_ln139_reg_3415 + 5'd1);

assign add_ln146_1_fu_2090_p2 = (sub_ln146_1_reg_3429 + zext_ln146_2_fu_2086_p1);

assign add_ln146_fu_1828_p2 = ($signed(sext_ln133_reg_3248) + $signed(zext_ln146_1_fu_1824_p1));

assign and_ln137_fu_1793_p2 = (xor_ln137_fu_1782_p2 & icmp_ln141_fu_1787_p2);

assign and_ln73_fu_2151_p2 = (or_ln73_fu_2145_p2 & grp_fu_1219_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bitcast_ln73_fu_2116_p1 = sum_reg_3691;

assign cmp1597_fu_1746_p2 = ((kch_reg_698 == 3'd0) ? 1'b1 : 1'b0);

assign cmp15_mid1_fu_1740_p2 = ((add_ln137_fu_1717_p2 == 3'd0) ? 1'b1 : 1'b0);

assign cmp2896_fu_1765_p2 = ((kch_reg_698 == 3'd3) ? 1'b1 : 1'b0);

assign cmp28_mid1_fu_1759_p2 = ((add_ln137_fu_1717_p2 == 3'd3) ? 1'b1 : 1'b0);

assign conv2_bias_address0 = zext_ln133_fu_1399_p1;

assign empty_189_fu_1954_p2 = (select_ln139_reg_3415 + 5'd2);

assign grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_start = grp_Conv_func_4_26_4_24_Pipeline_Fil_load_ch_Fil_load_r_Fil_load_c_fu_985_ap_start_reg;

assign grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_start = grp_Conv_func_4_26_4_24_Pipeline_loadWinFull_VITIS_LOOP_50_1_fu_1121_ap_start_reg;

assign grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_start = grp_Conv_func_4_26_4_24_Pipeline_loadWinShift_fu_1064_ap_start_reg;

assign icmp_ln133_fu_1232_p2 = ((n_f_fu_104 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln137_fu_1543_p2 = ((indvar_flatten219_reg_687 == 12'd2304) ? 1'b1 : 1'b0);

assign icmp_ln139_fu_1555_p2 = ((indvar_flatten157_reg_710 == 10'd576) ? 1'b1 : 1'b0);

assign icmp_ln141_fu_1787_p2 = ((ow_reg_733 == 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_1867_p2 = ((select_ln139_fu_1809_p3 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln73_17_fu_2139_p2 = ((trunc_ln73_fu_2129_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln73_fu_2133_p2 = ((tmp_22_fu_2119_p4 != 8'd255) ? 1'b1 : 1'b0);

assign lshr_ln_fu_2077_p4 = {{select_ln139_reg_3415[4:1]}};

assign mul_ln52_fu_1734_p0 = mul_ln52_fu_1734_p00;

assign mul_ln52_fu_1734_p00 = select_ln137_1_fu_1723_p3;

assign mul_ln52_fu_1734_p1 = 8'd26;

assign or_ln139_fu_1804_p2 = (icmp_ln139_reg_3374 | and_ln137_fu_1793_p2);

assign or_ln73_fu_2145_p2 = (icmp_ln73_fu_2133_p2 | icmp_ln73_17_fu_2139_p2);

assign or_ln_fu_1388_p4 = {{{n_f_fu_104}, {n_f_fu_104}}, {2'd0}};

assign p_shl5_fu_1837_p3 = {{trunc_ln146_fu_1833_p1}, {4'd0}};

assign p_shl6_fu_1849_p3 = {{trunc_ln146_1_fu_1845_p1}, {2'd0}};

assign prev_sum_fu_2110_p3 = ((select_ln137_2_reg_3401[0:0] == 1'b1) ? conv2_bias_load_reg_3361 : tmp_fu_2101_p4);

assign select_ln137_1_fu_1723_p3 = ((icmp_ln139_reg_3374[0:0] == 1'b1) ? add_ln137_fu_1717_p2 : kch_reg_698);

assign select_ln137_2_fu_1752_p3 = ((icmp_ln139_reg_3374[0:0] == 1'b1) ? cmp15_mid1_fu_1740_p2 : cmp1597_fu_1746_p2);

assign select_ln137_3_fu_1771_p3 = ((icmp_ln139_reg_3374[0:0] == 1'b1) ? cmp28_mid1_fu_1759_p2 : cmp2896_fu_1765_p2);

assign select_ln137_fu_1561_p3 = ((icmp_ln139_fu_1555_p2[0:0] == 1'b1) ? 5'd0 : oh_reg_722);

assign select_ln139_2_fu_1817_p3 = ((and_ln137_fu_1793_p2[0:0] == 1'b1) ? add_ln139_fu_1799_p2 : select_ln137_reg_3384);

assign select_ln139_3_fu_2175_p3 = ((icmp_ln139_reg_3374[0:0] == 1'b1) ? 10'd1 : add_ln139_2_fu_2169_p2);

assign select_ln139_fu_1809_p3 = ((or_ln139_fu_1804_p2[0:0] == 1'b1) ? 5'd0 : ow_reg_733);

assign select_ln73_fu_2157_p3 = ((and_ln73_fu_2151_p2[0:0] == 1'b1) ? 32'd0 : sum_reg_3691);

assign sext_ln133_fu_1431_p1 = $signed(sub_ln146_fu_1425_p2);

assign sub_ln146_1_fu_1857_p2 = (p_shl5_fu_1837_p3 - p_shl6_fu_1849_p3);

assign sub_ln146_fu_1425_p2 = (zext_ln26_fu_1410_p1 - zext_ln146_fu_1421_p1);

assign tmp_22_fu_2119_p4 = {{bitcast_ln73_fu_2116_p1[30:23]}};

assign tmp_25_fu_1414_p3 = {{n_f_fu_104}, {3'd0}};

assign tmp_s_fu_1403_p3 = {{n_f_fu_104}, {5'd0}};

assign trunc_ln137_fu_1778_p1 = select_ln137_1_fu_1723_p3[1:0];

assign trunc_ln141_fu_1863_p1 = select_ln139_fu_1809_p3[0:0];

assign trunc_ln146_1_fu_1845_p1 = add_ln146_fu_1828_p2[8:0];

assign trunc_ln146_fu_1833_p1 = add_ln146_fu_1828_p2[6:0];

assign trunc_ln73_fu_2129_p1 = bitcast_ln73_fu_2116_p1[22:0];

assign xor_ln137_fu_1782_p2 = (icmp_ln139_reg_3374 ^ 1'd1);

assign zext_ln133_fu_1399_p1 = n_f_fu_104;

assign zext_ln146_1_fu_1824_p1 = select_ln139_2_fu_1817_p3;

assign zext_ln146_2_fu_2086_p1 = lshr_ln_fu_2077_p4;

assign zext_ln146_3_fu_2095_p1 = add_ln146_1_fu_2090_p2;

assign zext_ln146_fu_1421_p1 = tmp_25_fu_1414_p3;

assign zext_ln26_fu_1410_p1 = tmp_s_fu_1403_p3;

always @ (posedge ap_clk) begin
    or_ln_reg_3238[1:0] <= 2'b00;
    sext_ln133_reg_3248[2:0] <= 3'b000;
    sub_ln146_1_reg_3429[1:0] <= 2'b00;
end

endmodule //HW_accel_Conv_func_4_26_4_24_s
