-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HW_accel_conv1_Pipeline_loadWinFull_VITIS_LOOP_50_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    window_i_2_2_promoted195 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_2_0_promoted193 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_2_1_promoted191 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_0_2_promoted189 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_0_0_promoted187 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_0_1_promoted185 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_1_2_promoted183 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_1_0_promoted181 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_1_1_promoted179 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_281138 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_179128 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_077118 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_2108 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_198 : IN STD_LOGIC_VECTOR (31 downto 0);
    mux_case_088 : IN STD_LOGIC_VECTOR (31 downto 0);
    select_ln139_1 : IN STD_LOGIC_VECTOR (4 downto 0);
    mem_1_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    mem_1_0_ce0 : OUT STD_LOGIC;
    mem_1_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out_ap_vld : OUT STD_LOGIC;
    p_out1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out1_ap_vld : OUT STD_LOGIC;
    p_out2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out2_ap_vld : OUT STD_LOGIC;
    p_out3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out3_ap_vld : OUT STD_LOGIC;
    p_out4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out4_ap_vld : OUT STD_LOGIC;
    p_out5 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out5_ap_vld : OUT STD_LOGIC;
    p_out6 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out6_ap_vld : OUT STD_LOGIC;
    p_out7 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out7_ap_vld : OUT STD_LOGIC;
    p_out8 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out8_ap_vld : OUT STD_LOGIC;
    mux_case_281136_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_281136_out_ap_vld : OUT STD_LOGIC;
    mux_case_179126_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_179126_out_ap_vld : OUT STD_LOGIC;
    mux_case_077116_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_077116_out_ap_vld : OUT STD_LOGIC;
    mux_case_2106_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_2106_out_ap_vld : OUT STD_LOGIC;
    mux_case_196_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_196_out_ap_vld : OUT STD_LOGIC;
    mux_case_086_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    mux_case_086_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of HW_accel_conv1_Pipeline_loadWinFull_VITIS_LOOP_50_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln49_fu_497_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln49_reg_890 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln52_fu_527_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_reg_894 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_reg_894_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_1_fu_535_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_1_reg_899 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln52_1_reg_899_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln52_3_fu_619_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal wj_fu_118 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln50_fu_543_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_wj_load : STD_LOGIC_VECTOR (1 downto 0);
    signal wi_fu_122 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_wi_load : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten27_fu_126 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln49_1_fu_503_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten27_load : STD_LOGIC_VECTOR (3 downto 0);
    signal mux_case_086_fu_130 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_196_fu_134 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_2106_fu_138 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_077116_fu_142 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_179126_fu_146 : STD_LOGIC_VECTOR (31 downto 0);
    signal mux_case_281136_fu_150 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_fu_154 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_36_fu_158 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_37_fu_162 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_38_fu_166 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_39_fu_170 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_40_fu_174 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_41_fu_178 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_42_fu_182 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_43_fu_186 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln50_fu_521_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln49_fu_515_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln52_fu_564_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln52_fu_567_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_572_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_23_fu_584_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln52_1_fu_580_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln52_2_fu_592_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln52_fu_596_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_36_cast_fu_602_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_24_fu_612_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_428 : BOOLEAN;
    signal ap_condition_433 : BOOLEAN;
    signal ap_condition_437 : BOOLEAN;
    signal ap_condition_440 : BOOLEAN;
    signal ap_condition_443 : BOOLEAN;
    signal ap_condition_447 : BOOLEAN;
    signal ap_condition_450 : BOOLEAN;
    signal ap_condition_455 : BOOLEAN;
    signal ap_condition_458 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component HW_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component HW_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    empty_36_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_36_fu_158 <= window_i_1_0_promoted181;
                elsif ((ap_const_boolean_1 = ap_condition_428)) then 
                    empty_36_fu_158 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_37_fu_162_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_37_fu_162 <= window_i_1_2_promoted183;
                elsif ((ap_const_boolean_1 = ap_condition_433)) then 
                    empty_37_fu_162 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_38_fu_166_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_38_fu_166 <= window_i_0_1_promoted185;
                elsif ((ap_const_boolean_1 = ap_condition_437)) then 
                    empty_38_fu_166 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_39_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_39_fu_170 <= window_i_0_0_promoted187;
                elsif ((ap_const_boolean_1 = ap_condition_440)) then 
                    empty_39_fu_170 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_40_fu_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_40_fu_174 <= window_i_0_2_promoted189;
                elsif ((ap_const_boolean_1 = ap_condition_443)) then 
                    empty_40_fu_174 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_41_fu_178_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_41_fu_178 <= window_i_2_1_promoted191;
                elsif ((ap_const_boolean_1 = ap_condition_447)) then 
                    empty_41_fu_178 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_42_fu_182_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_42_fu_182 <= window_i_2_0_promoted193;
                elsif ((ap_const_boolean_1 = ap_condition_450)) then 
                    empty_42_fu_182 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_43_fu_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_43_fu_186 <= window_i_2_2_promoted195;
                elsif ((ap_const_boolean_1 = ap_condition_455)) then 
                    empty_43_fu_186 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_fu_154 <= window_i_1_1_promoted179;
                elsif ((ap_const_boolean_1 = ap_condition_458)) then 
                    empty_fu_154 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten27_fu_126_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln49_fu_497_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten27_fu_126 <= add_ln49_1_fu_503_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten27_fu_126 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    mux_case_077116_fu_142_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    mux_case_077116_fu_142 <= mux_case_077118;
                elsif ((ap_const_boolean_1 = ap_condition_443)) then 
                    mux_case_077116_fu_142 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    mux_case_086_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    mux_case_086_fu_130 <= mux_case_088;
                elsif ((ap_const_boolean_1 = ap_condition_437)) then 
                    mux_case_086_fu_130 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    mux_case_179126_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    mux_case_179126_fu_146 <= mux_case_179128;
                elsif ((ap_const_boolean_1 = ap_condition_433)) then 
                    mux_case_179126_fu_146 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    mux_case_196_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    mux_case_196_fu_134 <= mux_case_198;
                elsif ((ap_const_boolean_1 = ap_condition_458)) then 
                    mux_case_196_fu_134 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    mux_case_2106_fu_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    mux_case_2106_fu_138 <= mux_case_2108;
                elsif ((ap_const_boolean_1 = ap_condition_447)) then 
                    mux_case_2106_fu_138 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    mux_case_281136_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    mux_case_281136_fu_150 <= mux_case_281138;
                elsif ((ap_const_boolean_1 = ap_condition_455)) then 
                    mux_case_281136_fu_150 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    wi_fu_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln49_fu_497_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    wi_fu_122 <= select_ln52_1_fu_535_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    wi_fu_122 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    wj_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln49_fu_497_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    wj_fu_118 <= add_ln50_fu_543_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    wj_fu_118 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln49_reg_890 <= icmp_ln49_fu_497_p2;
                select_ln52_1_reg_899_pp0_iter1_reg <= select_ln52_1_reg_899;
                select_ln52_reg_894_pp0_iter1_reg <= select_ln52_reg_894;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln49_fu_497_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln52_1_reg_899 <= select_ln52_1_fu_535_p3;
                select_ln52_reg_894 <= select_ln52_fu_527_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln49_1_fu_503_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten27_load) + unsigned(ap_const_lv4_1));
    add_ln49_fu_515_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_wi_load) + unsigned(ap_const_lv2_1));
    add_ln50_fu_543_p2 <= std_logic_vector(unsigned(select_ln52_fu_527_p3) + unsigned(ap_const_lv2_1));
    add_ln52_fu_567_p2 <= std_logic_vector(unsigned(select_ln139_1) + unsigned(zext_ln52_fu_564_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_428_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln52_reg_894_pp0_iter1_reg, select_ln52_1_reg_899_pp0_iter1_reg)
    begin
                ap_condition_428 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln52_1_reg_899_pp0_iter1_reg = ap_const_lv2_1) and (select_ln52_reg_894_pp0_iter1_reg = ap_const_lv2_0));
    end process;


    ap_condition_433_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln52_reg_894_pp0_iter1_reg, select_ln52_1_reg_899_pp0_iter1_reg)
    begin
                ap_condition_433 <= (not((select_ln52_reg_894_pp0_iter1_reg = ap_const_lv2_0)) and not((select_ln52_reg_894_pp0_iter1_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln52_1_reg_899_pp0_iter1_reg = ap_const_lv2_1));
    end process;


    ap_condition_437_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln52_reg_894_pp0_iter1_reg, select_ln52_1_reg_899_pp0_iter1_reg)
    begin
                ap_condition_437 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln52_1_reg_899_pp0_iter1_reg = ap_const_lv2_0) and (select_ln52_reg_894_pp0_iter1_reg = ap_const_lv2_1));
    end process;


    ap_condition_440_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln52_reg_894_pp0_iter1_reg, select_ln52_1_reg_899_pp0_iter1_reg)
    begin
                ap_condition_440 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln52_1_reg_899_pp0_iter1_reg = ap_const_lv2_0) and (select_ln52_reg_894_pp0_iter1_reg = ap_const_lv2_0));
    end process;


    ap_condition_443_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln52_reg_894_pp0_iter1_reg, select_ln52_1_reg_899_pp0_iter1_reg)
    begin
                ap_condition_443 <= (not((select_ln52_reg_894_pp0_iter1_reg = ap_const_lv2_0)) and not((select_ln52_reg_894_pp0_iter1_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln52_1_reg_899_pp0_iter1_reg = ap_const_lv2_0));
    end process;


    ap_condition_447_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln52_reg_894_pp0_iter1_reg, select_ln52_1_reg_899_pp0_iter1_reg)
    begin
                ap_condition_447 <= (not((select_ln52_1_reg_899_pp0_iter1_reg = ap_const_lv2_1)) and not((select_ln52_1_reg_899_pp0_iter1_reg = ap_const_lv2_0)) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln52_reg_894_pp0_iter1_reg = ap_const_lv2_1));
    end process;


    ap_condition_450_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln52_reg_894_pp0_iter1_reg, select_ln52_1_reg_899_pp0_iter1_reg)
    begin
                ap_condition_450 <= (not((select_ln52_1_reg_899_pp0_iter1_reg = ap_const_lv2_1)) and not((select_ln52_1_reg_899_pp0_iter1_reg = ap_const_lv2_0)) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln52_reg_894_pp0_iter1_reg = ap_const_lv2_0));
    end process;


    ap_condition_455_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln52_reg_894_pp0_iter1_reg, select_ln52_1_reg_899_pp0_iter1_reg)
    begin
                ap_condition_455 <= (not((select_ln52_reg_894_pp0_iter1_reg = ap_const_lv2_0)) and not((select_ln52_1_reg_899_pp0_iter1_reg = ap_const_lv2_1)) and not((select_ln52_reg_894_pp0_iter1_reg = ap_const_lv2_1)) and not((select_ln52_1_reg_899_pp0_iter1_reg = ap_const_lv2_0)) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_condition_458_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln52_reg_894_pp0_iter1_reg, select_ln52_1_reg_899_pp0_iter1_reg)
    begin
                ap_condition_458 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln52_1_reg_899_pp0_iter1_reg = ap_const_lv2_1) and (select_ln52_reg_894_pp0_iter1_reg = ap_const_lv2_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln49_fu_497_p2)
    begin
        if (((icmp_ln49_fu_497_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten27_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten27_fu_126)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten27_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten27_load <= indvar_flatten27_fu_126;
        end if; 
    end process;


    ap_sig_allocacmp_wi_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, wi_fu_122)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_wi_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_wi_load <= wi_fu_122;
        end if; 
    end process;


    ap_sig_allocacmp_wj_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, wj_fu_118, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_wj_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_wj_load <= wj_fu_118;
        end if; 
    end process;

    icmp_ln49_fu_497_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten27_load = ap_const_lv4_9) else "0";
    icmp_ln50_fu_521_p2 <= "1" when (ap_sig_allocacmp_wj_load = ap_const_lv2_3) else "0";
    mem_1_0_address0 <= zext_ln52_3_fu_619_p1(10 - 1 downto 0);

    mem_1_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mem_1_0_ce0 <= ap_const_logic_1;
        else 
            mem_1_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    mux_case_077116_out <= mux_case_077116_fu_142;

    mux_case_077116_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_890)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_890 = ap_const_lv1_1))) then 
            mux_case_077116_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_077116_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mux_case_086_out <= mux_case_086_fu_130;

    mux_case_086_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_890)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_890 = ap_const_lv1_1))) then 
            mux_case_086_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_086_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mux_case_179126_out <= mux_case_179126_fu_146;

    mux_case_179126_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_890)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_890 = ap_const_lv1_1))) then 
            mux_case_179126_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_179126_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mux_case_196_out <= mux_case_196_fu_134;

    mux_case_196_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_890)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_890 = ap_const_lv1_1))) then 
            mux_case_196_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_196_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mux_case_2106_out <= mux_case_2106_fu_138;

    mux_case_2106_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_890)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_890 = ap_const_lv1_1))) then 
            mux_case_2106_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_2106_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mux_case_281136_out <= mux_case_281136_fu_150;

    mux_case_281136_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_890)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_890 = ap_const_lv1_1))) then 
            mux_case_281136_out_ap_vld <= ap_const_logic_1;
        else 
            mux_case_281136_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out <= empty_43_fu_186;
    p_out1 <= empty_42_fu_182;

    p_out1_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_890)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_890 = ap_const_lv1_1))) then 
            p_out1_ap_vld <= ap_const_logic_1;
        else 
            p_out1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out2 <= empty_41_fu_178;

    p_out2_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_890)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_890 = ap_const_lv1_1))) then 
            p_out2_ap_vld <= ap_const_logic_1;
        else 
            p_out2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out3 <= empty_40_fu_174;

    p_out3_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_890)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_890 = ap_const_lv1_1))) then 
            p_out3_ap_vld <= ap_const_logic_1;
        else 
            p_out3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out4 <= empty_39_fu_170;

    p_out4_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_890)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_890 = ap_const_lv1_1))) then 
            p_out4_ap_vld <= ap_const_logic_1;
        else 
            p_out4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out5 <= empty_38_fu_166;

    p_out5_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_890)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_890 = ap_const_lv1_1))) then 
            p_out5_ap_vld <= ap_const_logic_1;
        else 
            p_out5_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out6 <= empty_37_fu_162;

    p_out6_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_890)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_890 = ap_const_lv1_1))) then 
            p_out6_ap_vld <= ap_const_logic_1;
        else 
            p_out6_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out7 <= empty_36_fu_158;

    p_out7_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_890)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_890 = ap_const_lv1_1))) then 
            p_out7_ap_vld <= ap_const_logic_1;
        else 
            p_out7_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out8 <= empty_fu_154;

    p_out8_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_890)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_890 = ap_const_lv1_1))) then 
            p_out8_ap_vld <= ap_const_logic_1;
        else 
            p_out8_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_890)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_890 = ap_const_lv1_1))) then 
            p_out_ap_vld <= ap_const_logic_1;
        else 
            p_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln52_1_fu_535_p3 <= 
        add_ln49_fu_515_p2 when (icmp_ln50_fu_521_p2(0) = '1') else 
        ap_sig_allocacmp_wi_load;
    select_ln52_fu_527_p3 <= 
        ap_const_lv2_0 when (icmp_ln50_fu_521_p2(0) = '1') else 
        ap_sig_allocacmp_wj_load;
    sub_ln52_fu_596_p2 <= std_logic_vector(unsigned(zext_ln52_1_fu_580_p1) - unsigned(zext_ln52_2_fu_592_p1));
    tmp_23_fu_584_p3 <= (add_ln52_fu_567_p2 & ap_const_lv2_0);
    tmp_24_fu_612_p3 <= (tmp_36_cast_fu_602_p4 & select_ln52_reg_894);
    tmp_36_cast_fu_602_p4 <= sub_ln52_fu_596_p2(9 downto 2);
    tmp_s_fu_572_p3 <= (add_ln52_fu_567_p2 & ap_const_lv5_0);
    zext_ln52_1_fu_580_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_572_p3),11));
    zext_ln52_2_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_23_fu_584_p3),11));
    zext_ln52_3_fu_619_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_24_fu_612_p3),64));
    zext_ln52_fu_564_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln52_1_reg_899),5));
end behav;
