-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HW_accel_fc_layer2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_r_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_r_ce1 : OUT STD_LOGIC;
    output_r_we1 : OUT STD_LOGIC;
    output_r_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of HW_accel_fc_layer2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (15 downto 0) := "0000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (15 downto 0) := "0000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (15 downto 0) := "0000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (15 downto 0) := "0000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (15 downto 0) := "0001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (15 downto 0) := "0010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (15 downto 0) := "0100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal fc2_bias_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal fc2_bias_ce0 : STD_LOGIC;
    signal fc2_bias_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_bias_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal fc2_bias_ce1 : STD_LOGIC;
    signal fc2_bias_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_bias_address2 : STD_LOGIC_VECTOR (3 downto 0);
    signal fc2_bias_ce2 : STD_LOGIC;
    signal fc2_bias_q2 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_bias_address3 : STD_LOGIC_VECTOR (3 downto 0);
    signal fc2_bias_ce3 : STD_LOGIC;
    signal fc2_bias_q3 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_bias_address4 : STD_LOGIC_VECTOR (3 downto 0);
    signal fc2_bias_ce4 : STD_LOGIC;
    signal fc2_bias_q4 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_weight_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal fc2_weight_ce0 : STD_LOGIC;
    signal fc2_weight_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_weight_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal fc2_weight_ce1 : STD_LOGIC;
    signal fc2_weight_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_weight_address2 : STD_LOGIC_VECTOR (7 downto 0);
    signal fc2_weight_ce2 : STD_LOGIC;
    signal fc2_weight_q2 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_weight_address3 : STD_LOGIC_VECTOR (7 downto 0);
    signal fc2_weight_ce3 : STD_LOGIC;
    signal fc2_weight_q3 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_weight_address4 : STD_LOGIC_VECTOR (7 downto 0);
    signal fc2_weight_ce4 : STD_LOGIC;
    signal fc2_weight_q4 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln213_fu_464_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln213_reg_864 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal empty_25_fu_470_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_25_reg_869 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln213_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_cast30_fu_482_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast30_reg_874 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_26_fu_491_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_26_reg_884 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_cast31_fu_497_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast31_reg_889 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_27_fu_502_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_27_reg_899 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_cast32_fu_508_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast32_reg_904 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_28_fu_513_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_28_reg_914 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_cast33_fu_519_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast33_reg_919 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_29_fu_524_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_29_reg_929 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_cast34_fu_530_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal p_cast34_reg_934 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_27_cast_fu_543_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_27_cast_reg_944 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_28_cast_fu_554_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_28_cast_reg_949 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_29_cast_fu_565_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_29_cast_reg_954 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_fu_569_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_reg_959 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_fu_576_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_21_reg_964 : STD_LOGIC_VECTOR (7 downto 0);
    signal fc2_bias_load_reg_969 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_bias_load_1_reg_974 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_bias_load_2_reg_979 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_bias_load_3_reg_984 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_bias_load_4_reg_989 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal add_ln216_fu_643_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln216_reg_1022 : STD_LOGIC_VECTOR (4 downto 0);
    signal ip_fu_649_p18 : STD_LOGIC_VECTOR (31 downto 0);
    signal ip_reg_1027 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln216_fu_637_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln220_fu_677_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln220_reg_1036 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln220_1_fu_684_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln220_1_reg_1041 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln220_2_fu_691_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln220_2_reg_1046 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln220_3_fu_698_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln220_3_reg_1051 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln220_4_fu_705_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln220_4_reg_1056 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_weight_load_reg_1061 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal fc2_weight_load_1_reg_1066 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_weight_load_2_reg_1071 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_weight_load_3_reg_1076 : STD_LOGIC_VECTOR (31 downto 0);
    signal fc2_weight_load_4_reg_1081 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_410_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul31_i_reg_1086 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_fu_414_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul31_1_i_reg_1091 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_418_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul31_2_i_reg_1096 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_422_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul31_3_i_reg_1101 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_426_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul31_4_i_reg_1106 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_index_reg_379 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal zext_ln230_1_fu_592_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln230_2_fu_602_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln230_3_fu_612_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln230_4_fu_622_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln230_5_fu_632_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal turn_fu_88 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal add32_lcssa19_i_fu_92 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_390_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add32_1_lcssa21_i_fu_96 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_394_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add32_2_lcssa23_i_fu_100 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_398_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add32_3_lcssa25_i_fu_104 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_402_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add32_4_lcssa27_i_fu_108 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_406_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_s_fu_474_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_cast_fu_487_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_17_fu_535_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_18_fu_547_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_19_fu_558_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln230_fu_583_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln230_fu_587_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln230_1_fu_597_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln230_2_fu_607_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln230_3_fu_617_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln230_4_fu_627_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal cmp9_i_fu_671_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component HW_accel_mux_165_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        din16 : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component HW_accel_fc_layer2_fc2_bias_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address2 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address3 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address4 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component HW_accel_fc_layer2_fc2_weight_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address2 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address3 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address4 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    fc2_bias_U : component HW_accel_fc_layer2_fc2_bias_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => fc2_bias_address0,
        ce0 => fc2_bias_ce0,
        q0 => fc2_bias_q0,
        address1 => fc2_bias_address1,
        ce1 => fc2_bias_ce1,
        q1 => fc2_bias_q1,
        address2 => fc2_bias_address2,
        ce2 => fc2_bias_ce2,
        q2 => fc2_bias_q2,
        address3 => fc2_bias_address3,
        ce3 => fc2_bias_ce3,
        q3 => fc2_bias_q3,
        address4 => fc2_bias_address4,
        ce4 => fc2_bias_ce4,
        q4 => fc2_bias_q4);

    fc2_weight_U : component HW_accel_fc_layer2_fc2_weight_ROM_AUTO_1R
    generic map (
        DataWidth => 32,
        AddressRange => 160,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => fc2_weight_address0,
        ce0 => fc2_weight_ce0,
        q0 => fc2_weight_q0,
        address1 => fc2_weight_address1,
        ce1 => fc2_weight_ce1,
        q1 => fc2_weight_q1,
        address2 => fc2_weight_address2,
        ce2 => fc2_weight_ce2,
        q2 => fc2_weight_q2,
        address3 => fc2_weight_address3,
        ce3 => fc2_weight_ce3,
        q3 => fc2_weight_q3,
        address4 => fc2_weight_address4,
        ce4 => fc2_weight_ce4,
        q4 => fc2_weight_q4);

    fadd_32ns_32ns_32_5_full_dsp_1_U430 : component HW_accel_fadd_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln220_2_reg_1046,
        din1 => mul31_i_reg_1086,
        ce => ap_const_logic_1,
        dout => grp_fu_390_p2);

    fadd_32ns_32ns_32_5_full_dsp_1_U431 : component HW_accel_fadd_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln220_1_reg_1041,
        din1 => mul31_1_i_reg_1091,
        ce => ap_const_logic_1,
        dout => grp_fu_394_p2);

    fadd_32ns_32ns_32_5_full_dsp_1_U432 : component HW_accel_fadd_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln220_3_reg_1051,
        din1 => mul31_2_i_reg_1096,
        ce => ap_const_logic_1,
        dout => grp_fu_398_p2);

    fadd_32ns_32ns_32_5_full_dsp_1_U433 : component HW_accel_fadd_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln220_reg_1036,
        din1 => mul31_3_i_reg_1101,
        ce => ap_const_logic_1,
        dout => grp_fu_402_p2);

    fadd_32ns_32ns_32_5_full_dsp_1_U434 : component HW_accel_fadd_32ns_32ns_32_5_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln220_4_reg_1056,
        din1 => mul31_4_i_reg_1106,
        ce => ap_const_logic_1,
        dout => grp_fu_406_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U435 : component HW_accel_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ip_reg_1027,
        din1 => fc2_weight_load_reg_1061,
        ce => ap_const_logic_1,
        dout => grp_fu_410_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U436 : component HW_accel_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ip_reg_1027,
        din1 => fc2_weight_load_1_reg_1066,
        ce => ap_const_logic_1,
        dout => grp_fu_414_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U437 : component HW_accel_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ip_reg_1027,
        din1 => fc2_weight_load_2_reg_1071,
        ce => ap_const_logic_1,
        dout => grp_fu_418_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U438 : component HW_accel_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ip_reg_1027,
        din1 => fc2_weight_load_3_reg_1076,
        ce => ap_const_logic_1,
        dout => grp_fu_422_p2);

    fmul_32ns_32ns_32_4_max_dsp_1_U439 : component HW_accel_fmul_32ns_32ns_32_4_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ip_reg_1027,
        din1 => fc2_weight_load_4_reg_1081,
        ce => ap_const_logic_1,
        dout => grp_fu_426_p2);

    mux_165_32_1_1_U440 : component HW_accel_mux_165_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        din2_WIDTH => 32,
        din3_WIDTH => 32,
        din4_WIDTH => 32,
        din5_WIDTH => 32,
        din6_WIDTH => 32,
        din7_WIDTH => 32,
        din8_WIDTH => 32,
        din9_WIDTH => 32,
        din10_WIDTH => 32,
        din11_WIDTH => 32,
        din12_WIDTH => 32,
        din13_WIDTH => 32,
        din14_WIDTH => 32,
        din15_WIDTH => 32,
        din16_WIDTH => 5,
        dout_WIDTH => 32)
    port map (
        din0 => p_read,
        din1 => p_read1,
        din2 => p_read2,
        din3 => p_read3,
        din4 => p_read4,
        din5 => p_read5,
        din6 => p_read6,
        din7 => p_read7,
        din8 => p_read8,
        din9 => p_read9,
        din10 => p_read10,
        din11 => p_read11,
        din12 => p_read12,
        din13 => p_read13,
        din14 => p_read14,
        din15 => p_read15,
        din16 => i_index_reg_379,
        dout => ip_fu_649_p18);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln213_fu_458_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_index_reg_379_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                i_index_reg_379 <= ap_const_lv5_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                i_index_reg_379 <= add_ln216_reg_1022;
            end if; 
        end if;
    end process;

    turn_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                turn_fu_88 <= ap_const_lv2_0;
            elsif (((icmp_ln216_fu_637_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                turn_fu_88 <= add_ln213_reg_864;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                add32_1_lcssa21_i_fu_96 <= grp_fu_394_p2;
                add32_2_lcssa23_i_fu_100 <= grp_fu_398_p2;
                add32_3_lcssa25_i_fu_104 <= grp_fu_402_p2;
                add32_4_lcssa27_i_fu_108 <= grp_fu_406_p2;
                add32_lcssa19_i_fu_92 <= grp_fu_390_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln213_reg_864 <= add_ln213_fu_464_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln216_reg_1022 <= add_ln216_fu_643_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln213_fu_458_p2 = ap_const_lv1_0))) then
                empty_25_reg_869 <= empty_25_fu_470_p1;
                empty_26_reg_884 <= empty_26_fu_491_p2;
                empty_27_reg_899 <= empty_27_fu_502_p2;
                empty_28_reg_914 <= empty_28_fu_513_p2;
                empty_29_reg_929 <= empty_29_fu_524_p2;
                    p_cast30_reg_874(2 downto 0) <= p_cast30_fu_482_p1(2 downto 0);
                    p_cast31_reg_889(2 downto 0) <= p_cast31_fu_497_p1(2 downto 0);
                    p_cast32_reg_904(2 downto 0) <= p_cast32_fu_508_p1(2 downto 0);
                    p_cast33_reg_919(3 downto 0) <= p_cast33_fu_519_p1(3 downto 0);
                    p_cast34_reg_934(3 downto 0) <= p_cast34_fu_530_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                fc2_bias_load_1_reg_974 <= fc2_bias_q3;
                fc2_bias_load_2_reg_979 <= fc2_bias_q2;
                fc2_bias_load_3_reg_984 <= fc2_bias_q1;
                fc2_bias_load_4_reg_989 <= fc2_bias_q0;
                fc2_bias_load_reg_969 <= fc2_bias_q4;
                    tmp_20_reg_959(7 downto 4) <= tmp_20_fu_569_p3(7 downto 4);
                    tmp_21_reg_964(7 downto 4) <= tmp_21_fu_576_p3(7 downto 4);
                    tmp_27_cast_reg_944(6 downto 4) <= tmp_27_cast_fu_543_p1(6 downto 4);
                    tmp_28_cast_reg_949(6 downto 4) <= tmp_28_cast_fu_554_p1(6 downto 4);
                    tmp_29_cast_reg_954(6 downto 4) <= tmp_29_cast_fu_565_p1(6 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                fc2_weight_load_1_reg_1066 <= fc2_weight_q3;
                fc2_weight_load_2_reg_1071 <= fc2_weight_q2;
                fc2_weight_load_3_reg_1076 <= fc2_weight_q1;
                fc2_weight_load_4_reg_1081 <= fc2_weight_q0;
                fc2_weight_load_reg_1061 <= fc2_weight_q4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln216_fu_637_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                ip_reg_1027 <= ip_fu_649_p18;
                select_ln220_1_reg_1041 <= select_ln220_1_fu_684_p3;
                select_ln220_2_reg_1046 <= select_ln220_2_fu_691_p3;
                select_ln220_3_reg_1051 <= select_ln220_3_fu_698_p3;
                select_ln220_4_reg_1056 <= select_ln220_4_fu_705_p3;
                select_ln220_reg_1036 <= select_ln220_fu_677_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                mul31_1_i_reg_1091 <= grp_fu_414_p2;
                mul31_2_i_reg_1096 <= grp_fu_418_p2;
                mul31_3_i_reg_1101 <= grp_fu_422_p2;
                mul31_4_i_reg_1106 <= grp_fu_426_p2;
                mul31_i_reg_1086 <= grp_fu_410_p2;
            end if;
        end if;
    end process;
    p_cast30_reg_874(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    p_cast31_reg_889(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    p_cast32_reg_904(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";
    p_cast33_reg_919(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    p_cast34_reg_934(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    tmp_27_cast_reg_944(3 downto 0) <= "0000";
    tmp_27_cast_reg_944(7) <= '0';
    tmp_28_cast_reg_949(3 downto 0) <= "0000";
    tmp_28_cast_reg_949(7) <= '0';
    tmp_29_cast_reg_954(3 downto 0) <= "0000";
    tmp_29_cast_reg_954(7) <= '0';
    tmp_20_reg_959(3 downto 0) <= "0000";
    tmp_21_reg_964(3 downto 0) <= "0000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln213_fu_458_p2, ap_CS_fsm_state4, icmp_ln216_fu_637_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln213_fu_458_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln216_fu_637_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln213_fu_464_p2 <= std_logic_vector(unsigned(turn_fu_88) + unsigned(ap_const_lv2_1));
    add_ln216_fu_643_p2 <= std_logic_vector(unsigned(i_index_reg_379) + unsigned(ap_const_lv5_1));
    add_ln230_1_fu_597_p2 <= std_logic_vector(unsigned(tmp_28_cast_reg_949) + unsigned(zext_ln230_fu_583_p1));
    add_ln230_2_fu_607_p2 <= std_logic_vector(unsigned(tmp_29_cast_reg_954) + unsigned(zext_ln230_fu_583_p1));
    add_ln230_3_fu_617_p2 <= std_logic_vector(unsigned(tmp_20_reg_959) + unsigned(zext_ln230_fu_583_p1));
    add_ln230_4_fu_627_p2 <= std_logic_vector(unsigned(tmp_21_reg_964) + unsigned(zext_ln230_fu_583_p1));
    add_ln230_fu_587_p2 <= std_logic_vector(unsigned(tmp_27_cast_reg_944) + unsigned(zext_ln230_fu_583_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln213_fu_458_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln213_fu_458_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln213_fu_458_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln213_fu_458_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    cmp9_i_fu_671_p2 <= "1" when (i_index_reg_379 = ap_const_lv5_0) else "0";
    empty_25_fu_470_p1 <= turn_fu_88(1 - 1 downto 0);
    empty_26_fu_491_p2 <= std_logic_vector(unsigned(tmp_s_fu_474_p3) + unsigned(ap_const_lv3_1));
    empty_27_fu_502_p2 <= std_logic_vector(unsigned(tmp_s_fu_474_p3) + unsigned(ap_const_lv3_2));
    empty_28_fu_513_p2 <= std_logic_vector(unsigned(p_cast_fu_487_p1) + unsigned(ap_const_lv4_3));
    empty_29_fu_524_p2 <= std_logic_vector(unsigned(p_cast_fu_487_p1) + unsigned(ap_const_lv4_4));
    fc2_bias_address0 <= p_cast34_fu_530_p1(4 - 1 downto 0);
    fc2_bias_address1 <= p_cast33_fu_519_p1(4 - 1 downto 0);
    fc2_bias_address2 <= p_cast32_fu_508_p1(4 - 1 downto 0);
    fc2_bias_address3 <= p_cast31_fu_497_p1(4 - 1 downto 0);
    fc2_bias_address4 <= p_cast30_fu_482_p1(4 - 1 downto 0);

    fc2_bias_ce0_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fc2_bias_ce0 <= ap_const_logic_1;
        else 
            fc2_bias_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    fc2_bias_ce1_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fc2_bias_ce1 <= ap_const_logic_1;
        else 
            fc2_bias_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    fc2_bias_ce2_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fc2_bias_ce2 <= ap_const_logic_1;
        else 
            fc2_bias_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    fc2_bias_ce3_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fc2_bias_ce3 <= ap_const_logic_1;
        else 
            fc2_bias_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    fc2_bias_ce4_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            fc2_bias_ce4 <= ap_const_logic_1;
        else 
            fc2_bias_ce4 <= ap_const_logic_0;
        end if; 
    end process;

    fc2_weight_address0 <= zext_ln230_5_fu_632_p1(8 - 1 downto 0);
    fc2_weight_address1 <= zext_ln230_4_fu_622_p1(8 - 1 downto 0);
    fc2_weight_address2 <= zext_ln230_3_fu_612_p1(8 - 1 downto 0);
    fc2_weight_address3 <= zext_ln230_2_fu_602_p1(8 - 1 downto 0);
    fc2_weight_address4 <= zext_ln230_1_fu_592_p1(8 - 1 downto 0);

    fc2_weight_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            fc2_weight_ce0 <= ap_const_logic_1;
        else 
            fc2_weight_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    fc2_weight_ce1_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            fc2_weight_ce1 <= ap_const_logic_1;
        else 
            fc2_weight_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    fc2_weight_ce2_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            fc2_weight_ce2 <= ap_const_logic_1;
        else 
            fc2_weight_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    fc2_weight_ce3_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            fc2_weight_ce3 <= ap_const_logic_1;
        else 
            fc2_weight_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    fc2_weight_ce4_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            fc2_weight_ce4 <= ap_const_logic_1;
        else 
            fc2_weight_ce4 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln213_fu_458_p2 <= "1" when (turn_fu_88 = ap_const_lv2_2) else "0";
    icmp_ln216_fu_637_p2 <= "1" when (i_index_reg_379 = ap_const_lv5_10) else "0";

    output_r_address0_assign_proc : process(p_cast31_reg_889, p_cast33_reg_919, p_cast34_reg_934, ap_CS_fsm_state4, ap_CS_fsm_state15, ap_CS_fsm_state16)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            output_r_address0 <= p_cast34_reg_934(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            output_r_address0 <= p_cast33_reg_919(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_r_address0 <= p_cast31_reg_889(4 - 1 downto 0);
        else 
            output_r_address0 <= "XXXX";
        end if; 
    end process;


    output_r_address1_assign_proc : process(p_cast30_reg_874, p_cast32_reg_904, ap_CS_fsm_state4, ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            output_r_address1 <= p_cast32_reg_904(4 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_r_address1 <= p_cast30_reg_874(4 - 1 downto 0);
        else 
            output_r_address1 <= "XXXX";
        end if; 
    end process;


    output_r_ce0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state15, ap_CS_fsm_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_r_ce0 <= ap_const_logic_1;
        else 
            output_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_r_ce1_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state15)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            output_r_ce1 <= ap_const_logic_1;
        else 
            output_r_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    output_r_d0_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state15, ap_CS_fsm_state16, add32_1_lcssa21_i_fu_96, add32_3_lcssa25_i_fu_104, add32_4_lcssa27_i_fu_108)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state16)) then 
            output_r_d0 <= add32_4_lcssa27_i_fu_108;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            output_r_d0 <= add32_3_lcssa25_i_fu_104;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_r_d0 <= add32_1_lcssa21_i_fu_96;
        else 
            output_r_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    output_r_d1_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state15, add32_lcssa19_i_fu_92, add32_2_lcssa23_i_fu_100)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            output_r_d1 <= add32_2_lcssa23_i_fu_100;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            output_r_d1 <= add32_lcssa19_i_fu_92;
        else 
            output_r_d1 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    output_r_we0_assign_proc : process(ap_CS_fsm_state4, icmp_ln216_fu_637_p2, ap_CS_fsm_state15, ap_CS_fsm_state16)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state16) or (ap_const_logic_1 = ap_CS_fsm_state15) or ((icmp_ln216_fu_637_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            output_r_we0 <= ap_const_logic_1;
        else 
            output_r_we0 <= ap_const_logic_0;
        end if; 
    end process;


    output_r_we1_assign_proc : process(ap_CS_fsm_state4, icmp_ln216_fu_637_p2, ap_CS_fsm_state15)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state15) or ((icmp_ln216_fu_637_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4)))) then 
            output_r_we1 <= ap_const_logic_1;
        else 
            output_r_we1 <= ap_const_logic_0;
        end if; 
    end process;

    p_cast30_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_474_p3),64));
    p_cast31_fu_497_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_26_fu_491_p2),64));
    p_cast32_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_27_fu_502_p2),64));
    p_cast33_fu_519_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_28_fu_513_p2),64));
    p_cast34_fu_530_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_29_fu_524_p2),64));
    p_cast_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_474_p3),4));
    select_ln220_1_fu_684_p3 <= 
        fc2_bias_load_1_reg_974 when (cmp9_i_fu_671_p2(0) = '1') else 
        add32_1_lcssa21_i_fu_96;
    select_ln220_2_fu_691_p3 <= 
        fc2_bias_load_reg_969 when (cmp9_i_fu_671_p2(0) = '1') else 
        add32_lcssa19_i_fu_92;
    select_ln220_3_fu_698_p3 <= 
        fc2_bias_load_2_reg_979 when (cmp9_i_fu_671_p2(0) = '1') else 
        add32_2_lcssa23_i_fu_100;
    select_ln220_4_fu_705_p3 <= 
        fc2_bias_load_4_reg_989 when (cmp9_i_fu_671_p2(0) = '1') else 
        add32_4_lcssa27_i_fu_108;
    select_ln220_fu_677_p3 <= 
        fc2_bias_load_3_reg_984 when (cmp9_i_fu_671_p2(0) = '1') else 
        add32_3_lcssa25_i_fu_104;
    tmp_17_fu_535_p4 <= ((empty_25_reg_869 & turn_fu_88) & ap_const_lv4_0);
    tmp_18_fu_547_p3 <= (empty_26_reg_884 & ap_const_lv4_0);
    tmp_19_fu_558_p3 <= (empty_27_reg_899 & ap_const_lv4_0);
    tmp_20_fu_569_p3 <= (empty_28_reg_914 & ap_const_lv4_0);
    tmp_21_fu_576_p3 <= (empty_29_reg_929 & ap_const_lv4_0);
    tmp_27_cast_fu_543_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_17_fu_535_p4),8));
    tmp_28_cast_fu_554_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_18_fu_547_p3),8));
    tmp_29_cast_fu_565_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_19_fu_558_p3),8));
    tmp_s_fu_474_p3 <= (empty_25_fu_470_p1 & turn_fu_88);
    zext_ln230_1_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln230_fu_587_p2),64));
    zext_ln230_2_fu_602_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln230_1_fu_597_p2),64));
    zext_ln230_3_fu_612_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln230_2_fu_607_p2),64));
    zext_ln230_4_fu_622_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln230_3_fu_617_p2),64));
    zext_ln230_5_fu_632_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln230_4_fu_627_p2),64));
    zext_ln230_fu_583_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_index_reg_379),8));
end behav;
