-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HW_accel_fc_layer117 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of HW_accel_fc_layer117 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_FC_layer_100_16_true_s_fu_8_ap_start : STD_LOGIC;
    signal grp_FC_layer_100_16_true_s_fu_8_ap_done : STD_LOGIC;
    signal grp_FC_layer_100_16_true_s_fu_8_ap_idle : STD_LOGIC;
    signal grp_FC_layer_100_16_true_s_fu_8_ap_ready : STD_LOGIC;
    signal grp_FC_layer_100_16_true_s_fu_8_input_r_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_input_r_ce0 : STD_LOGIC;
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_5 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_6 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_7 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_8 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_9 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_10 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_11 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_12 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_13 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_14 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_return_15 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_FC_layer_100_16_true_s_fu_8_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call0 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component HW_accel_FC_layer_100_16_true_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    grp_FC_layer_100_16_true_s_fu_8 : component HW_accel_FC_layer_100_16_true_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_FC_layer_100_16_true_s_fu_8_ap_start,
        ap_done => grp_FC_layer_100_16_true_s_fu_8_ap_done,
        ap_idle => grp_FC_layer_100_16_true_s_fu_8_ap_idle,
        ap_ready => grp_FC_layer_100_16_true_s_fu_8_ap_ready,
        input_r_address0 => grp_FC_layer_100_16_true_s_fu_8_input_r_address0,
        input_r_ce0 => grp_FC_layer_100_16_true_s_fu_8_input_r_ce0,
        input_r_q0 => input_r_q0,
        ap_return_0 => grp_FC_layer_100_16_true_s_fu_8_ap_return_0,
        ap_return_1 => grp_FC_layer_100_16_true_s_fu_8_ap_return_1,
        ap_return_2 => grp_FC_layer_100_16_true_s_fu_8_ap_return_2,
        ap_return_3 => grp_FC_layer_100_16_true_s_fu_8_ap_return_3,
        ap_return_4 => grp_FC_layer_100_16_true_s_fu_8_ap_return_4,
        ap_return_5 => grp_FC_layer_100_16_true_s_fu_8_ap_return_5,
        ap_return_6 => grp_FC_layer_100_16_true_s_fu_8_ap_return_6,
        ap_return_7 => grp_FC_layer_100_16_true_s_fu_8_ap_return_7,
        ap_return_8 => grp_FC_layer_100_16_true_s_fu_8_ap_return_8,
        ap_return_9 => grp_FC_layer_100_16_true_s_fu_8_ap_return_9,
        ap_return_10 => grp_FC_layer_100_16_true_s_fu_8_ap_return_10,
        ap_return_11 => grp_FC_layer_100_16_true_s_fu_8_ap_return_11,
        ap_return_12 => grp_FC_layer_100_16_true_s_fu_8_ap_return_12,
        ap_return_13 => grp_FC_layer_100_16_true_s_fu_8_ap_return_13,
        ap_return_14 => grp_FC_layer_100_16_true_s_fu_8_ap_return_14,
        ap_return_15 => grp_FC_layer_100_16_true_s_fu_8_ap_return_15);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((grp_FC_layer_100_16_true_s_fu_8_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_FC_layer_100_16_true_s_fu_8_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_FC_layer_100_16_true_s_fu_8_ap_start_reg <= ap_const_logic_0;
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_FC_layer_100_16_true_s_fu_8_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_FC_layer_100_16_true_s_fu_8_ap_ready = ap_const_logic_1)) then 
                    grp_FC_layer_100_16_true_s_fu_8_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, grp_FC_layer_100_16_true_s_fu_8_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_FC_layer_100_16_true_s_fu_8_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_FC_layer_100_16_true_s_fu_8_ap_done)
    begin
        if ((grp_FC_layer_100_16_true_s_fu_8_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call0_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call0 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, grp_FC_layer_100_16_true_s_fu_8_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_FC_layer_100_16_true_s_fu_8_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_FC_layer_100_16_true_s_fu_8_ap_done, ap_CS_fsm_state2)
    begin
        if (((grp_FC_layer_100_16_true_s_fu_8_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_0;
    ap_return_1 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_1;
    ap_return_10 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_10;
    ap_return_11 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_11;
    ap_return_12 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_12;
    ap_return_13 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_13;
    ap_return_14 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_14;
    ap_return_15 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_15;
    ap_return_2 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_2;
    ap_return_3 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_3;
    ap_return_4 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_4;
    ap_return_5 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_5;
    ap_return_6 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_6;
    ap_return_7 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_7;
    ap_return_8 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_8;
    ap_return_9 <= grp_FC_layer_100_16_true_s_fu_8_ap_return_9;
    grp_FC_layer_100_16_true_s_fu_8_ap_start <= grp_FC_layer_100_16_true_s_fu_8_ap_start_reg;
    input_r_address0 <= grp_FC_layer_100_16_true_s_fu_8_input_r_address0;
    input_r_ce0 <= grp_FC_layer_100_16_true_s_fu_8_input_r_ce0;
end behav;
