-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity HW_accel_conv1_Pipeline_loadWin1_VITIS_LOOP_50_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    window_i_2_2_promoted117 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_2_0_promoted115 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_2_1_promoted113 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_0_2_promoted111 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_0_0_promoted109 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_0_1_promoted107 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_1_2_promoted105 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_1_0_promoted103 : IN STD_LOGIC_VECTOR (31 downto 0);
    window_i_1_1_promoted101 : IN STD_LOGIC_VECTOR (31 downto 0);
    select_ln150_7 : IN STD_LOGIC_VECTOR (4 downto 0);
    select_ln150 : IN STD_LOGIC_VECTOR (4 downto 0);
    mem_1_0_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    mem_1_0_ce0 : OUT STD_LOGIC;
    mem_1_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out_ap_vld : OUT STD_LOGIC;
    p_out1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out1_ap_vld : OUT STD_LOGIC;
    p_out2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out2_ap_vld : OUT STD_LOGIC;
    p_out3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out3_ap_vld : OUT STD_LOGIC;
    p_out4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out4_ap_vld : OUT STD_LOGIC;
    p_out5 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out5_ap_vld : OUT STD_LOGIC;
    p_out6 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out6_ap_vld : OUT STD_LOGIC;
    p_out7 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out7_ap_vld : OUT STD_LOGIC;
    p_out8 : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_out8_ap_vld : OUT STD_LOGIC );
end;


architecture behav of HW_accel_conv1_Pipeline_loadWin1_VITIS_LOOP_50_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln49_fu_341_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln49_reg_631 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln49_fu_371_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln49_reg_635 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln49_reg_635_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln49_3_fu_379_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln49_3_reg_639 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln49_3_reg_639_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln49_5_fu_391_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln49_5_reg_643 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln52_fu_401_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln52_reg_649 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln52_7_fu_461_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal wj_fu_88 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln50_fu_407_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_wj_load : STD_LOGIC_VECTOR (1 downto 0);
    signal wi_fu_92 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_sig_allocacmp_wi_load : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten27_fu_96 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln49_6_fu_347_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_indvar_flatten27_load : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_fu_100 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_129_fu_104 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_130_fu_108 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_131_fu_112 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_132_fu_116 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_133_fu_120 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_134_fu_124 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_135_fu_128 : STD_LOGIC_VECTOR (31 downto 0);
    signal empty_136_fu_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln50_fu_365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln49_fu_359_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln49_fu_387_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln50_fu_397_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_26_fu_435_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_s_fu_428_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln52_fu_442_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln52_fu_446_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln52_6_fu_452_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln52_5_fu_455_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_365 : BOOLEAN;
    signal ap_condition_370 : BOOLEAN;
    signal ap_condition_374 : BOOLEAN;
    signal ap_condition_377 : BOOLEAN;
    signal ap_condition_380 : BOOLEAN;
    signal ap_condition_384 : BOOLEAN;
    signal ap_condition_387 : BOOLEAN;
    signal ap_condition_392 : BOOLEAN;
    signal ap_condition_395 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component HW_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component HW_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    empty_129_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_129_fu_104 <= window_i_1_0_promoted103;
                elsif ((ap_const_boolean_1 = ap_condition_365)) then 
                    empty_129_fu_104 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_130_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_130_fu_108 <= window_i_1_2_promoted105;
                elsif ((ap_const_boolean_1 = ap_condition_370)) then 
                    empty_130_fu_108 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_131_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_131_fu_112 <= window_i_0_1_promoted107;
                elsif ((ap_const_boolean_1 = ap_condition_374)) then 
                    empty_131_fu_112 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_132_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_132_fu_116 <= window_i_0_0_promoted109;
                elsif ((ap_const_boolean_1 = ap_condition_377)) then 
                    empty_132_fu_116 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_133_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_133_fu_120 <= window_i_0_2_promoted111;
                elsif ((ap_const_boolean_1 = ap_condition_380)) then 
                    empty_133_fu_120 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_134_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_134_fu_124 <= window_i_2_1_promoted113;
                elsif ((ap_const_boolean_1 = ap_condition_384)) then 
                    empty_134_fu_124 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_135_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_135_fu_128 <= window_i_2_0_promoted115;
                elsif ((ap_const_boolean_1 = ap_condition_387)) then 
                    empty_135_fu_128 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_136_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_136_fu_132 <= window_i_2_2_promoted117;
                elsif ((ap_const_boolean_1 = ap_condition_392)) then 
                    empty_136_fu_132 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    empty_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
                    empty_fu_100 <= window_i_1_1_promoted101;
                elsif ((ap_const_boolean_1 = ap_condition_395)) then 
                    empty_fu_100 <= mem_1_0_q0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten27_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln49_fu_341_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten27_fu_96 <= add_ln49_6_fu_347_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten27_fu_96 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    wi_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln49_fu_341_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    wi_fu_92 <= select_ln49_3_fu_379_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    wi_fu_92 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    wj_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln49_fu_341_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    wj_fu_88 <= add_ln50_fu_407_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    wj_fu_88 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln49_fu_341_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln49_5_reg_643 <= add_ln49_5_fu_391_p2;
                add_ln52_reg_649 <= add_ln52_fu_401_p2;
                select_ln49_3_reg_639 <= select_ln49_3_fu_379_p3;
                select_ln49_reg_635 <= select_ln49_fu_371_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln49_reg_631 <= icmp_ln49_fu_341_p2;
                select_ln49_3_reg_639_pp0_iter1_reg <= select_ln49_3_reg_639;
                select_ln49_reg_635_pp0_iter1_reg <= select_ln49_reg_635;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln49_5_fu_391_p2 <= std_logic_vector(unsigned(select_ln150_7) + unsigned(zext_ln49_fu_387_p1));
    add_ln49_6_fu_347_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten27_load) + unsigned(ap_const_lv4_1));
    add_ln49_fu_359_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_wi_load) + unsigned(ap_const_lv2_1));
    add_ln50_fu_407_p2 <= std_logic_vector(unsigned(select_ln49_fu_371_p3) + unsigned(ap_const_lv2_1));
    add_ln52_5_fu_455_p2 <= std_logic_vector(unsigned(sub_ln52_fu_446_p2) + unsigned(zext_ln52_6_fu_452_p1));
    add_ln52_fu_401_p2 <= std_logic_vector(unsigned(select_ln150) + unsigned(zext_ln50_fu_397_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_365_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln49_reg_635_pp0_iter1_reg, select_ln49_3_reg_639_pp0_iter1_reg)
    begin
                ap_condition_365 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln49_3_reg_639_pp0_iter1_reg = ap_const_lv2_1) and (select_ln49_reg_635_pp0_iter1_reg = ap_const_lv2_0));
    end process;


    ap_condition_370_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln49_reg_635_pp0_iter1_reg, select_ln49_3_reg_639_pp0_iter1_reg)
    begin
                ap_condition_370 <= (not((select_ln49_reg_635_pp0_iter1_reg = ap_const_lv2_0)) and not((select_ln49_reg_635_pp0_iter1_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln49_3_reg_639_pp0_iter1_reg = ap_const_lv2_1));
    end process;


    ap_condition_374_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln49_reg_635_pp0_iter1_reg, select_ln49_3_reg_639_pp0_iter1_reg)
    begin
                ap_condition_374 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln49_3_reg_639_pp0_iter1_reg = ap_const_lv2_0) and (select_ln49_reg_635_pp0_iter1_reg = ap_const_lv2_1));
    end process;


    ap_condition_377_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln49_reg_635_pp0_iter1_reg, select_ln49_3_reg_639_pp0_iter1_reg)
    begin
                ap_condition_377 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln49_3_reg_639_pp0_iter1_reg = ap_const_lv2_0) and (select_ln49_reg_635_pp0_iter1_reg = ap_const_lv2_0));
    end process;


    ap_condition_380_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln49_reg_635_pp0_iter1_reg, select_ln49_3_reg_639_pp0_iter1_reg)
    begin
                ap_condition_380 <= (not((select_ln49_reg_635_pp0_iter1_reg = ap_const_lv2_0)) and not((select_ln49_reg_635_pp0_iter1_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln49_3_reg_639_pp0_iter1_reg = ap_const_lv2_0));
    end process;


    ap_condition_384_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln49_reg_635_pp0_iter1_reg, select_ln49_3_reg_639_pp0_iter1_reg)
    begin
                ap_condition_384 <= (not((select_ln49_3_reg_639_pp0_iter1_reg = ap_const_lv2_0)) and not((select_ln49_3_reg_639_pp0_iter1_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln49_reg_635_pp0_iter1_reg = ap_const_lv2_1));
    end process;


    ap_condition_387_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln49_reg_635_pp0_iter1_reg, select_ln49_3_reg_639_pp0_iter1_reg)
    begin
                ap_condition_387 <= (not((select_ln49_3_reg_639_pp0_iter1_reg = ap_const_lv2_0)) and not((select_ln49_3_reg_639_pp0_iter1_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln49_reg_635_pp0_iter1_reg = ap_const_lv2_0));
    end process;


    ap_condition_392_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln49_reg_635_pp0_iter1_reg, select_ln49_3_reg_639_pp0_iter1_reg)
    begin
                ap_condition_392 <= (not((select_ln49_3_reg_639_pp0_iter1_reg = ap_const_lv2_0)) and not((select_ln49_reg_635_pp0_iter1_reg = ap_const_lv2_0)) and not((select_ln49_reg_635_pp0_iter1_reg = ap_const_lv2_1)) and not((select_ln49_3_reg_639_pp0_iter1_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_condition_395_assign_proc : process(ap_enable_reg_pp0_iter2, select_ln49_reg_635_pp0_iter1_reg, select_ln49_3_reg_639_pp0_iter1_reg)
    begin
                ap_condition_395 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (select_ln49_3_reg_639_pp0_iter1_reg = ap_const_lv2_1) and (select_ln49_reg_635_pp0_iter1_reg = ap_const_lv2_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln49_fu_341_p2)
    begin
        if (((icmp_ln49_fu_341_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten27_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten27_fu_96)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten27_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_indvar_flatten27_load <= indvar_flatten27_fu_96;
        end if; 
    end process;


    ap_sig_allocacmp_wi_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, wi_fu_92)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_wi_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_wi_load <= wi_fu_92;
        end if; 
    end process;


    ap_sig_allocacmp_wj_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, wj_fu_88, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_wj_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_wj_load <= wj_fu_88;
        end if; 
    end process;

    icmp_ln49_fu_341_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten27_load = ap_const_lv4_9) else "0";
    icmp_ln50_fu_365_p2 <= "1" when (ap_sig_allocacmp_wj_load = ap_const_lv2_3) else "0";
    mem_1_0_address0 <= zext_ln52_7_fu_461_p1(10 - 1 downto 0);

    mem_1_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            mem_1_0_ce0 <= ap_const_logic_1;
        else 
            mem_1_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    p_out <= empty_136_fu_132;
    p_out1 <= empty_135_fu_128;

    p_out1_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_631)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_631 = ap_const_lv1_1))) then 
            p_out1_ap_vld <= ap_const_logic_1;
        else 
            p_out1_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out2 <= empty_134_fu_124;

    p_out2_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_631)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_631 = ap_const_lv1_1))) then 
            p_out2_ap_vld <= ap_const_logic_1;
        else 
            p_out2_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out3 <= empty_133_fu_120;

    p_out3_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_631)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_631 = ap_const_lv1_1))) then 
            p_out3_ap_vld <= ap_const_logic_1;
        else 
            p_out3_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out4 <= empty_132_fu_116;

    p_out4_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_631)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_631 = ap_const_lv1_1))) then 
            p_out4_ap_vld <= ap_const_logic_1;
        else 
            p_out4_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out5 <= empty_131_fu_112;

    p_out5_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_631)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_631 = ap_const_lv1_1))) then 
            p_out5_ap_vld <= ap_const_logic_1;
        else 
            p_out5_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out6 <= empty_130_fu_108;

    p_out6_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_631)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_631 = ap_const_lv1_1))) then 
            p_out6_ap_vld <= ap_const_logic_1;
        else 
            p_out6_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out7 <= empty_129_fu_104;

    p_out7_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_631)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_631 = ap_const_lv1_1))) then 
            p_out7_ap_vld <= ap_const_logic_1;
        else 
            p_out7_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    p_out8 <= empty_fu_100;

    p_out8_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_631)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_631 = ap_const_lv1_1))) then 
            p_out8_ap_vld <= ap_const_logic_1;
        else 
            p_out8_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, icmp_ln49_reg_631)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln49_reg_631 = ap_const_lv1_1))) then 
            p_out_ap_vld <= ap_const_logic_1;
        else 
            p_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln49_3_fu_379_p3 <= 
        add_ln49_fu_359_p2 when (icmp_ln50_fu_365_p2(0) = '1') else 
        ap_sig_allocacmp_wi_load;
    select_ln49_fu_371_p3 <= 
        ap_const_lv2_0 when (icmp_ln50_fu_365_p2(0) = '1') else 
        ap_sig_allocacmp_wj_load;
    sub_ln52_fu_446_p2 <= std_logic_vector(unsigned(tmp_s_fu_428_p3) - unsigned(zext_ln52_fu_442_p1));
    tmp_26_fu_435_p3 <= (add_ln49_5_reg_643 & ap_const_lv2_0);
    tmp_s_fu_428_p3 <= (add_ln49_5_reg_643 & ap_const_lv5_0);
    zext_ln49_fu_387_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln49_3_fu_379_p3),5));
    zext_ln50_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln49_fu_371_p3),5));
    zext_ln52_6_fu_452_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln52_reg_649),10));
    zext_ln52_7_fu_461_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln52_5_fu_455_p2),64));
    zext_ln52_fu_442_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_26_fu_435_p3),10));
end behav;
