// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module HW_accel_maxPool_4_24_12_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        ifmap_0_address0,
        ifmap_0_ce0,
        ifmap_0_q0,
        ifmap_0_address1,
        ifmap_0_ce1,
        ifmap_0_q1,
        ifmap_1_address0,
        ifmap_1_ce0,
        ifmap_1_q0,
        ifmap_1_address1,
        ifmap_1_ce1,
        ifmap_1_q1,
        ofmap_address0,
        ofmap_ce0,
        ofmap_we0,
        ofmap_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [10:0] ifmap_0_address0;
output   ifmap_0_ce0;
input  [31:0] ifmap_0_q0;
output  [10:0] ifmap_0_address1;
output   ifmap_0_ce1;
input  [31:0] ifmap_0_q1;
output  [10:0] ifmap_1_address0;
output   ifmap_1_ce0;
input  [31:0] ifmap_1_q0;
output  [10:0] ifmap_1_address1;
output   ifmap_1_ce1;
input  [31:0] ifmap_1_q1;
output  [9:0] ofmap_address0;
output   ofmap_ce0;
output   ofmap_we0;
output  [31:0] ofmap_d0;

reg ap_idle;
reg ifmap_0_ce0;
reg ifmap_0_ce1;
reg ifmap_1_ce0;
reg ifmap_1_ce1;
reg ofmap_ce0;
reg ofmap_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln170_fu_211_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] icmp_ln170_reg_939;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln171_fu_226_p2;
reg   [0:0] icmp_ln171_reg_943;
wire   [6:0] trunc_ln174_fu_433_p1;
reg   [6:0] trunc_ln174_reg_953;
wire   [8:0] trunc_ln174_1_fu_437_p1;
reg   [8:0] trunc_ln174_1_reg_958;
wire   [6:0] trunc_ln175_fu_465_p1;
reg   [6:0] trunc_ln175_reg_963;
wire   [8:0] trunc_ln175_1_fu_469_p1;
reg   [8:0] trunc_ln175_1_reg_968;
wire   [5:0] trunc_ln177_fu_501_p1;
reg   [5:0] trunc_ln177_reg_973;
wire   [7:0] trunc_ln177_1_fu_505_p1;
reg   [7:0] trunc_ln177_1_reg_978;
reg   [3:0] lshr_ln_reg_983;
wire   [9:0] add_ln177_1_fu_630_p2;
reg   [9:0] add_ln177_1_reg_1009;
reg   [9:0] add_ln177_1_reg_1009_pp0_iter3_reg;
reg   [9:0] add_ln177_1_reg_1009_pp0_iter4_reg;
reg   [9:0] add_ln177_1_reg_1009_pp0_iter5_reg;
reg   [9:0] add_ln177_1_reg_1009_pp0_iter6_reg;
reg   [9:0] add_ln177_1_reg_1009_pp0_iter7_reg;
reg   [31:0] ifmap_0_load_reg_1014;
reg   [31:0] ifmap_0_load_reg_1014_pp0_iter4_reg;
reg   [31:0] ifmap_1_load_reg_1021;
reg   [31:0] ifmap_1_load_reg_1021_pp0_iter4_reg;
reg   [31:0] ifmap_0_load_1_reg_1028;
reg   [31:0] ifmap_0_load_1_reg_1028_pp0_iter4_reg;
reg   [31:0] ifmap_1_load_1_reg_1035;
reg   [31:0] ifmap_1_load_1_reg_1035_pp0_iter4_reg;
wire   [31:0] max_0_fu_718_p3;
reg   [31:0] max_0_reg_1042;
reg   [31:0] max_0_reg_1042_pp0_iter6_reg;
wire   [31:0] max_1_fu_806_p3;
reg   [31:0] max_1_reg_1049;
reg   [31:0] max_1_reg_1049_pp0_iter6_reg;
wire   [31:0] select_ln177_fu_894_p3;
reg   [31:0] select_ln177_reg_1056;
reg    ap_condition_exit_pp0_iter1_stage0;
wire   [63:0] zext_ln174_5_fu_612_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln175_1_fu_624_p1;
wire   [63:0] zext_ln177_3_fu_900_p1;
reg   [4:0] ow_fu_88;
wire   [4:0] add_ln172_fu_519_p2;
wire    ap_loop_init;
reg    ap_loop_init_pp0_iter1_reg;
reg   [4:0] ap_sig_allocacmp_ow_load;
reg   [4:0] oh_fu_92;
wire   [4:0] select_ln171_1_fu_415_p3;
reg   [4:0] ap_sig_allocacmp_oh_1;
reg   [7:0] indvar_flatten_fu_96;
wire   [7:0] select_ln171_4_fu_238_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [2:0] och_fu_100;
wire   [2:0] select_ln170_2_fu_301_p3;
reg   [2:0] ap_sig_allocacmp_och_load;
reg   [9:0] indvar_flatten24_fu_104;
wire   [9:0] add_ln170_1_fu_217_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten24_load;
wire   [7:0] add_ln171_1_fu_232_p2;
wire   [2:0] add_ln170_fu_281_p2;
wire   [7:0] tmp_s_fu_308_p3;
wire   [5:0] tmp_10_fu_320_p3;
wire   [8:0] zext_ln174_fu_316_p1;
wire   [8:0] zext_ln174_1_fu_328_p1;
wire   [8:0] sub_ln174_fu_332_p2;
wire   [6:0] tmp_11_fu_342_p3;
wire   [4:0] tmp_12_fu_354_p3;
wire   [7:0] zext_ln177_fu_350_p1;
wire   [7:0] zext_ln177_1_fu_362_p1;
wire   [7:0] sub_ln177_fu_366_p2;
wire   [4:0] empty_fu_259_p2;
wire   [3:0] tmp_9_fu_265_p4;
wire   [0:0] icmp_ln172_fu_390_p2;
wire   [4:0] select_ln170_fu_287_p3;
wire   [0:0] or_ln170_fu_396_p2;
wire   [4:0] select_ln170_1_fu_294_p3;
wire   [4:0] add_ln171_fu_401_p2;
wire  signed [9:0] sext_ln177_fu_338_p1;
wire   [9:0] zext_ln174_2_fu_423_p1;
wire   [9:0] add_ln174_fu_427_p2;
wire   [4:0] select_ln170_3_fu_376_p3;
wire   [4:0] p_mid1_fu_441_p2;
wire   [4:0] select_ln171_2_fu_447_p3;
wire   [9:0] zext_ln175_fu_455_p1;
wire   [9:0] add_ln175_fu_459_p2;
wire   [3:0] select_ln170_4_fu_383_p3;
wire   [3:0] p_mid_fu_473_p4;
wire   [3:0] select_ln171_3_fu_483_p3;
wire  signed [8:0] sext_ln170_fu_372_p1;
wire   [8:0] zext_ln177_2_fu_491_p1;
wire   [8:0] add_ln177_fu_495_p2;
wire   [4:0] select_ln171_fu_407_p3;
wire   [10:0] p_shl4_fu_540_p3;
wire   [10:0] p_shl5_fu_547_p3;
wire   [10:0] p_shl2_fu_560_p3;
wire   [10:0] p_shl3_fu_567_p3;
wire   [9:0] p_shl_fu_580_p3;
wire   [9:0] p_shl1_fu_587_p3;
wire   [10:0] sub_ln174_1_fu_554_p2;
wire   [10:0] zext_ln174_4_fu_603_p1;
wire   [10:0] add_ln174_1_fu_606_p2;
wire   [10:0] sub_ln175_fu_574_p2;
wire   [10:0] add_ln175_1_fu_618_p2;
wire   [9:0] sub_ln177_1_fu_594_p2;
wire   [9:0] zext_ln174_3_fu_600_p1;
wire   [31:0] bitcast_ln174_fu_636_p1;
wire   [31:0] bitcast_ln174_1_fu_653_p1;
wire   [7:0] tmp_fu_639_p4;
wire   [22:0] trunc_ln174_2_fu_649_p1;
wire   [0:0] icmp_ln174_1_fu_676_p2;
wire   [0:0] icmp_ln174_fu_670_p2;
wire   [7:0] tmp_1_fu_656_p4;
wire   [22:0] trunc_ln174_3_fu_666_p1;
wire   [0:0] icmp_ln174_3_fu_694_p2;
wire   [0:0] icmp_ln174_2_fu_688_p2;
wire   [0:0] or_ln174_fu_682_p2;
wire   [0:0] or_ln174_1_fu_700_p2;
wire   [0:0] and_ln174_fu_706_p2;
wire   [0:0] grp_fu_171_p2;
wire   [0:0] and_ln174_1_fu_712_p2;
wire   [31:0] bitcast_ln175_fu_724_p1;
wire   [31:0] bitcast_ln175_1_fu_741_p1;
wire   [7:0] tmp_3_fu_727_p4;
wire   [22:0] trunc_ln175_2_fu_737_p1;
wire   [0:0] icmp_ln175_1_fu_764_p2;
wire   [0:0] icmp_ln175_fu_758_p2;
wire   [7:0] tmp_4_fu_744_p4;
wire   [22:0] trunc_ln175_3_fu_754_p1;
wire   [0:0] icmp_ln175_3_fu_782_p2;
wire   [0:0] icmp_ln175_2_fu_776_p2;
wire   [0:0] or_ln175_fu_770_p2;
wire   [0:0] or_ln175_1_fu_788_p2;
wire   [0:0] and_ln175_fu_794_p2;
wire   [0:0] grp_fu_175_p2;
wire   [0:0] and_ln175_1_fu_800_p2;
wire   [31:0] bitcast_ln177_fu_812_p1;
wire   [31:0] bitcast_ln177_1_fu_829_p1;
wire   [7:0] tmp_6_fu_815_p4;
wire   [22:0] trunc_ln177_2_fu_825_p1;
wire   [0:0] icmp_ln177_1_fu_852_p2;
wire   [0:0] icmp_ln177_fu_846_p2;
wire   [7:0] tmp_7_fu_832_p4;
wire   [22:0] trunc_ln177_3_fu_842_p1;
wire   [0:0] icmp_ln177_3_fu_870_p2;
wire   [0:0] icmp_ln177_2_fu_864_p2;
wire   [0:0] or_ln177_fu_858_p2;
wire   [0:0] or_ln177_1_fu_876_p2;
wire   [0:0] and_ln177_fu_882_p2;
wire   [0:0] grp_fu_179_p2;
wire   [0:0] and_ln177_1_fu_888_p2;
reg    grp_fu_171_ce;
reg    ap_block_pp0_stage0_00001;
reg    grp_fu_175_ce;
reg    grp_fu_179_ce;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_221;
reg    ap_condition_202;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_done_reg = 1'b0;
end

HW_accel_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U414(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ifmap_0_load_reg_1014),
    .din1(ifmap_1_load_reg_1021),
    .ce(grp_fu_171_ce),
    .opcode(5'd2),
    .dout(grp_fu_171_p2)
);

HW_accel_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U415(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ifmap_0_load_1_reg_1028),
    .din1(ifmap_1_load_1_reg_1035),
    .ce(grp_fu_175_ce),
    .opcode(5'd2),
    .dout(grp_fu_175_p2)
);

HW_accel_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U416(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(max_0_reg_1042),
    .din1(max_1_reg_1049),
    .ce(grp_fu_179_ce),
    .opcode(5'd2),
    .dout(grp_fu_179_p2)
);

HW_accel_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_221)) begin
        if ((icmp_ln170_fu_211_p2 == 1'd0)) begin
            indvar_flatten24_fu_104 <= add_ln170_1_fu_217_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten24_fu_104 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_221)) begin
        if ((icmp_ln170_fu_211_p2 == 1'd0)) begin
            indvar_flatten_fu_96 <= select_ln171_4_fu_238_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_96 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_202)) begin
        if ((icmp_ln170_reg_939 == 1'd0)) begin
            och_fu_100 <= select_ln170_2_fu_301_p3;
        end else if ((ap_loop_init_pp0_iter1_reg == 1'b1)) begin
            och_fu_100 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_202)) begin
        if ((icmp_ln170_reg_939 == 1'd0)) begin
            oh_fu_92 <= select_ln171_1_fu_415_p3;
        end else if ((ap_loop_init_pp0_iter1_reg == 1'b1)) begin
            oh_fu_92 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_202)) begin
        if ((icmp_ln170_reg_939 == 1'd0)) begin
            ow_fu_88 <= add_ln172_fu_519_p2;
        end else if ((ap_loop_init_pp0_iter1_reg == 1'b1)) begin
            ow_fu_88 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln177_1_reg_1009 <= add_ln177_1_fu_630_p2;
        add_ln177_1_reg_1009_pp0_iter3_reg <= add_ln177_1_reg_1009;
        add_ln177_1_reg_1009_pp0_iter4_reg <= add_ln177_1_reg_1009_pp0_iter3_reg;
        add_ln177_1_reg_1009_pp0_iter5_reg <= add_ln177_1_reg_1009_pp0_iter4_reg;
        add_ln177_1_reg_1009_pp0_iter6_reg <= add_ln177_1_reg_1009_pp0_iter5_reg;
        add_ln177_1_reg_1009_pp0_iter7_reg <= add_ln177_1_reg_1009_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ifmap_0_load_1_reg_1028_pp0_iter4_reg <= ifmap_0_load_1_reg_1028;
        ifmap_0_load_reg_1014_pp0_iter4_reg <= ifmap_0_load_reg_1014;
        ifmap_1_load_1_reg_1035_pp0_iter4_reg <= ifmap_1_load_1_reg_1035;
        ifmap_1_load_reg_1021_pp0_iter4_reg <= ifmap_1_load_reg_1021;
        max_0_reg_1042 <= max_0_fu_718_p3;
        max_0_reg_1042_pp0_iter6_reg <= max_0_reg_1042;
        max_1_reg_1049 <= max_1_fu_806_p3;
        max_1_reg_1049_pp0_iter6_reg <= max_1_reg_1049;
        select_ln177_reg_1056 <= select_ln177_fu_894_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        ap_loop_init_pp0_iter1_reg <= ap_loop_init;
        icmp_ln170_reg_939 <= icmp_ln170_fu_211_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln170_fu_211_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln171_reg_943 <= icmp_ln171_fu_226_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ifmap_0_load_1_reg_1028 <= ifmap_0_q0;
        ifmap_0_load_reg_1014 <= ifmap_0_q1;
        ifmap_1_load_1_reg_1035 <= ifmap_1_q0;
        ifmap_1_load_reg_1021 <= ifmap_1_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln170_reg_939 == 1'd0))) begin
        lshr_ln_reg_983 <= {{select_ln171_fu_407_p3[4:1]}};
        trunc_ln174_1_reg_958 <= trunc_ln174_1_fu_437_p1;
        trunc_ln174_reg_953 <= trunc_ln174_fu_433_p1;
        trunc_ln175_1_reg_968[8 : 1] <= trunc_ln175_1_fu_469_p1[8 : 1];
        trunc_ln175_reg_963[6 : 1] <= trunc_ln175_fu_465_p1[6 : 1];
        trunc_ln177_1_reg_978 <= trunc_ln177_1_fu_505_p1;
        trunc_ln177_reg_973 <= trunc_ln177_fu_501_p1;
    end
end

always @ (*) begin
    if (((icmp_ln170_fu_211_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln170_reg_939 == 1'd1))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter7_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten24_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten24_load = indvar_flatten24_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_96;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        ap_sig_allocacmp_och_load = 3'd0;
    end else begin
        ap_sig_allocacmp_och_load = och_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        ap_sig_allocacmp_oh_1 = 5'd0;
    end else begin
        ap_sig_allocacmp_oh_1 = oh_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init_pp0_iter1_reg == 1'b1))) begin
        ap_sig_allocacmp_ow_load = 5'd0;
    end else begin
        ap_sig_allocacmp_ow_load = ow_fu_88;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_171_ce = 1'b1;
    end else begin
        grp_fu_171_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_175_ce = 1'b1;
    end else begin
        grp_fu_175_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_179_ce = 1'b1;
    end else begin
        grp_fu_179_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ifmap_0_ce0 = 1'b1;
    end else begin
        ifmap_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ifmap_0_ce1 = 1'b1;
    end else begin
        ifmap_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ifmap_1_ce0 = 1'b1;
    end else begin
        ifmap_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ifmap_1_ce1 = 1'b1;
    end else begin
        ifmap_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        ofmap_ce0 = 1'b1;
    end else begin
        ofmap_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        ofmap_we0 = 1'b1;
    end else begin
        ofmap_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln170_1_fu_217_p2 = (ap_sig_allocacmp_indvar_flatten24_load + 10'd1);

assign add_ln170_fu_281_p2 = (ap_sig_allocacmp_och_load + 3'd1);

assign add_ln171_1_fu_232_p2 = (ap_sig_allocacmp_indvar_flatten_load + 8'd1);

assign add_ln171_fu_401_p2 = (select_ln170_fu_287_p3 + 5'd2);

assign add_ln172_fu_519_p2 = (select_ln171_fu_407_p3 + 5'd2);

assign add_ln174_1_fu_606_p2 = (sub_ln174_1_fu_554_p2 + zext_ln174_4_fu_603_p1);

assign add_ln174_fu_427_p2 = ($signed(sext_ln177_fu_338_p1) + $signed(zext_ln174_2_fu_423_p1));

assign add_ln175_1_fu_618_p2 = (sub_ln175_fu_574_p2 + zext_ln174_4_fu_603_p1);

assign add_ln175_fu_459_p2 = ($signed(sext_ln177_fu_338_p1) + $signed(zext_ln175_fu_455_p1));

assign add_ln177_1_fu_630_p2 = (sub_ln177_1_fu_594_p2 + zext_ln174_3_fu_600_p1);

assign add_ln177_fu_495_p2 = ($signed(sext_ln170_fu_372_p1) + $signed(zext_ln177_2_fu_491_p1));

assign and_ln174_1_fu_712_p2 = (grp_fu_171_p2 & and_ln174_fu_706_p2);

assign and_ln174_fu_706_p2 = (or_ln174_fu_682_p2 & or_ln174_1_fu_700_p2);

assign and_ln175_1_fu_800_p2 = (grp_fu_175_p2 & and_ln175_fu_794_p2);

assign and_ln175_fu_794_p2 = (or_ln175_fu_770_p2 & or_ln175_1_fu_788_p2);

assign and_ln177_1_fu_888_p2 = (grp_fu_179_p2 & and_ln177_fu_882_p2);

assign and_ln177_fu_882_p2 = (or_ln177_fu_858_p2 & or_ln177_1_fu_876_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_00001 = ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_202 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_221 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln174_1_fu_653_p1 = ifmap_1_load_reg_1021_pp0_iter4_reg;

assign bitcast_ln174_fu_636_p1 = ifmap_0_load_reg_1014_pp0_iter4_reg;

assign bitcast_ln175_1_fu_741_p1 = ifmap_1_load_1_reg_1035_pp0_iter4_reg;

assign bitcast_ln175_fu_724_p1 = ifmap_0_load_1_reg_1028_pp0_iter4_reg;

assign bitcast_ln177_1_fu_829_p1 = max_1_reg_1049_pp0_iter6_reg;

assign bitcast_ln177_fu_812_p1 = max_0_reg_1042_pp0_iter6_reg;

assign empty_fu_259_p2 = (ap_sig_allocacmp_oh_1 | 5'd1);

assign icmp_ln170_fu_211_p2 = ((ap_sig_allocacmp_indvar_flatten24_load == 10'd576) ? 1'b1 : 1'b0);

assign icmp_ln171_fu_226_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 8'd144) ? 1'b1 : 1'b0);

assign icmp_ln172_fu_390_p2 = ((ap_sig_allocacmp_ow_load < 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln174_1_fu_676_p2 = ((trunc_ln174_2_fu_649_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln174_2_fu_688_p2 = ((tmp_1_fu_656_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln174_3_fu_694_p2 = ((trunc_ln174_3_fu_666_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln174_fu_670_p2 = ((tmp_fu_639_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln175_1_fu_764_p2 = ((trunc_ln175_2_fu_737_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln175_2_fu_776_p2 = ((tmp_4_fu_744_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln175_3_fu_782_p2 = ((trunc_ln175_3_fu_754_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln175_fu_758_p2 = ((tmp_3_fu_727_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln177_1_fu_852_p2 = ((trunc_ln177_2_fu_825_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln177_2_fu_864_p2 = ((tmp_7_fu_832_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln177_3_fu_870_p2 = ((trunc_ln177_3_fu_842_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln177_fu_846_p2 = ((tmp_6_fu_815_p4 != 8'd255) ? 1'b1 : 1'b0);

assign ifmap_0_address0 = zext_ln175_1_fu_624_p1;

assign ifmap_0_address1 = zext_ln174_5_fu_612_p1;

assign ifmap_1_address0 = zext_ln175_1_fu_624_p1;

assign ifmap_1_address1 = zext_ln174_5_fu_612_p1;

assign max_0_fu_718_p3 = ((and_ln174_1_fu_712_p2[0:0] == 1'b1) ? ifmap_0_load_reg_1014_pp0_iter4_reg : ifmap_1_load_reg_1021_pp0_iter4_reg);

assign max_1_fu_806_p3 = ((and_ln175_1_fu_800_p2[0:0] == 1'b1) ? ifmap_0_load_1_reg_1028_pp0_iter4_reg : ifmap_1_load_1_reg_1035_pp0_iter4_reg);

assign ofmap_address0 = zext_ln177_3_fu_900_p1;

assign ofmap_d0 = select_ln177_reg_1056;

assign or_ln170_fu_396_p2 = (icmp_ln172_fu_390_p2 | icmp_ln171_reg_943);

assign or_ln174_1_fu_700_p2 = (icmp_ln174_3_fu_694_p2 | icmp_ln174_2_fu_688_p2);

assign or_ln174_fu_682_p2 = (icmp_ln174_fu_670_p2 | icmp_ln174_1_fu_676_p2);

assign or_ln175_1_fu_788_p2 = (icmp_ln175_3_fu_782_p2 | icmp_ln175_2_fu_776_p2);

assign or_ln175_fu_770_p2 = (icmp_ln175_fu_758_p2 | icmp_ln175_1_fu_764_p2);

assign or_ln177_1_fu_876_p2 = (icmp_ln177_3_fu_870_p2 | icmp_ln177_2_fu_864_p2);

assign or_ln177_fu_858_p2 = (icmp_ln177_fu_846_p2 | icmp_ln177_1_fu_852_p2);

assign p_mid1_fu_441_p2 = (5'd1 | add_ln171_fu_401_p2);

assign p_mid_fu_473_p4 = {{add_ln171_fu_401_p2[4:1]}};

assign p_shl1_fu_587_p3 = {{trunc_ln177_1_reg_978}, {2'd0}};

assign p_shl2_fu_560_p3 = {{trunc_ln175_reg_963}, {4'd0}};

assign p_shl3_fu_567_p3 = {{trunc_ln175_1_reg_968}, {2'd0}};

assign p_shl4_fu_540_p3 = {{trunc_ln174_reg_953}, {4'd0}};

assign p_shl5_fu_547_p3 = {{trunc_ln174_1_reg_958}, {2'd0}};

assign p_shl_fu_580_p3 = {{trunc_ln177_reg_973}, {4'd0}};

assign select_ln170_1_fu_294_p3 = ((icmp_ln171_reg_943[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_ow_load);

assign select_ln170_2_fu_301_p3 = ((icmp_ln171_reg_943[0:0] == 1'b1) ? add_ln170_fu_281_p2 : ap_sig_allocacmp_och_load);

assign select_ln170_3_fu_376_p3 = ((icmp_ln171_reg_943[0:0] == 1'b1) ? 5'd1 : empty_fu_259_p2);

assign select_ln170_4_fu_383_p3 = ((icmp_ln171_reg_943[0:0] == 1'b1) ? 4'd0 : tmp_9_fu_265_p4);

assign select_ln170_fu_287_p3 = ((icmp_ln171_reg_943[0:0] == 1'b1) ? 5'd0 : ap_sig_allocacmp_oh_1);

assign select_ln171_1_fu_415_p3 = ((or_ln170_fu_396_p2[0:0] == 1'b1) ? select_ln170_fu_287_p3 : add_ln171_fu_401_p2);

assign select_ln171_2_fu_447_p3 = ((or_ln170_fu_396_p2[0:0] == 1'b1) ? select_ln170_3_fu_376_p3 : p_mid1_fu_441_p2);

assign select_ln171_3_fu_483_p3 = ((or_ln170_fu_396_p2[0:0] == 1'b1) ? select_ln170_4_fu_383_p3 : p_mid_fu_473_p4);

assign select_ln171_4_fu_238_p3 = ((icmp_ln171_fu_226_p2[0:0] == 1'b1) ? 8'd1 : add_ln171_1_fu_232_p2);

assign select_ln171_fu_407_p3 = ((or_ln170_fu_396_p2[0:0] == 1'b1) ? select_ln170_1_fu_294_p3 : 5'd0);

assign select_ln177_fu_894_p3 = ((and_ln177_1_fu_888_p2[0:0] == 1'b1) ? max_0_reg_1042_pp0_iter6_reg : max_1_reg_1049_pp0_iter6_reg);

assign sext_ln170_fu_372_p1 = $signed(sub_ln177_fu_366_p2);

assign sext_ln177_fu_338_p1 = $signed(sub_ln174_fu_332_p2);

assign sub_ln174_1_fu_554_p2 = (p_shl4_fu_540_p3 - p_shl5_fu_547_p3);

assign sub_ln174_fu_332_p2 = (zext_ln174_fu_316_p1 - zext_ln174_1_fu_328_p1);

assign sub_ln175_fu_574_p2 = (p_shl2_fu_560_p3 - p_shl3_fu_567_p3);

assign sub_ln177_1_fu_594_p2 = (p_shl_fu_580_p3 - p_shl1_fu_587_p3);

assign sub_ln177_fu_366_p2 = (zext_ln177_fu_350_p1 - zext_ln177_1_fu_362_p1);

assign tmp_10_fu_320_p3 = {{select_ln170_2_fu_301_p3}, {3'd0}};

assign tmp_11_fu_342_p3 = {{select_ln170_2_fu_301_p3}, {4'd0}};

assign tmp_12_fu_354_p3 = {{select_ln170_2_fu_301_p3}, {2'd0}};

assign tmp_1_fu_656_p4 = {{bitcast_ln174_1_fu_653_p1[30:23]}};

assign tmp_3_fu_727_p4 = {{bitcast_ln175_fu_724_p1[30:23]}};

assign tmp_4_fu_744_p4 = {{bitcast_ln175_1_fu_741_p1[30:23]}};

assign tmp_6_fu_815_p4 = {{bitcast_ln177_fu_812_p1[30:23]}};

assign tmp_7_fu_832_p4 = {{bitcast_ln177_1_fu_829_p1[30:23]}};

assign tmp_9_fu_265_p4 = {{ap_sig_allocacmp_oh_1[4:1]}};

assign tmp_fu_639_p4 = {{bitcast_ln174_fu_636_p1[30:23]}};

assign tmp_s_fu_308_p3 = {{select_ln170_2_fu_301_p3}, {5'd0}};

assign trunc_ln174_1_fu_437_p1 = add_ln174_fu_427_p2[8:0];

assign trunc_ln174_2_fu_649_p1 = bitcast_ln174_fu_636_p1[22:0];

assign trunc_ln174_3_fu_666_p1 = bitcast_ln174_1_fu_653_p1[22:0];

assign trunc_ln174_fu_433_p1 = add_ln174_fu_427_p2[6:0];

assign trunc_ln175_1_fu_469_p1 = add_ln175_fu_459_p2[8:0];

assign trunc_ln175_2_fu_737_p1 = bitcast_ln175_fu_724_p1[22:0];

assign trunc_ln175_3_fu_754_p1 = bitcast_ln175_1_fu_741_p1[22:0];

assign trunc_ln175_fu_465_p1 = add_ln175_fu_459_p2[6:0];

assign trunc_ln177_1_fu_505_p1 = add_ln177_fu_495_p2[7:0];

assign trunc_ln177_2_fu_825_p1 = bitcast_ln177_fu_812_p1[22:0];

assign trunc_ln177_3_fu_842_p1 = bitcast_ln177_1_fu_829_p1[22:0];

assign trunc_ln177_fu_501_p1 = add_ln177_fu_495_p2[5:0];

assign zext_ln174_1_fu_328_p1 = tmp_10_fu_320_p3;

assign zext_ln174_2_fu_423_p1 = select_ln171_1_fu_415_p3;

assign zext_ln174_3_fu_600_p1 = lshr_ln_reg_983;

assign zext_ln174_4_fu_603_p1 = lshr_ln_reg_983;

assign zext_ln174_5_fu_612_p1 = add_ln174_1_fu_606_p2;

assign zext_ln174_fu_316_p1 = tmp_s_fu_308_p3;

assign zext_ln175_1_fu_624_p1 = add_ln175_1_fu_618_p2;

assign zext_ln175_fu_455_p1 = select_ln171_2_fu_447_p3;

assign zext_ln177_1_fu_362_p1 = tmp_12_fu_354_p3;

assign zext_ln177_2_fu_491_p1 = select_ln171_3_fu_483_p3;

assign zext_ln177_3_fu_900_p1 = add_ln177_1_reg_1009_pp0_iter7_reg;

assign zext_ln177_fu_350_p1 = tmp_11_fu_342_p3;

always @ (posedge ap_clk) begin
    trunc_ln175_reg_963[0] <= 1'b1;
    trunc_ln175_1_reg_968[0] <= 1'b1;
end

endmodule //HW_accel_maxPool_4_24_12_s
