// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module HW_accel_FC_layer_100_16_true_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);

parameter    ap_ST_fsm_state1 = 15'd1;
parameter    ap_ST_fsm_state2 = 15'd2;
parameter    ap_ST_fsm_state3 = 15'd4;
parameter    ap_ST_fsm_state4 = 15'd8;
parameter    ap_ST_fsm_state5 = 15'd16;
parameter    ap_ST_fsm_state6 = 15'd32;
parameter    ap_ST_fsm_state7 = 15'd64;
parameter    ap_ST_fsm_state8 = 15'd128;
parameter    ap_ST_fsm_state9 = 15'd256;
parameter    ap_ST_fsm_state10 = 15'd512;
parameter    ap_ST_fsm_state11 = 15'd1024;
parameter    ap_ST_fsm_state12 = 15'd2048;
parameter    ap_ST_fsm_state13 = 15'd4096;
parameter    ap_ST_fsm_state14 = 15'd8192;
parameter    ap_ST_fsm_state15 = 15'd16384;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;
output  [31:0] ap_return_6;
output  [31:0] ap_return_7;
output  [31:0] ap_return_8;
output  [31:0] ap_return_9;
output  [31:0] ap_return_10;
output  [31:0] ap_return_11;
output  [31:0] ap_return_12;
output  [31:0] ap_return_13;
output  [31:0] ap_return_14;
output  [31:0] ap_return_15;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_ce0;

(* fsm_encoding = "none" *) reg   [14:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] fc1_bias_address0;
reg    fc1_bias_ce0;
wire   [31:0] fc1_bias_q0;
wire   [3:0] fc1_bias_address1;
reg    fc1_bias_ce1;
wire   [31:0] fc1_bias_q1;
wire   [3:0] fc1_bias_address2;
reg    fc1_bias_ce2;
wire   [31:0] fc1_bias_q2;
wire   [3:0] fc1_bias_address3;
reg    fc1_bias_ce3;
wire   [31:0] fc1_bias_q3;
wire   [3:0] fc1_bias_address4;
reg    fc1_bias_ce4;
wire   [31:0] fc1_bias_q4;
wire   [3:0] fc1_bias_address5;
reg    fc1_bias_ce5;
wire   [31:0] fc1_bias_q5;
wire   [3:0] fc1_bias_address6;
reg    fc1_bias_ce6;
wire   [31:0] fc1_bias_q6;
wire   [3:0] fc1_bias_address7;
reg    fc1_bias_ce7;
wire   [31:0] fc1_bias_q7;
wire   [10:0] fc1_weight_address0;
reg    fc1_weight_ce0;
wire   [31:0] fc1_weight_q0;
wire   [10:0] fc1_weight_address1;
reg    fc1_weight_ce1;
wire   [31:0] fc1_weight_q1;
wire   [10:0] fc1_weight_address2;
reg    fc1_weight_ce2;
wire   [31:0] fc1_weight_q2;
wire   [10:0] fc1_weight_address3;
reg    fc1_weight_ce3;
wire   [31:0] fc1_weight_q3;
wire   [10:0] fc1_weight_address4;
reg    fc1_weight_ce4;
wire   [31:0] fc1_weight_q4;
wire   [10:0] fc1_weight_address5;
reg    fc1_weight_ce5;
wire   [31:0] fc1_weight_q5;
wire   [10:0] fc1_weight_address6;
reg    fc1_weight_ce6;
wire   [31:0] fc1_weight_q6;
wire   [10:0] fc1_weight_address7;
reg    fc1_weight_ce7;
wire   [31:0] fc1_weight_q7;
wire   [1:0] add_ln213_fu_586_p2;
reg   [1:0] add_ln213_reg_1796;
wire    ap_CS_fsm_state2;
wire   [3:0] shl_ln_fu_596_p3;
reg   [3:0] shl_ln_reg_1801;
wire   [0:0] icmp_ln213_fu_580_p2;
wire   [3:0] empty_220_fu_609_p2;
reg   [3:0] empty_220_reg_1812;
wire   [3:0] empty_221_fu_620_p2;
reg   [3:0] empty_221_reg_1822;
wire   [3:0] empty_222_fu_631_p2;
reg   [3:0] empty_222_reg_1832;
wire   [3:0] empty_223_fu_642_p2;
reg   [3:0] empty_223_reg_1842;
wire   [3:0] empty_224_fu_653_p2;
reg   [3:0] empty_224_reg_1852;
wire   [3:0] empty_225_fu_664_p2;
reg   [3:0] empty_225_reg_1862;
wire   [3:0] empty_226_fu_675_p2;
reg   [3:0] empty_226_reg_1872;
wire   [10:0] mul_ln230_fu_785_p2;
reg   [10:0] mul_ln230_reg_1882;
wire    ap_CS_fsm_state3;
wire   [10:0] mul_ln230_1_fu_794_p2;
reg   [10:0] mul_ln230_1_reg_1887;
wire   [10:0] mul_ln230_2_fu_803_p2;
reg   [10:0] mul_ln230_2_reg_1892;
wire   [10:0] mul_ln230_3_fu_812_p2;
reg   [10:0] mul_ln230_3_reg_1897;
wire   [10:0] mul_ln230_4_fu_821_p2;
reg   [10:0] mul_ln230_4_reg_1902;
wire   [10:0] mul_ln230_5_fu_830_p2;
reg   [10:0] mul_ln230_5_reg_1907;
wire   [10:0] mul_ln230_6_fu_839_p2;
reg   [10:0] mul_ln230_6_reg_1912;
wire   [10:0] mul_ln230_7_fu_848_p2;
reg   [10:0] mul_ln230_7_reg_1917;
reg   [31:0] fc1_bias_load_reg_1922;
reg   [31:0] fc1_bias_load_1_reg_1927;
reg   [31:0] fc1_bias_load_2_reg_1932;
reg   [31:0] fc1_bias_load_3_reg_1937;
reg   [31:0] fc1_bias_load_4_reg_1942;
reg   [31:0] fc1_bias_load_5_reg_1947;
reg   [31:0] fc1_bias_load_6_reg_1952;
reg   [31:0] fc1_bias_load_7_reg_1957;
wire    ap_CS_fsm_state4;
wire   [6:0] add_ln216_fu_949_p2;
reg   [6:0] add_ln216_reg_2010;
wire   [31:0] select_ln220_fu_961_p3;
reg   [31:0] select_ln220_reg_2015;
wire   [0:0] icmp_ln216_fu_943_p2;
wire   [31:0] select_ln220_5_fu_968_p3;
reg   [31:0] select_ln220_5_reg_2020;
wire   [31:0] select_ln220_6_fu_975_p3;
reg   [31:0] select_ln220_6_reg_2025;
wire   [31:0] select_ln220_7_fu_982_p3;
reg   [31:0] select_ln220_7_reg_2030;
wire   [31:0] select_ln220_8_fu_989_p3;
reg   [31:0] select_ln220_8_reg_2035;
wire   [31:0] select_ln220_9_fu_996_p3;
reg   [31:0] select_ln220_9_reg_2040;
wire   [31:0] select_ln220_10_fu_1003_p3;
reg   [31:0] select_ln220_10_reg_2045;
wire   [31:0] select_ln220_11_fu_1010_p3;
reg   [31:0] select_ln220_11_reg_2050;
reg   [31:0] add32_lcssa10_load_reg_2055;
reg   [31:0] add32_1_lcssa12_load_reg_2062;
reg   [31:0] add32_2_lcssa14_load_reg_2069;
reg   [31:0] add32_3_lcssa16_load_reg_2076;
reg   [31:0] add32_4_lcssa18_load_reg_2083;
reg   [31:0] add32_5_lcssa20_load_reg_2090;
reg   [31:0] add32_6_lcssa22_load_reg_2097;
reg   [31:0] add32_7_lcssa24_load_reg_2104;
wire   [0:0] icmp_ln237_fu_1017_p2;
reg   [0:0] icmp_ln237_reg_2111;
reg   [31:0] ip_reg_2131;
wire    ap_CS_fsm_state5;
reg   [31:0] fc1_weight_load_reg_2143;
reg   [31:0] fc1_weight_load_1_reg_2148;
reg   [31:0] fc1_weight_load_2_reg_2153;
reg   [31:0] fc1_weight_load_3_reg_2158;
reg   [31:0] fc1_weight_load_4_reg_2163;
reg   [31:0] fc1_weight_load_5_reg_2168;
reg   [31:0] fc1_weight_load_6_reg_2173;
reg   [31:0] fc1_weight_load_7_reg_2178;
wire   [31:0] grp_fu_420_p2;
reg   [31:0] mul_reg_2183;
wire    ap_CS_fsm_state9;
wire   [31:0] grp_fu_424_p2;
reg   [31:0] mul31_1_reg_2188;
wire   [31:0] grp_fu_428_p2;
reg   [31:0] mul31_2_reg_2193;
wire   [31:0] grp_fu_432_p2;
reg   [31:0] mul31_3_reg_2198;
wire   [31:0] grp_fu_436_p2;
reg   [31:0] mul31_4_reg_2203;
wire   [31:0] grp_fu_440_p2;
reg   [31:0] mul31_5_reg_2208;
wire   [31:0] grp_fu_444_p2;
reg   [31:0] mul31_6_reg_2213;
wire   [31:0] grp_fu_448_p2;
reg   [31:0] mul31_7_reg_2218;
reg   [6:0] i_index_reg_377;
wire    ap_CS_fsm_state14;
wire   [63:0] trunc_ln237_cast_fu_604_p1;
wire   [63:0] p_cast_fu_615_p1;
wire   [63:0] p_cast1_fu_626_p1;
wire   [63:0] p_cast2_fu_637_p1;
wire   [63:0] p_cast3_fu_648_p1;
wire   [63:0] p_cast4_fu_659_p1;
wire   [63:0] p_cast5_fu_670_p1;
wire   [63:0] p_cast6_fu_681_p1;
wire   [63:0] zext_ln230_14_fu_868_p1;
wire   [63:0] zext_ln230_15_fu_878_p1;
wire   [63:0] zext_ln230_16_fu_888_p1;
wire   [63:0] zext_ln230_17_fu_898_p1;
wire   [63:0] zext_ln230_18_fu_908_p1;
wire   [63:0] zext_ln230_19_fu_918_p1;
wire   [63:0] zext_ln230_20_fu_928_p1;
wire   [63:0] zext_ln230_21_fu_938_p1;
wire   [63:0] zext_ln216_fu_854_p1;
reg   [1:0] turn_fu_70;
reg   [31:0] output_15_016_fu_74;
wire   [31:0] select_ln237_15_fu_1555_p3;
wire    ap_CS_fsm_state15;
reg   [31:0] output_1445_017_fu_78;
wire   [31:0] select_ln237_14_fu_1548_p3;
reg   [31:0] output_0_018_fu_82;
wire   [31:0] select_ln237_13_fu_1541_p3;
reg   [31:0] output_13_019_fu_86;
wire   [31:0] select_ln237_12_fu_1534_p3;
reg   [31:0] output_12_020_fu_90;
wire   [31:0] select_ln237_11_fu_1527_p3;
reg   [31:0] output_1_021_fu_94;
wire   [31:0] select_ln237_10_fu_1520_p3;
reg   [31:0] output_11_022_fu_98;
wire   [31:0] select_ln237_9_fu_1513_p3;
reg   [31:0] output_10_023_fu_102;
wire   [31:0] select_ln237_8_fu_1506_p3;
reg   [31:0] output_2_024_fu_106;
wire   [31:0] select_ln237_7_fu_1499_p3;
reg   [31:0] output_9_025_fu_110;
wire   [31:0] select_ln237_6_fu_1492_p3;
reg   [31:0] output_8_026_fu_114;
wire   [31:0] select_ln237_5_fu_1485_p3;
reg   [31:0] output_3_027_fu_118;
wire   [31:0] select_ln237_4_fu_1478_p3;
reg   [31:0] output_7_028_fu_122;
wire   [31:0] select_ln237_3_fu_1471_p3;
reg   [31:0] output_6_029_fu_126;
wire   [31:0] select_ln237_2_fu_1464_p3;
reg   [31:0] output_4_030_fu_130;
wire   [31:0] select_ln237_1_fu_1457_p3;
reg   [31:0] output_5_031_fu_134;
wire   [31:0] select_ln237_fu_1450_p3;
reg   [31:0] add32_lcssa10_fu_138;
wire   [31:0] grp_fu_388_p2;
reg   [31:0] add32_1_lcssa12_fu_142;
wire   [31:0] grp_fu_392_p2;
reg   [31:0] add32_2_lcssa14_fu_146;
wire   [31:0] grp_fu_396_p2;
reg   [31:0] add32_3_lcssa16_fu_150;
wire   [31:0] grp_fu_400_p2;
reg   [31:0] add32_4_lcssa18_fu_154;
wire   [31:0] grp_fu_404_p2;
reg   [31:0] add32_5_lcssa20_fu_158;
wire   [31:0] grp_fu_408_p2;
reg   [31:0] add32_6_lcssa22_fu_162;
wire   [31:0] grp_fu_412_p2;
reg   [31:0] add32_7_lcssa24_fu_166;
wire   [31:0] grp_fu_416_p2;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state6;
wire   [0:0] trunc_ln237_fu_592_p1;
wire   [3:0] mul_ln230_fu_785_p0;
wire   [7:0] mul_ln230_fu_785_p1;
wire   [3:0] mul_ln230_1_fu_794_p0;
wire   [7:0] mul_ln230_1_fu_794_p1;
wire   [3:0] mul_ln230_2_fu_803_p0;
wire   [7:0] mul_ln230_2_fu_803_p1;
wire   [3:0] mul_ln230_3_fu_812_p0;
wire   [7:0] mul_ln230_3_fu_812_p1;
wire   [3:0] mul_ln230_4_fu_821_p0;
wire   [7:0] mul_ln230_4_fu_821_p1;
wire   [3:0] mul_ln230_5_fu_830_p0;
wire   [7:0] mul_ln230_5_fu_830_p1;
wire   [3:0] mul_ln230_6_fu_839_p0;
wire   [7:0] mul_ln230_6_fu_839_p1;
wire   [3:0] mul_ln230_7_fu_848_p0;
wire   [7:0] mul_ln230_7_fu_848_p1;
wire   [10:0] zext_ln230_13_fu_859_p1;
wire   [10:0] add_ln230_fu_863_p2;
wire   [10:0] add_ln230_5_fu_873_p2;
wire   [10:0] add_ln230_6_fu_883_p2;
wire   [10:0] add_ln230_7_fu_893_p2;
wire   [10:0] add_ln230_8_fu_903_p2;
wire   [10:0] add_ln230_9_fu_913_p2;
wire   [10:0] add_ln230_10_fu_923_p2;
wire   [10:0] add_ln230_11_fu_933_p2;
wire   [0:0] cmp9_fu_955_p2;
wire   [31:0] bitcast_ln61_fu_1066_p1;
wire   [7:0] tmp_fu_1069_p4;
wire   [22:0] trunc_ln61_fu_1079_p1;
wire   [0:0] icmp_ln61_4_fu_1089_p2;
wire   [0:0] icmp_ln61_fu_1083_p2;
wire   [0:0] or_ln61_fu_1095_p2;
wire   [0:0] grp_fu_452_p2;
wire   [0:0] and_ln61_fu_1101_p2;
wire   [31:0] bitcast_ln61_1_fu_1114_p1;
wire   [7:0] tmp_13_fu_1117_p4;
wire   [22:0] trunc_ln61_1_fu_1127_p1;
wire   [0:0] icmp_ln61_6_fu_1137_p2;
wire   [0:0] icmp_ln61_5_fu_1131_p2;
wire   [0:0] or_ln61_1_fu_1143_p2;
wire   [0:0] grp_fu_457_p2;
wire   [0:0] and_ln61_1_fu_1149_p2;
wire   [31:0] bitcast_ln61_2_fu_1162_p1;
wire   [7:0] tmp_15_fu_1165_p4;
wire   [22:0] trunc_ln61_2_fu_1175_p1;
wire   [0:0] icmp_ln61_8_fu_1185_p2;
wire   [0:0] icmp_ln61_7_fu_1179_p2;
wire   [0:0] or_ln61_2_fu_1191_p2;
wire   [0:0] grp_fu_462_p2;
wire   [0:0] and_ln61_2_fu_1197_p2;
wire   [31:0] bitcast_ln61_3_fu_1210_p1;
wire   [7:0] tmp_17_fu_1213_p4;
wire   [22:0] trunc_ln61_3_fu_1223_p1;
wire   [0:0] icmp_ln61_10_fu_1233_p2;
wire   [0:0] icmp_ln61_9_fu_1227_p2;
wire   [0:0] or_ln61_3_fu_1239_p2;
wire   [0:0] grp_fu_467_p2;
wire   [0:0] and_ln61_3_fu_1245_p2;
wire   [31:0] bitcast_ln61_4_fu_1258_p1;
wire   [7:0] tmp_19_fu_1261_p4;
wire   [22:0] trunc_ln61_4_fu_1271_p1;
wire   [0:0] icmp_ln61_12_fu_1281_p2;
wire   [0:0] icmp_ln61_11_fu_1275_p2;
wire   [0:0] or_ln61_4_fu_1287_p2;
wire   [0:0] grp_fu_472_p2;
wire   [0:0] and_ln61_4_fu_1293_p2;
wire   [31:0] bitcast_ln61_5_fu_1306_p1;
wire   [7:0] tmp_21_fu_1309_p4;
wire   [22:0] trunc_ln61_5_fu_1319_p1;
wire   [0:0] icmp_ln61_14_fu_1329_p2;
wire   [0:0] icmp_ln61_13_fu_1323_p2;
wire   [0:0] or_ln61_5_fu_1335_p2;
wire   [0:0] grp_fu_477_p2;
wire   [0:0] and_ln61_5_fu_1341_p2;
wire   [31:0] bitcast_ln61_6_fu_1354_p1;
wire   [7:0] tmp_23_fu_1357_p4;
wire   [22:0] trunc_ln61_6_fu_1367_p1;
wire   [0:0] icmp_ln61_16_fu_1377_p2;
wire   [0:0] icmp_ln61_15_fu_1371_p2;
wire   [0:0] or_ln61_6_fu_1383_p2;
wire   [0:0] grp_fu_482_p2;
wire   [0:0] and_ln61_6_fu_1389_p2;
wire   [31:0] bitcast_ln61_7_fu_1402_p1;
wire   [7:0] tmp_25_fu_1405_p4;
wire   [22:0] trunc_ln61_7_fu_1415_p1;
wire   [0:0] icmp_ln61_18_fu_1425_p2;
wire   [0:0] icmp_ln61_17_fu_1419_p2;
wire   [0:0] or_ln61_7_fu_1431_p2;
wire   [0:0] grp_fu_487_p2;
wire   [0:0] and_ln61_7_fu_1437_p2;
wire   [31:0] select_ln61_5_fu_1347_p3;
wire   [31:0] select_ln61_4_fu_1299_p3;
wire   [31:0] select_ln61_6_fu_1395_p3;
wire   [31:0] select_ln61_7_fu_1443_p3;
wire   [31:0] select_ln61_3_fu_1251_p3;
wire   [31:0] select_ln61_fu_1107_p3;
wire   [31:0] select_ln61_1_fu_1155_p3;
wire   [31:0] select_ln61_2_fu_1203_p3;
reg   [14:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire   [10:0] mul_ln230_1_fu_794_p00;
wire   [10:0] mul_ln230_2_fu_803_p00;
wire   [10:0] mul_ln230_3_fu_812_p00;
wire   [10:0] mul_ln230_4_fu_821_p00;
wire   [10:0] mul_ln230_5_fu_830_p00;
wire   [10:0] mul_ln230_6_fu_839_p00;
wire   [10:0] mul_ln230_7_fu_848_p00;
wire   [10:0] mul_ln230_fu_785_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 15'd1;
end

HW_accel_FC_layer_100_16_true_s_fc1_bias_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
fc1_bias_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc1_bias_address0),
    .ce0(fc1_bias_ce0),
    .q0(fc1_bias_q0),
    .address1(fc1_bias_address1),
    .ce1(fc1_bias_ce1),
    .q1(fc1_bias_q1),
    .address2(fc1_bias_address2),
    .ce2(fc1_bias_ce2),
    .q2(fc1_bias_q2),
    .address3(fc1_bias_address3),
    .ce3(fc1_bias_ce3),
    .q3(fc1_bias_q3),
    .address4(fc1_bias_address4),
    .ce4(fc1_bias_ce4),
    .q4(fc1_bias_q4),
    .address5(fc1_bias_address5),
    .ce5(fc1_bias_ce5),
    .q5(fc1_bias_q5),
    .address6(fc1_bias_address6),
    .ce6(fc1_bias_ce6),
    .q6(fc1_bias_q6),
    .address7(fc1_bias_address7),
    .ce7(fc1_bias_ce7),
    .q7(fc1_bias_q7)
);

HW_accel_FC_layer_100_16_true_s_fc1_weight_ROM_AUTO_1R #(
    .DataWidth( 32 ),
    .AddressRange( 1600 ),
    .AddressWidth( 11 ))
fc1_weight_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc1_weight_address0),
    .ce0(fc1_weight_ce0),
    .q0(fc1_weight_q0),
    .address1(fc1_weight_address1),
    .ce1(fc1_weight_ce1),
    .q1(fc1_weight_q1),
    .address2(fc1_weight_address2),
    .ce2(fc1_weight_ce2),
    .q2(fc1_weight_q2),
    .address3(fc1_weight_address3),
    .ce3(fc1_weight_ce3),
    .q3(fc1_weight_q3),
    .address4(fc1_weight_address4),
    .ce4(fc1_weight_ce4),
    .q4(fc1_weight_q4),
    .address5(fc1_weight_address5),
    .ce5(fc1_weight_ce5),
    .q5(fc1_weight_q5),
    .address6(fc1_weight_address6),
    .ce6(fc1_weight_ce6),
    .q6(fc1_weight_q6),
    .address7(fc1_weight_address7),
    .ce7(fc1_weight_ce7),
    .q7(fc1_weight_q7)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U393(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln220_7_reg_2030),
    .din1(mul_reg_2183),
    .ce(1'b1),
    .dout(grp_fu_388_p2)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U394(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln220_8_reg_2035),
    .din1(mul31_1_reg_2188),
    .ce(1'b1),
    .dout(grp_fu_392_p2)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U395(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln220_6_reg_2025),
    .din1(mul31_2_reg_2193),
    .ce(1'b1),
    .dout(grp_fu_396_p2)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U396(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln220_9_reg_2040),
    .din1(mul31_3_reg_2198),
    .ce(1'b1),
    .dout(grp_fu_400_p2)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U397(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln220_5_reg_2020),
    .din1(mul31_4_reg_2203),
    .ce(1'b1),
    .dout(grp_fu_404_p2)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U398(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln220_10_reg_2045),
    .din1(mul31_5_reg_2208),
    .ce(1'b1),
    .dout(grp_fu_408_p2)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U399(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln220_reg_2015),
    .din1(mul31_6_reg_2213),
    .ce(1'b1),
    .dout(grp_fu_412_p2)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U400(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln220_11_reg_2050),
    .din1(mul31_7_reg_2218),
    .ce(1'b1),
    .dout(grp_fu_416_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U401(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ip_reg_2131),
    .din1(fc1_weight_load_reg_2143),
    .ce(1'b1),
    .dout(grp_fu_420_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U402(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ip_reg_2131),
    .din1(fc1_weight_load_1_reg_2148),
    .ce(1'b1),
    .dout(grp_fu_424_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U403(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ip_reg_2131),
    .din1(fc1_weight_load_2_reg_2153),
    .ce(1'b1),
    .dout(grp_fu_428_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U404(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ip_reg_2131),
    .din1(fc1_weight_load_3_reg_2158),
    .ce(1'b1),
    .dout(grp_fu_432_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U405(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ip_reg_2131),
    .din1(fc1_weight_load_4_reg_2163),
    .ce(1'b1),
    .dout(grp_fu_436_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U406(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ip_reg_2131),
    .din1(fc1_weight_load_5_reg_2168),
    .ce(1'b1),
    .dout(grp_fu_440_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U407(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ip_reg_2131),
    .din1(fc1_weight_load_6_reg_2173),
    .ce(1'b1),
    .dout(grp_fu_444_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U408(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ip_reg_2131),
    .din1(fc1_weight_load_7_reg_2178),
    .ce(1'b1),
    .dout(grp_fu_448_p2)
);

HW_accel_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U409(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add32_lcssa10_fu_138),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_452_p2)
);

HW_accel_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U410(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add32_1_lcssa12_fu_142),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_457_p2)
);

HW_accel_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U411(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add32_2_lcssa14_fu_146),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_462_p2)
);

HW_accel_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U412(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add32_3_lcssa16_fu_150),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_467_p2)
);

HW_accel_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U413(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add32_4_lcssa18_fu_154),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_472_p2)
);

HW_accel_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U414(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add32_5_lcssa20_fu_158),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_477_p2)
);

HW_accel_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U415(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add32_6_lcssa22_fu_162),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_482_p2)
);

HW_accel_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U416(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add32_7_lcssa24_fu_166),
    .din1(32'd0),
    .ce(1'b1),
    .opcode(5'd4),
    .dout(grp_fu_487_p2)
);

HW_accel_mul_4ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_4ns_8ns_11_1_1_U417(
    .din0(mul_ln230_fu_785_p0),
    .din1(mul_ln230_fu_785_p1),
    .dout(mul_ln230_fu_785_p2)
);

HW_accel_mul_4ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_4ns_8ns_11_1_1_U418(
    .din0(mul_ln230_1_fu_794_p0),
    .din1(mul_ln230_1_fu_794_p1),
    .dout(mul_ln230_1_fu_794_p2)
);

HW_accel_mul_4ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_4ns_8ns_11_1_1_U419(
    .din0(mul_ln230_2_fu_803_p0),
    .din1(mul_ln230_2_fu_803_p1),
    .dout(mul_ln230_2_fu_803_p2)
);

HW_accel_mul_4ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_4ns_8ns_11_1_1_U420(
    .din0(mul_ln230_3_fu_812_p0),
    .din1(mul_ln230_3_fu_812_p1),
    .dout(mul_ln230_3_fu_812_p2)
);

HW_accel_mul_4ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_4ns_8ns_11_1_1_U421(
    .din0(mul_ln230_4_fu_821_p0),
    .din1(mul_ln230_4_fu_821_p1),
    .dout(mul_ln230_4_fu_821_p2)
);

HW_accel_mul_4ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_4ns_8ns_11_1_1_U422(
    .din0(mul_ln230_5_fu_830_p0),
    .din1(mul_ln230_5_fu_830_p1),
    .dout(mul_ln230_5_fu_830_p2)
);

HW_accel_mul_4ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_4ns_8ns_11_1_1_U423(
    .din0(mul_ln230_6_fu_839_p0),
    .din1(mul_ln230_6_fu_839_p1),
    .dout(mul_ln230_6_fu_839_p2)
);

HW_accel_mul_4ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_4ns_8ns_11_1_1_U424(
    .din0(mul_ln230_7_fu_848_p0),
    .din1(mul_ln230_7_fu_848_p1),
    .dout(mul_ln230_7_fu_848_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        i_index_reg_377 <= add_ln216_reg_2010;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        i_index_reg_377 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        turn_fu_70 <= 2'd0;
    end else if (((icmp_ln216_fu_943_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        turn_fu_70 <= add_ln213_reg_1796;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        add32_1_lcssa12_fu_142 <= grp_fu_392_p2;
        add32_2_lcssa14_fu_146 <= grp_fu_396_p2;
        add32_3_lcssa16_fu_150 <= grp_fu_400_p2;
        add32_4_lcssa18_fu_154 <= grp_fu_404_p2;
        add32_5_lcssa20_fu_158 <= grp_fu_408_p2;
        add32_6_lcssa22_fu_162 <= grp_fu_412_p2;
        add32_7_lcssa24_fu_166 <= grp_fu_416_p2;
        add32_lcssa10_fu_138 <= grp_fu_388_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln216_fu_943_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        add32_1_lcssa12_load_reg_2062 <= add32_1_lcssa12_fu_142;
        add32_2_lcssa14_load_reg_2069 <= add32_2_lcssa14_fu_146;
        add32_3_lcssa16_load_reg_2076 <= add32_3_lcssa16_fu_150;
        add32_4_lcssa18_load_reg_2083 <= add32_4_lcssa18_fu_154;
        add32_5_lcssa20_load_reg_2090 <= add32_5_lcssa20_fu_158;
        add32_6_lcssa22_load_reg_2097 <= add32_6_lcssa22_fu_162;
        add32_7_lcssa24_load_reg_2104 <= add32_7_lcssa24_fu_166;
        add32_lcssa10_load_reg_2055 <= add32_lcssa10_fu_138;
        icmp_ln237_reg_2111 <= icmp_ln237_fu_1017_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln213_reg_1796 <= add_ln213_fu_586_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln216_reg_2010 <= add_ln216_fu_949_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln213_fu_580_p2 == 1'd0))) begin
        empty_220_reg_1812[3] <= empty_220_fu_609_p2[3];
        empty_221_reg_1822[3] <= empty_221_fu_620_p2[3];
        empty_222_reg_1832[3] <= empty_222_fu_631_p2[3];
        empty_223_reg_1842[3] <= empty_223_fu_642_p2[3];
        empty_224_reg_1852[3] <= empty_224_fu_653_p2[3];
        empty_225_reg_1862[3] <= empty_225_fu_664_p2[3];
        empty_226_reg_1872[3] <= empty_226_fu_675_p2[3];
        shl_ln_reg_1801[3] <= shl_ln_fu_596_p3[3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fc1_bias_load_1_reg_1927 <= fc1_bias_q6;
        fc1_bias_load_2_reg_1932 <= fc1_bias_q5;
        fc1_bias_load_3_reg_1937 <= fc1_bias_q4;
        fc1_bias_load_4_reg_1942 <= fc1_bias_q3;
        fc1_bias_load_5_reg_1947 <= fc1_bias_q2;
        fc1_bias_load_6_reg_1952 <= fc1_bias_q1;
        fc1_bias_load_7_reg_1957 <= fc1_bias_q0;
        fc1_bias_load_reg_1922 <= fc1_bias_q7;
        mul_ln230_1_reg_1887 <= mul_ln230_1_fu_794_p2;
        mul_ln230_2_reg_1892 <= mul_ln230_2_fu_803_p2;
        mul_ln230_3_reg_1897 <= mul_ln230_3_fu_812_p2;
        mul_ln230_4_reg_1902 <= mul_ln230_4_fu_821_p2;
        mul_ln230_5_reg_1907 <= mul_ln230_5_fu_830_p2;
        mul_ln230_6_reg_1912 <= mul_ln230_6_fu_839_p2;
        mul_ln230_7_reg_1917 <= mul_ln230_7_fu_848_p2;
        mul_ln230_reg_1882 <= mul_ln230_fu_785_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        fc1_weight_load_1_reg_2148 <= fc1_weight_q6;
        fc1_weight_load_2_reg_2153 <= fc1_weight_q5;
        fc1_weight_load_3_reg_2158 <= fc1_weight_q4;
        fc1_weight_load_4_reg_2163 <= fc1_weight_q3;
        fc1_weight_load_5_reg_2168 <= fc1_weight_q2;
        fc1_weight_load_6_reg_2173 <= fc1_weight_q1;
        fc1_weight_load_7_reg_2178 <= fc1_weight_q0;
        fc1_weight_load_reg_2143 <= fc1_weight_q7;
        ip_reg_2131 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        mul31_1_reg_2188 <= grp_fu_424_p2;
        mul31_2_reg_2193 <= grp_fu_428_p2;
        mul31_3_reg_2198 <= grp_fu_432_p2;
        mul31_4_reg_2203 <= grp_fu_436_p2;
        mul31_5_reg_2208 <= grp_fu_440_p2;
        mul31_6_reg_2213 <= grp_fu_444_p2;
        mul31_7_reg_2218 <= grp_fu_448_p2;
        mul_reg_2183 <= grp_fu_420_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        output_0_018_fu_82 <= select_ln237_13_fu_1541_p3;
        output_10_023_fu_102 <= select_ln237_8_fu_1506_p3;
        output_11_022_fu_98 <= select_ln237_9_fu_1513_p3;
        output_12_020_fu_90 <= select_ln237_11_fu_1527_p3;
        output_13_019_fu_86 <= select_ln237_12_fu_1534_p3;
        output_1445_017_fu_78 <= select_ln237_14_fu_1548_p3;
        output_15_016_fu_74 <= select_ln237_15_fu_1555_p3;
        output_1_021_fu_94 <= select_ln237_10_fu_1520_p3;
        output_2_024_fu_106 <= select_ln237_7_fu_1499_p3;
        output_3_027_fu_118 <= select_ln237_4_fu_1478_p3;
        output_4_030_fu_130 <= select_ln237_1_fu_1457_p3;
        output_5_031_fu_134 <= select_ln237_fu_1450_p3;
        output_6_029_fu_126 <= select_ln237_2_fu_1464_p3;
        output_7_028_fu_122 <= select_ln237_3_fu_1471_p3;
        output_8_026_fu_114 <= select_ln237_5_fu_1485_p3;
        output_9_025_fu_110 <= select_ln237_6_fu_1492_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln216_fu_943_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        select_ln220_10_reg_2045 <= select_ln220_10_fu_1003_p3;
        select_ln220_11_reg_2050 <= select_ln220_11_fu_1010_p3;
        select_ln220_5_reg_2020 <= select_ln220_5_fu_968_p3;
        select_ln220_6_reg_2025 <= select_ln220_6_fu_975_p3;
        select_ln220_7_reg_2030 <= select_ln220_7_fu_982_p3;
        select_ln220_8_reg_2035 <= select_ln220_8_fu_989_p3;
        select_ln220_9_reg_2040 <= select_ln220_9_fu_996_p3;
        select_ln220_reg_2015 <= select_ln220_fu_961_p3;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state2) & (icmp_ln213_fu_580_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln213_fu_580_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fc1_bias_ce0 = 1'b1;
    end else begin
        fc1_bias_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fc1_bias_ce1 = 1'b1;
    end else begin
        fc1_bias_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fc1_bias_ce2 = 1'b1;
    end else begin
        fc1_bias_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fc1_bias_ce3 = 1'b1;
    end else begin
        fc1_bias_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fc1_bias_ce4 = 1'b1;
    end else begin
        fc1_bias_ce4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fc1_bias_ce5 = 1'b1;
    end else begin
        fc1_bias_ce5 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fc1_bias_ce6 = 1'b1;
    end else begin
        fc1_bias_ce6 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fc1_bias_ce7 = 1'b1;
    end else begin
        fc1_bias_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fc1_weight_ce0 = 1'b1;
    end else begin
        fc1_weight_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fc1_weight_ce1 = 1'b1;
    end else begin
        fc1_weight_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fc1_weight_ce2 = 1'b1;
    end else begin
        fc1_weight_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fc1_weight_ce3 = 1'b1;
    end else begin
        fc1_weight_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fc1_weight_ce4 = 1'b1;
    end else begin
        fc1_weight_ce4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fc1_weight_ce5 = 1'b1;
    end else begin
        fc1_weight_ce5 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fc1_weight_ce6 = 1'b1;
    end else begin
        fc1_weight_ce6 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        fc1_weight_ce7 = 1'b1;
    end else begin
        fc1_weight_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln213_fu_580_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln216_fu_943_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln213_fu_586_p2 = (turn_fu_70 + 2'd1);

assign add_ln216_fu_949_p2 = (i_index_reg_377 + 7'd1);

assign add_ln230_10_fu_923_p2 = (mul_ln230_6_reg_1912 + zext_ln230_13_fu_859_p1);

assign add_ln230_11_fu_933_p2 = (mul_ln230_7_reg_1917 + zext_ln230_13_fu_859_p1);

assign add_ln230_5_fu_873_p2 = (mul_ln230_1_reg_1887 + zext_ln230_13_fu_859_p1);

assign add_ln230_6_fu_883_p2 = (mul_ln230_2_reg_1892 + zext_ln230_13_fu_859_p1);

assign add_ln230_7_fu_893_p2 = (mul_ln230_3_reg_1897 + zext_ln230_13_fu_859_p1);

assign add_ln230_8_fu_903_p2 = (mul_ln230_4_reg_1902 + zext_ln230_13_fu_859_p1);

assign add_ln230_9_fu_913_p2 = (mul_ln230_5_reg_1907 + zext_ln230_13_fu_859_p1);

assign add_ln230_fu_863_p2 = (mul_ln230_reg_1882 + zext_ln230_13_fu_859_p1);

assign and_ln61_1_fu_1149_p2 = (or_ln61_1_fu_1143_p2 & grp_fu_457_p2);

assign and_ln61_2_fu_1197_p2 = (or_ln61_2_fu_1191_p2 & grp_fu_462_p2);

assign and_ln61_3_fu_1245_p2 = (or_ln61_3_fu_1239_p2 & grp_fu_467_p2);

assign and_ln61_4_fu_1293_p2 = (or_ln61_4_fu_1287_p2 & grp_fu_472_p2);

assign and_ln61_5_fu_1341_p2 = (or_ln61_5_fu_1335_p2 & grp_fu_477_p2);

assign and_ln61_6_fu_1389_p2 = (or_ln61_6_fu_1383_p2 & grp_fu_482_p2);

assign and_ln61_7_fu_1437_p2 = (or_ln61_7_fu_1431_p2 & grp_fu_487_p2);

assign and_ln61_fu_1101_p2 = (or_ln61_fu_1095_p2 & grp_fu_452_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return_0 = output_0_018_fu_82;

assign ap_return_1 = output_1_021_fu_94;

assign ap_return_10 = output_10_023_fu_102;

assign ap_return_11 = output_11_022_fu_98;

assign ap_return_12 = output_12_020_fu_90;

assign ap_return_13 = output_13_019_fu_86;

assign ap_return_14 = output_1445_017_fu_78;

assign ap_return_15 = output_15_016_fu_74;

assign ap_return_2 = output_2_024_fu_106;

assign ap_return_3 = output_3_027_fu_118;

assign ap_return_4 = output_4_030_fu_130;

assign ap_return_5 = output_5_031_fu_134;

assign ap_return_6 = output_6_029_fu_126;

assign ap_return_7 = output_7_028_fu_122;

assign ap_return_8 = output_8_026_fu_114;

assign ap_return_9 = output_9_025_fu_110;

assign bitcast_ln61_1_fu_1114_p1 = add32_1_lcssa12_load_reg_2062;

assign bitcast_ln61_2_fu_1162_p1 = add32_2_lcssa14_load_reg_2069;

assign bitcast_ln61_3_fu_1210_p1 = add32_3_lcssa16_load_reg_2076;

assign bitcast_ln61_4_fu_1258_p1 = add32_4_lcssa18_load_reg_2083;

assign bitcast_ln61_5_fu_1306_p1 = add32_5_lcssa20_load_reg_2090;

assign bitcast_ln61_6_fu_1354_p1 = add32_6_lcssa22_load_reg_2097;

assign bitcast_ln61_7_fu_1402_p1 = add32_7_lcssa24_load_reg_2104;

assign bitcast_ln61_fu_1066_p1 = add32_lcssa10_load_reg_2055;

assign cmp9_fu_955_p2 = ((i_index_reg_377 == 7'd0) ? 1'b1 : 1'b0);

assign empty_220_fu_609_p2 = (shl_ln_fu_596_p3 | 4'd1);

assign empty_221_fu_620_p2 = (shl_ln_fu_596_p3 | 4'd2);

assign empty_222_fu_631_p2 = (shl_ln_fu_596_p3 | 4'd3);

assign empty_223_fu_642_p2 = (shl_ln_fu_596_p3 | 4'd4);

assign empty_224_fu_653_p2 = (shl_ln_fu_596_p3 | 4'd5);

assign empty_225_fu_664_p2 = (shl_ln_fu_596_p3 | 4'd6);

assign empty_226_fu_675_p2 = (shl_ln_fu_596_p3 | 4'd7);

assign fc1_bias_address0 = p_cast6_fu_681_p1;

assign fc1_bias_address1 = p_cast5_fu_670_p1;

assign fc1_bias_address2 = p_cast4_fu_659_p1;

assign fc1_bias_address3 = p_cast3_fu_648_p1;

assign fc1_bias_address4 = p_cast2_fu_637_p1;

assign fc1_bias_address5 = p_cast1_fu_626_p1;

assign fc1_bias_address6 = p_cast_fu_615_p1;

assign fc1_bias_address7 = trunc_ln237_cast_fu_604_p1;

assign fc1_weight_address0 = zext_ln230_21_fu_938_p1;

assign fc1_weight_address1 = zext_ln230_20_fu_928_p1;

assign fc1_weight_address2 = zext_ln230_19_fu_918_p1;

assign fc1_weight_address3 = zext_ln230_18_fu_908_p1;

assign fc1_weight_address4 = zext_ln230_17_fu_898_p1;

assign fc1_weight_address5 = zext_ln230_16_fu_888_p1;

assign fc1_weight_address6 = zext_ln230_15_fu_878_p1;

assign fc1_weight_address7 = zext_ln230_14_fu_868_p1;

assign icmp_ln213_fu_580_p2 = ((turn_fu_70 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln216_fu_943_p2 = ((i_index_reg_377 == 7'd100) ? 1'b1 : 1'b0);

assign icmp_ln237_fu_1017_p2 = ((shl_ln_reg_1801 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_10_fu_1233_p2 = ((trunc_ln61_3_fu_1223_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_11_fu_1275_p2 = ((tmp_19_fu_1261_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln61_12_fu_1281_p2 = ((trunc_ln61_4_fu_1271_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_13_fu_1323_p2 = ((tmp_21_fu_1309_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln61_14_fu_1329_p2 = ((trunc_ln61_5_fu_1319_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_15_fu_1371_p2 = ((tmp_23_fu_1357_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln61_16_fu_1377_p2 = ((trunc_ln61_6_fu_1367_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_17_fu_1419_p2 = ((tmp_25_fu_1405_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln61_18_fu_1425_p2 = ((trunc_ln61_7_fu_1415_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_4_fu_1089_p2 = ((trunc_ln61_fu_1079_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_5_fu_1131_p2 = ((tmp_13_fu_1117_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln61_6_fu_1137_p2 = ((trunc_ln61_1_fu_1127_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_7_fu_1179_p2 = ((tmp_15_fu_1165_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln61_8_fu_1185_p2 = ((trunc_ln61_2_fu_1175_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln61_9_fu_1227_p2 = ((tmp_17_fu_1213_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_1083_p2 = ((tmp_fu_1069_p4 != 8'd255) ? 1'b1 : 1'b0);

assign input_r_address0 = zext_ln216_fu_854_p1;

assign mul_ln230_1_fu_794_p0 = mul_ln230_1_fu_794_p00;

assign mul_ln230_1_fu_794_p00 = empty_220_reg_1812;

assign mul_ln230_1_fu_794_p1 = 11'd100;

assign mul_ln230_2_fu_803_p0 = mul_ln230_2_fu_803_p00;

assign mul_ln230_2_fu_803_p00 = empty_221_reg_1822;

assign mul_ln230_2_fu_803_p1 = 11'd100;

assign mul_ln230_3_fu_812_p0 = mul_ln230_3_fu_812_p00;

assign mul_ln230_3_fu_812_p00 = empty_222_reg_1832;

assign mul_ln230_3_fu_812_p1 = 11'd100;

assign mul_ln230_4_fu_821_p0 = mul_ln230_4_fu_821_p00;

assign mul_ln230_4_fu_821_p00 = empty_223_reg_1842;

assign mul_ln230_4_fu_821_p1 = 11'd100;

assign mul_ln230_5_fu_830_p0 = mul_ln230_5_fu_830_p00;

assign mul_ln230_5_fu_830_p00 = empty_224_reg_1852;

assign mul_ln230_5_fu_830_p1 = 11'd100;

assign mul_ln230_6_fu_839_p0 = mul_ln230_6_fu_839_p00;

assign mul_ln230_6_fu_839_p00 = empty_225_reg_1862;

assign mul_ln230_6_fu_839_p1 = 11'd100;

assign mul_ln230_7_fu_848_p0 = mul_ln230_7_fu_848_p00;

assign mul_ln230_7_fu_848_p00 = empty_226_reg_1872;

assign mul_ln230_7_fu_848_p1 = 11'd100;

assign mul_ln230_fu_785_p0 = mul_ln230_fu_785_p00;

assign mul_ln230_fu_785_p00 = shl_ln_reg_1801;

assign mul_ln230_fu_785_p1 = 11'd100;

assign or_ln61_1_fu_1143_p2 = (icmp_ln61_6_fu_1137_p2 | icmp_ln61_5_fu_1131_p2);

assign or_ln61_2_fu_1191_p2 = (icmp_ln61_8_fu_1185_p2 | icmp_ln61_7_fu_1179_p2);

assign or_ln61_3_fu_1239_p2 = (icmp_ln61_9_fu_1227_p2 | icmp_ln61_10_fu_1233_p2);

assign or_ln61_4_fu_1287_p2 = (icmp_ln61_12_fu_1281_p2 | icmp_ln61_11_fu_1275_p2);

assign or_ln61_5_fu_1335_p2 = (icmp_ln61_14_fu_1329_p2 | icmp_ln61_13_fu_1323_p2);

assign or_ln61_6_fu_1383_p2 = (icmp_ln61_16_fu_1377_p2 | icmp_ln61_15_fu_1371_p2);

assign or_ln61_7_fu_1431_p2 = (icmp_ln61_18_fu_1425_p2 | icmp_ln61_17_fu_1419_p2);

assign or_ln61_fu_1095_p2 = (icmp_ln61_fu_1083_p2 | icmp_ln61_4_fu_1089_p2);

assign p_cast1_fu_626_p1 = empty_221_fu_620_p2;

assign p_cast2_fu_637_p1 = empty_222_fu_631_p2;

assign p_cast3_fu_648_p1 = empty_223_fu_642_p2;

assign p_cast4_fu_659_p1 = empty_224_fu_653_p2;

assign p_cast5_fu_670_p1 = empty_225_fu_664_p2;

assign p_cast6_fu_681_p1 = empty_226_fu_675_p2;

assign p_cast_fu_615_p1 = empty_220_fu_609_p2;

assign select_ln220_10_fu_1003_p3 = ((cmp9_fu_955_p2[0:0] == 1'b1) ? fc1_bias_load_5_reg_1947 : add32_5_lcssa20_fu_158);

assign select_ln220_11_fu_1010_p3 = ((cmp9_fu_955_p2[0:0] == 1'b1) ? fc1_bias_load_7_reg_1957 : add32_7_lcssa24_fu_166);

assign select_ln220_5_fu_968_p3 = ((cmp9_fu_955_p2[0:0] == 1'b1) ? fc1_bias_load_4_reg_1942 : add32_4_lcssa18_fu_154);

assign select_ln220_6_fu_975_p3 = ((cmp9_fu_955_p2[0:0] == 1'b1) ? fc1_bias_load_2_reg_1932 : add32_2_lcssa14_fu_146);

assign select_ln220_7_fu_982_p3 = ((cmp9_fu_955_p2[0:0] == 1'b1) ? fc1_bias_load_reg_1922 : add32_lcssa10_fu_138);

assign select_ln220_8_fu_989_p3 = ((cmp9_fu_955_p2[0:0] == 1'b1) ? fc1_bias_load_1_reg_1927 : add32_1_lcssa12_fu_142);

assign select_ln220_9_fu_996_p3 = ((cmp9_fu_955_p2[0:0] == 1'b1) ? fc1_bias_load_3_reg_1937 : add32_3_lcssa16_fu_150);

assign select_ln220_fu_961_p3 = ((cmp9_fu_955_p2[0:0] == 1'b1) ? fc1_bias_load_6_reg_1952 : add32_6_lcssa22_fu_162);

assign select_ln237_10_fu_1520_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? select_ln61_1_fu_1155_p3 : output_1_021_fu_94);

assign select_ln237_11_fu_1527_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? output_12_020_fu_90 : select_ln61_4_fu_1299_p3);

assign select_ln237_12_fu_1534_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? output_13_019_fu_86 : select_ln61_5_fu_1347_p3);

assign select_ln237_13_fu_1541_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? select_ln61_fu_1107_p3 : output_0_018_fu_82);

assign select_ln237_14_fu_1548_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? output_1445_017_fu_78 : select_ln61_6_fu_1395_p3);

assign select_ln237_15_fu_1555_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? output_15_016_fu_74 : select_ln61_7_fu_1443_p3);

assign select_ln237_1_fu_1457_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? select_ln61_4_fu_1299_p3 : output_4_030_fu_130);

assign select_ln237_2_fu_1464_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? select_ln61_6_fu_1395_p3 : output_6_029_fu_126);

assign select_ln237_3_fu_1471_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? select_ln61_7_fu_1443_p3 : output_7_028_fu_122);

assign select_ln237_4_fu_1478_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? select_ln61_3_fu_1251_p3 : output_3_027_fu_118);

assign select_ln237_5_fu_1485_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? output_8_026_fu_114 : select_ln61_fu_1107_p3);

assign select_ln237_6_fu_1492_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? output_9_025_fu_110 : select_ln61_1_fu_1155_p3);

assign select_ln237_7_fu_1499_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? select_ln61_2_fu_1203_p3 : output_2_024_fu_106);

assign select_ln237_8_fu_1506_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? output_10_023_fu_102 : select_ln61_2_fu_1203_p3);

assign select_ln237_9_fu_1513_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? output_11_022_fu_98 : select_ln61_3_fu_1251_p3);

assign select_ln237_fu_1450_p3 = ((icmp_ln237_reg_2111[0:0] == 1'b1) ? select_ln61_5_fu_1347_p3 : output_5_031_fu_134);

assign select_ln61_1_fu_1155_p3 = ((and_ln61_1_fu_1149_p2[0:0] == 1'b1) ? 32'd0 : add32_1_lcssa12_load_reg_2062);

assign select_ln61_2_fu_1203_p3 = ((and_ln61_2_fu_1197_p2[0:0] == 1'b1) ? 32'd0 : add32_2_lcssa14_load_reg_2069);

assign select_ln61_3_fu_1251_p3 = ((and_ln61_3_fu_1245_p2[0:0] == 1'b1) ? 32'd0 : add32_3_lcssa16_load_reg_2076);

assign select_ln61_4_fu_1299_p3 = ((and_ln61_4_fu_1293_p2[0:0] == 1'b1) ? 32'd0 : add32_4_lcssa18_load_reg_2083);

assign select_ln61_5_fu_1347_p3 = ((and_ln61_5_fu_1341_p2[0:0] == 1'b1) ? 32'd0 : add32_5_lcssa20_load_reg_2090);

assign select_ln61_6_fu_1395_p3 = ((and_ln61_6_fu_1389_p2[0:0] == 1'b1) ? 32'd0 : add32_6_lcssa22_load_reg_2097);

assign select_ln61_7_fu_1443_p3 = ((and_ln61_7_fu_1437_p2[0:0] == 1'b1) ? 32'd0 : add32_7_lcssa24_load_reg_2104);

assign select_ln61_fu_1107_p3 = ((and_ln61_fu_1101_p2[0:0] == 1'b1) ? 32'd0 : add32_lcssa10_load_reg_2055);

assign shl_ln_fu_596_p3 = {{trunc_ln237_fu_592_p1}, {3'd0}};

assign tmp_13_fu_1117_p4 = {{bitcast_ln61_1_fu_1114_p1[30:23]}};

assign tmp_15_fu_1165_p4 = {{bitcast_ln61_2_fu_1162_p1[30:23]}};

assign tmp_17_fu_1213_p4 = {{bitcast_ln61_3_fu_1210_p1[30:23]}};

assign tmp_19_fu_1261_p4 = {{bitcast_ln61_4_fu_1258_p1[30:23]}};

assign tmp_21_fu_1309_p4 = {{bitcast_ln61_5_fu_1306_p1[30:23]}};

assign tmp_23_fu_1357_p4 = {{bitcast_ln61_6_fu_1354_p1[30:23]}};

assign tmp_25_fu_1405_p4 = {{bitcast_ln61_7_fu_1402_p1[30:23]}};

assign tmp_fu_1069_p4 = {{bitcast_ln61_fu_1066_p1[30:23]}};

assign trunc_ln237_cast_fu_604_p1 = shl_ln_fu_596_p3;

assign trunc_ln237_fu_592_p1 = turn_fu_70[0:0];

assign trunc_ln61_1_fu_1127_p1 = bitcast_ln61_1_fu_1114_p1[22:0];

assign trunc_ln61_2_fu_1175_p1 = bitcast_ln61_2_fu_1162_p1[22:0];

assign trunc_ln61_3_fu_1223_p1 = bitcast_ln61_3_fu_1210_p1[22:0];

assign trunc_ln61_4_fu_1271_p1 = bitcast_ln61_4_fu_1258_p1[22:0];

assign trunc_ln61_5_fu_1319_p1 = bitcast_ln61_5_fu_1306_p1[22:0];

assign trunc_ln61_6_fu_1367_p1 = bitcast_ln61_6_fu_1354_p1[22:0];

assign trunc_ln61_7_fu_1415_p1 = bitcast_ln61_7_fu_1402_p1[22:0];

assign trunc_ln61_fu_1079_p1 = bitcast_ln61_fu_1066_p1[22:0];

assign zext_ln216_fu_854_p1 = i_index_reg_377;

assign zext_ln230_13_fu_859_p1 = i_index_reg_377;

assign zext_ln230_14_fu_868_p1 = add_ln230_fu_863_p2;

assign zext_ln230_15_fu_878_p1 = add_ln230_5_fu_873_p2;

assign zext_ln230_16_fu_888_p1 = add_ln230_6_fu_883_p2;

assign zext_ln230_17_fu_898_p1 = add_ln230_7_fu_893_p2;

assign zext_ln230_18_fu_908_p1 = add_ln230_8_fu_903_p2;

assign zext_ln230_19_fu_918_p1 = add_ln230_9_fu_913_p2;

assign zext_ln230_20_fu_928_p1 = add_ln230_10_fu_923_p2;

assign zext_ln230_21_fu_938_p1 = add_ln230_11_fu_933_p2;

always @ (posedge ap_clk) begin
    shl_ln_reg_1801[2:0] <= 3'b000;
    empty_220_reg_1812[2:0] <= 3'b001;
    empty_221_reg_1822[2:0] <= 3'b010;
    empty_222_reg_1832[2:0] <= 3'b011;
    empty_223_reg_1842[2:0] <= 3'b100;
    empty_224_reg_1852[2:0] <= 3'b101;
    empty_225_reg_1862[2:0] <= 3'b110;
    empty_226_reg_1872[2:0] <= 3'b111;
end

endmodule //HW_accel_FC_layer_100_16_true_s
