// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module HW_accel_conv2D_4_s (
        ap_clk,
        ap_rst,
        kch,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        p_read35,
        p_read36,
        p_read37,
        p_read38,
        p_read39,
        p_read40,
        p_read41,
        p_read42,
        p_read43,
        p_read44,
        prev_sum,
        ap_return
);


input   ap_clk;
input   ap_rst;
input  [1:0] kch;
input  [31:0] p_read;
input  [31:0] p_read1;
input  [31:0] p_read2;
input  [31:0] p_read3;
input  [31:0] p_read4;
input  [31:0] p_read5;
input  [31:0] p_read6;
input  [31:0] p_read7;
input  [31:0] p_read8;
input  [31:0] p_read9;
input  [31:0] p_read10;
input  [31:0] p_read11;
input  [31:0] p_read12;
input  [31:0] p_read13;
input  [31:0] p_read14;
input  [31:0] p_read15;
input  [31:0] p_read16;
input  [31:0] p_read17;
input  [31:0] p_read18;
input  [31:0] p_read19;
input  [31:0] p_read20;
input  [31:0] p_read21;
input  [31:0] p_read22;
input  [31:0] p_read23;
input  [31:0] p_read24;
input  [31:0] p_read25;
input  [31:0] p_read26;
input  [31:0] p_read27;
input  [31:0] p_read28;
input  [31:0] p_read29;
input  [31:0] p_read30;
input  [31:0] p_read31;
input  [31:0] p_read32;
input  [31:0] p_read33;
input  [31:0] p_read34;
input  [31:0] p_read35;
input  [31:0] p_read36;
input  [31:0] p_read37;
input  [31:0] p_read38;
input  [31:0] p_read39;
input  [31:0] p_read40;
input  [31:0] p_read41;
input  [31:0] p_read42;
input  [31:0] p_read43;
input  [31:0] p_read44;
input  [31:0] prev_sum;
output  [31:0] ap_return;

reg   [31:0] prev_sum_read_reg_588;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] prev_sum_read_reg_588_pp0_iter1_reg;
reg   [31:0] prev_sum_read_reg_588_pp0_iter2_reg;
reg   [31:0] prev_sum_read_reg_588_pp0_iter3_reg;
reg   [31:0] prev_sum_read_reg_588_pp0_iter4_reg;
reg   [31:0] p_read_16_reg_593;
reg   [31:0] p_read_17_reg_598;
reg   [31:0] p_read_18_reg_603;
reg   [31:0] p_read_19_reg_608;
reg   [31:0] p_read_20_reg_613;
reg   [31:0] p_read_21_reg_618;
reg   [31:0] p_read_22_reg_623;
reg   [31:0] p_read_23_reg_628;
reg   [31:0] p_read_24_reg_633;
wire   [31:0] tmp_fu_462_p6;
reg   [31:0] tmp_reg_638;
wire   [31:0] tmp_8_fu_476_p6;
reg   [31:0] tmp_8_reg_643;
wire   [31:0] tmp_9_fu_490_p6;
reg   [31:0] tmp_9_reg_648;
wire   [31:0] tmp_s_fu_504_p6;
reg   [31:0] tmp_s_reg_653;
wire   [31:0] tmp_1_fu_518_p6;
reg   [31:0] tmp_1_reg_658;
wire   [31:0] tmp_2_fu_532_p6;
reg   [31:0] tmp_2_reg_663;
wire   [31:0] tmp_3_fu_546_p6;
reg   [31:0] tmp_3_reg_668;
wire   [31:0] tmp_4_fu_560_p6;
reg   [31:0] tmp_4_reg_673;
wire   [31:0] tmp_5_fu_574_p6;
reg   [31:0] tmp_5_reg_678;
wire   [31:0] grp_fu_426_p2;
reg   [31:0] mul_reg_683;
wire   [31:0] grp_fu_430_p2;
reg   [31:0] mul_s_reg_688;
wire   [31:0] grp_fu_434_p2;
reg   [31:0] mul_3_reg_693;
wire   [31:0] grp_fu_438_p2;
reg   [31:0] mul_1_reg_698;
wire   [31:0] grp_fu_442_p2;
reg   [31:0] mul_1_1_reg_703;
wire   [31:0] grp_fu_446_p2;
reg   [31:0] mul_1_2_reg_708;
wire   [31:0] grp_fu_450_p2;
reg   [31:0] mul_2_reg_713;
wire   [31:0] grp_fu_454_p2;
reg   [31:0] mul_2_1_reg_718;
wire   [31:0] grp_fu_458_p2;
reg   [31:0] mul_2_2_reg_723;
wire   [31:0] grp_fu_390_p2;
reg   [31:0] s0_reg_728;
wire   [31:0] grp_fu_394_p2;
reg   [31:0] s1_reg_733;
wire   [31:0] grp_fu_398_p2;
reg   [31:0] s2_reg_738;
wire   [31:0] grp_fu_402_p2;
reg   [31:0] s3_reg_743;
wire   [31:0] grp_fu_406_p2;
reg   [31:0] s4_reg_748;
reg   [31:0] s4_reg_748_pp0_iter10_reg;
reg   [31:0] s4_reg_748_pp0_iter11_reg;
reg   [31:0] s4_reg_748_pp0_iter12_reg;
reg   [31:0] s4_reg_748_pp0_iter13_reg;
reg   [31:0] s4_reg_748_pp0_iter14_reg;
reg   [31:0] s4_reg_748_pp0_iter15_reg;
reg   [31:0] s4_reg_748_pp0_iter16_reg;
reg   [31:0] s4_reg_748_pp0_iter17_reg;
reg   [31:0] s4_reg_748_pp0_iter18_reg;
reg   [31:0] s4_reg_748_pp0_iter19_reg;
wire   [31:0] grp_fu_410_p2;
reg   [31:0] s5_reg_753;
wire   [31:0] grp_fu_414_p2;
reg   [31:0] s6_reg_758;
wire   [31:0] grp_fu_418_p2;
reg   [31:0] s7_reg_763;
wire    ap_block_pp0_stage0;
wire   [31:0] grp_fu_422_p2;
reg   [1:0] kch_int_reg;
reg   [31:0] p_read_int_reg;
reg   [31:0] p_read1_int_reg;
reg   [31:0] p_read2_int_reg;
reg   [31:0] p_read3_int_reg;
reg   [31:0] p_read4_int_reg;
reg   [31:0] p_read5_int_reg;
reg   [31:0] p_read6_int_reg;
reg   [31:0] p_read7_int_reg;
reg   [31:0] p_read8_int_reg;
reg   [31:0] p_read9_int_reg;
reg   [31:0] p_read10_int_reg;
reg   [31:0] p_read11_int_reg;
reg   [31:0] p_read12_int_reg;
reg   [31:0] p_read13_int_reg;
reg   [31:0] p_read14_int_reg;
reg   [31:0] p_read15_int_reg;
reg   [31:0] p_read16_int_reg;
reg   [31:0] p_read17_int_reg;
reg   [31:0] p_read18_int_reg;
reg   [31:0] p_read19_int_reg;
reg   [31:0] p_read20_int_reg;
reg   [31:0] p_read21_int_reg;
reg   [31:0] p_read22_int_reg;
reg   [31:0] p_read23_int_reg;
reg   [31:0] p_read24_int_reg;
reg   [31:0] p_read25_int_reg;
reg   [31:0] p_read26_int_reg;
reg   [31:0] p_read27_int_reg;
reg   [31:0] p_read28_int_reg;
reg   [31:0] p_read29_int_reg;
reg   [31:0] p_read30_int_reg;
reg   [31:0] p_read31_int_reg;
reg   [31:0] p_read32_int_reg;
reg   [31:0] p_read33_int_reg;
reg   [31:0] p_read34_int_reg;
reg   [31:0] p_read35_int_reg;
reg   [31:0] p_read36_int_reg;
reg   [31:0] p_read37_int_reg;
reg   [31:0] p_read38_int_reg;
reg   [31:0] p_read39_int_reg;
reg   [31:0] p_read40_int_reg;
reg   [31:0] p_read41_int_reg;
reg   [31:0] p_read42_int_reg;
reg   [31:0] p_read43_int_reg;
reg   [31:0] p_read44_int_reg;
reg   [31:0] prev_sum_int_reg;
wire    ap_ce_reg;

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U195(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_reg_683),
    .din1(mul_s_reg_688),
    .ce(1'b1),
    .dout(grp_fu_390_p2)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U196(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_3_reg_693),
    .din1(mul_1_reg_698),
    .ce(1'b1),
    .dout(grp_fu_394_p2)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U197(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_1_1_reg_703),
    .din1(mul_1_2_reg_708),
    .ce(1'b1),
    .dout(grp_fu_398_p2)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U198(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_2_reg_713),
    .din1(mul_2_1_reg_718),
    .ce(1'b1),
    .dout(grp_fu_402_p2)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U199(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_2_2_reg_723),
    .din1(prev_sum_read_reg_588_pp0_iter4_reg),
    .ce(1'b1),
    .dout(grp_fu_406_p2)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U200(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(s0_reg_728),
    .din1(s1_reg_733),
    .ce(1'b1),
    .dout(grp_fu_410_p2)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U201(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(s2_reg_738),
    .din1(s3_reg_743),
    .ce(1'b1),
    .dout(grp_fu_414_p2)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U202(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(s5_reg_753),
    .din1(s6_reg_758),
    .ce(1'b1),
    .dout(grp_fu_418_p2)
);

HW_accel_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U203(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(s7_reg_763),
    .din1(s4_reg_748_pp0_iter19_reg),
    .ce(1'b1),
    .dout(grp_fu_422_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U204(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_reg_638),
    .din1(p_read_24_reg_633),
    .ce(1'b1),
    .dout(grp_fu_426_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U205(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_8_reg_643),
    .din1(p_read_23_reg_628),
    .ce(1'b1),
    .dout(grp_fu_430_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U206(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_9_reg_648),
    .din1(p_read_22_reg_623),
    .ce(1'b1),
    .dout(grp_fu_434_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U207(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_s_reg_653),
    .din1(p_read_21_reg_618),
    .ce(1'b1),
    .dout(grp_fu_438_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U208(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_1_reg_658),
    .din1(p_read_20_reg_613),
    .ce(1'b1),
    .dout(grp_fu_442_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U209(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_2_reg_663),
    .din1(p_read_19_reg_608),
    .ce(1'b1),
    .dout(grp_fu_446_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U210(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_3_reg_668),
    .din1(p_read_18_reg_603),
    .ce(1'b1),
    .dout(grp_fu_450_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U211(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_4_reg_673),
    .din1(p_read_17_reg_598),
    .ce(1'b1),
    .dout(grp_fu_454_p2)
);

HW_accel_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U212(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_5_reg_678),
    .din1(p_read_16_reg_593),
    .ce(1'b1),
    .dout(grp_fu_458_p2)
);

HW_accel_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U213(
    .din0(p_read_int_reg),
    .din1(p_read9_int_reg),
    .din2(p_read18_int_reg),
    .din3(p_read27_int_reg),
    .din4(kch_int_reg),
    .dout(tmp_fu_462_p6)
);

HW_accel_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U214(
    .din0(p_read1_int_reg),
    .din1(p_read10_int_reg),
    .din2(p_read19_int_reg),
    .din3(p_read28_int_reg),
    .din4(kch_int_reg),
    .dout(tmp_8_fu_476_p6)
);

HW_accel_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U215(
    .din0(p_read2_int_reg),
    .din1(p_read11_int_reg),
    .din2(p_read20_int_reg),
    .din3(p_read29_int_reg),
    .din4(kch_int_reg),
    .dout(tmp_9_fu_490_p6)
);

HW_accel_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U216(
    .din0(p_read3_int_reg),
    .din1(p_read12_int_reg),
    .din2(p_read21_int_reg),
    .din3(p_read30_int_reg),
    .din4(kch_int_reg),
    .dout(tmp_s_fu_504_p6)
);

HW_accel_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U217(
    .din0(p_read4_int_reg),
    .din1(p_read13_int_reg),
    .din2(p_read22_int_reg),
    .din3(p_read31_int_reg),
    .din4(kch_int_reg),
    .dout(tmp_1_fu_518_p6)
);

HW_accel_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U218(
    .din0(p_read5_int_reg),
    .din1(p_read14_int_reg),
    .din2(p_read23_int_reg),
    .din3(p_read32_int_reg),
    .din4(kch_int_reg),
    .dout(tmp_2_fu_532_p6)
);

HW_accel_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U219(
    .din0(p_read6_int_reg),
    .din1(p_read15_int_reg),
    .din2(p_read24_int_reg),
    .din3(p_read33_int_reg),
    .din4(kch_int_reg),
    .dout(tmp_3_fu_546_p6)
);

HW_accel_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U220(
    .din0(p_read7_int_reg),
    .din1(p_read16_int_reg),
    .din2(p_read25_int_reg),
    .din3(p_read34_int_reg),
    .din4(kch_int_reg),
    .dout(tmp_4_fu_560_p6)
);

HW_accel_mux_42_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_42_32_1_1_U221(
    .din0(p_read8_int_reg),
    .din1(p_read17_int_reg),
    .din2(p_read26_int_reg),
    .din3(p_read35_int_reg),
    .din4(kch_int_reg),
    .dout(tmp_5_fu_574_p6)
);

always @ (posedge ap_clk) begin
    kch_int_reg <= kch;
end

always @ (posedge ap_clk) begin
    p_read10_int_reg <= p_read10;
end

always @ (posedge ap_clk) begin
    p_read11_int_reg <= p_read11;
end

always @ (posedge ap_clk) begin
    p_read12_int_reg <= p_read12;
end

always @ (posedge ap_clk) begin
    p_read13_int_reg <= p_read13;
end

always @ (posedge ap_clk) begin
    p_read14_int_reg <= p_read14;
end

always @ (posedge ap_clk) begin
    p_read15_int_reg <= p_read15;
end

always @ (posedge ap_clk) begin
    p_read16_int_reg <= p_read16;
end

always @ (posedge ap_clk) begin
    p_read17_int_reg <= p_read17;
end

always @ (posedge ap_clk) begin
    p_read18_int_reg <= p_read18;
end

always @ (posedge ap_clk) begin
    p_read19_int_reg <= p_read19;
end

always @ (posedge ap_clk) begin
    p_read1_int_reg <= p_read1;
end

always @ (posedge ap_clk) begin
    p_read20_int_reg <= p_read20;
end

always @ (posedge ap_clk) begin
    p_read21_int_reg <= p_read21;
end

always @ (posedge ap_clk) begin
    p_read22_int_reg <= p_read22;
end

always @ (posedge ap_clk) begin
    p_read23_int_reg <= p_read23;
end

always @ (posedge ap_clk) begin
    p_read24_int_reg <= p_read24;
end

always @ (posedge ap_clk) begin
    p_read25_int_reg <= p_read25;
end

always @ (posedge ap_clk) begin
    p_read26_int_reg <= p_read26;
end

always @ (posedge ap_clk) begin
    p_read27_int_reg <= p_read27;
end

always @ (posedge ap_clk) begin
    p_read28_int_reg <= p_read28;
end

always @ (posedge ap_clk) begin
    p_read29_int_reg <= p_read29;
end

always @ (posedge ap_clk) begin
    p_read2_int_reg <= p_read2;
end

always @ (posedge ap_clk) begin
    p_read30_int_reg <= p_read30;
end

always @ (posedge ap_clk) begin
    p_read31_int_reg <= p_read31;
end

always @ (posedge ap_clk) begin
    p_read32_int_reg <= p_read32;
end

always @ (posedge ap_clk) begin
    p_read33_int_reg <= p_read33;
end

always @ (posedge ap_clk) begin
    p_read34_int_reg <= p_read34;
end

always @ (posedge ap_clk) begin
    p_read35_int_reg <= p_read35;
end

always @ (posedge ap_clk) begin
    p_read36_int_reg <= p_read36;
end

always @ (posedge ap_clk) begin
    p_read37_int_reg <= p_read37;
end

always @ (posedge ap_clk) begin
    p_read38_int_reg <= p_read38;
end

always @ (posedge ap_clk) begin
    p_read39_int_reg <= p_read39;
end

always @ (posedge ap_clk) begin
    p_read3_int_reg <= p_read3;
end

always @ (posedge ap_clk) begin
    p_read40_int_reg <= p_read40;
end

always @ (posedge ap_clk) begin
    p_read41_int_reg <= p_read41;
end

always @ (posedge ap_clk) begin
    p_read42_int_reg <= p_read42;
end

always @ (posedge ap_clk) begin
    p_read43_int_reg <= p_read43;
end

always @ (posedge ap_clk) begin
    p_read44_int_reg <= p_read44;
end

always @ (posedge ap_clk) begin
    p_read4_int_reg <= p_read4;
end

always @ (posedge ap_clk) begin
    p_read5_int_reg <= p_read5;
end

always @ (posedge ap_clk) begin
    p_read6_int_reg <= p_read6;
end

always @ (posedge ap_clk) begin
    p_read7_int_reg <= p_read7;
end

always @ (posedge ap_clk) begin
    p_read8_int_reg <= p_read8;
end

always @ (posedge ap_clk) begin
    p_read9_int_reg <= p_read9;
end

always @ (posedge ap_clk) begin
    p_read_int_reg <= p_read;
end

always @ (posedge ap_clk) begin
    prev_sum_int_reg <= prev_sum;
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        mul_1_1_reg_703 <= grp_fu_442_p2;
        mul_1_2_reg_708 <= grp_fu_446_p2;
        mul_1_reg_698 <= grp_fu_438_p2;
        mul_2_1_reg_718 <= grp_fu_454_p2;
        mul_2_2_reg_723 <= grp_fu_458_p2;
        mul_2_reg_713 <= grp_fu_450_p2;
        mul_3_reg_693 <= grp_fu_434_p2;
        mul_reg_683 <= grp_fu_426_p2;
        mul_s_reg_688 <= grp_fu_430_p2;
        p_read_16_reg_593 <= p_read44_int_reg;
        p_read_17_reg_598 <= p_read43_int_reg;
        p_read_18_reg_603 <= p_read42_int_reg;
        p_read_19_reg_608 <= p_read41_int_reg;
        p_read_20_reg_613 <= p_read40_int_reg;
        p_read_21_reg_618 <= p_read39_int_reg;
        p_read_22_reg_623 <= p_read38_int_reg;
        p_read_23_reg_628 <= p_read37_int_reg;
        p_read_24_reg_633 <= p_read36_int_reg;
        prev_sum_read_reg_588 <= prev_sum_int_reg;
        prev_sum_read_reg_588_pp0_iter1_reg <= prev_sum_read_reg_588;
        prev_sum_read_reg_588_pp0_iter2_reg <= prev_sum_read_reg_588_pp0_iter1_reg;
        prev_sum_read_reg_588_pp0_iter3_reg <= prev_sum_read_reg_588_pp0_iter2_reg;
        prev_sum_read_reg_588_pp0_iter4_reg <= prev_sum_read_reg_588_pp0_iter3_reg;
        s0_reg_728 <= grp_fu_390_p2;
        s1_reg_733 <= grp_fu_394_p2;
        s2_reg_738 <= grp_fu_398_p2;
        s3_reg_743 <= grp_fu_402_p2;
        s4_reg_748 <= grp_fu_406_p2;
        s4_reg_748_pp0_iter10_reg <= s4_reg_748;
        s4_reg_748_pp0_iter11_reg <= s4_reg_748_pp0_iter10_reg;
        s4_reg_748_pp0_iter12_reg <= s4_reg_748_pp0_iter11_reg;
        s4_reg_748_pp0_iter13_reg <= s4_reg_748_pp0_iter12_reg;
        s4_reg_748_pp0_iter14_reg <= s4_reg_748_pp0_iter13_reg;
        s4_reg_748_pp0_iter15_reg <= s4_reg_748_pp0_iter14_reg;
        s4_reg_748_pp0_iter16_reg <= s4_reg_748_pp0_iter15_reg;
        s4_reg_748_pp0_iter17_reg <= s4_reg_748_pp0_iter16_reg;
        s4_reg_748_pp0_iter18_reg <= s4_reg_748_pp0_iter17_reg;
        s4_reg_748_pp0_iter19_reg <= s4_reg_748_pp0_iter18_reg;
        s5_reg_753 <= grp_fu_410_p2;
        s6_reg_758 <= grp_fu_414_p2;
        s7_reg_763 <= grp_fu_418_p2;
        tmp_1_reg_658 <= tmp_1_fu_518_p6;
        tmp_2_reg_663 <= tmp_2_fu_532_p6;
        tmp_3_reg_668 <= tmp_3_fu_546_p6;
        tmp_4_reg_673 <= tmp_4_fu_560_p6;
        tmp_5_reg_678 <= tmp_5_fu_574_p6;
        tmp_8_reg_643 <= tmp_8_fu_476_p6;
        tmp_9_reg_648 <= tmp_9_fu_490_p6;
        tmp_reg_638 <= tmp_fu_462_p6;
        tmp_s_reg_653 <= tmp_s_fu_504_p6;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_return = grp_fu_422_p2;

endmodule //HW_accel_conv2D_4_s
